<?php
namespace ProcessWire;

final class MercatoPrivacyService extends Wire {
    private string $logName = 'mercato-privacy';
    public function __construct(private Mercato $commerce) { parent::__construct(); }

    public function exportCustomer(string $email): array {
        $email = strtolower((string) $this->wire('sanitizer')->email($email)); if ($email === '') throw new WireException('A valid customer email is required.');
        $orders = $this->findOrders($email); $quotes = $this->findQuotes($email); $account = $this->wire('users')->get('email=' . $this->wire('sanitizer')->selectorValue($email));
        $data = ['format' => 'mercato-privacy-export-v1', 'generated_at' => date(DATE_ATOM), 'policy_version' => (string) $this->commerce->privacy_policy_version, 'subject' => ['email' => $email], 'categories' => ['account' => $account && $account->id ? ['id' => (int) $account->id, 'name' => (string) $account->name, 'email' => (string) $account->email, 'created' => date(DATE_ATOM, (int) $account->created), 'profile' => ['first_name' => (string) ($account->mrc_first_name ?? ''), 'last_name' => (string) ($account->mrc_last_name ?? ''), 'phone' => (string) ($account->mrc_phone ?? ''), 'addresses' => json_decode((string) ($account->mrc_customer_addresses ?? ''), true) ?: [], 'preferences' => json_decode((string) ($account->mrc_customer_preferences ?? ''), true) ?: []]] : null, 'orders' => [], 'quotes' => [], 'recovery_preferences' => ['suppressed' => $this->commerce->isRecoveryEmailSuppressed($email)]]];
        foreach ($orders as $order) $data['categories']['orders'][] = $this->portableOrder($order);
        foreach ($quotes as $quote) $data['categories']['quotes'][] = ['id' => (int) $quote->id, 'number' => (string) $quote->mrc_quote_number, 'status' => (string) $quote->mrc_quote_status, 'created' => date(DATE_ATOM, (int) $quote->created), 'expires' => (string) $quote->mrc_quote_expires, 'items' => json_decode((string) $quote->mrc_items, true), 'total' => (float) $quote->mrc_total_amount];
        $data = $this->commerce->privacyExport($data, $email);
        $this->audit('export_completed', ['email_hash' => hash('sha256', $email), 'orders' => count($data['categories']['orders']), 'quotes' => count($data['categories']['quotes']), 'operator' => (string) $this->wire('user')->name]);
        return $data;
    }

    public function reviewCustomer(string $email): array {
        $email = strtolower((string) $this->wire('sanitizer')->email($email)); $orders = $this->findOrders($email); $rows = []; $blocked = 0;
        foreach ($orders as $order) { $blockers = $this->orderBlockers($order); if ($blockers) $blocked++; $rows[] = ['order_id' => (int) $order->id, 'invoice' => (string) ($order->mrc_invoice_number ?: $order->title), 'payment_status' => (string) $order->mrc_payment_status, 'fulfilment_status' => (string) ($order->mrc_fulfilment_status ?? ''), 'legal_hold' => (bool) ($order->mrc_privacy_legal_hold ?? false), 'already_anonymized' => trim((string) ($order->mrc_privacy_anonymized_date ?? '')) !== '', 'blockers' => $blockers]; }
        return ['email' => $email, 'email_hash' => hash('sha256', $email), 'orders' => $rows, 'total' => count($rows), 'blocked' => $blocked, 'eligible' => count($rows) - $blocked, 'quotes' => count($this->findQuotes($email))];
    }

    public function anonymizeCustomer(string $email, string $reason, string $policyVersion = '', string $requestType = 'anonymization'): array {
        $email = strtolower((string) $this->wire('sanitizer')->email($email)); $reason = trim($reason); if ($email === '' || $reason === '') throw new WireException('Customer email and review reason are required.');
        $review = $this->reviewCustomer($email); if ($review['blocked'] > 0) { $this->audit('anonymization_blocked', ['email_hash' => $review['email_hash'], 'reason' => $reason, 'blocked' => $review['blocked'], 'orders' => $review['orders'], 'operator' => (string) $this->wire('user')->name]); throw new WireException('Privacy action blocked by legal hold, dispute, refund, reservation, or active fulfilment.'); }
        $requestId = 'privacy-' . date('YmdHis') . '-' . substr($review['email_hash'], 0, 12); $version = trim($policyVersion) ?: (string) ($this->commerce->privacy_policy_version ?: 'unversioned');
        $this->audit('request_reviewed', ['request_id' => $requestId, 'request_type' => $requestType, 'request_status' => 'approved', 'policy_version' => $version, 'email_hash' => $review['email_hash'], 'reason' => $reason, 'operator' => (string) $this->wire('user')->name]);
        $pushRevoked = 0; $changed = 0; foreach ($this->findOrders($email) as $order) { $pushRevoked += $this->commerce->pushNotificationService()->revokeOwner('order', (int) $order->id); if ($this->anonymizeOrder($order, $review['email_hash'], $requestId)) $changed++; }
        $quotes = 0; foreach ($this->findQuotes($email) as $quote) { $quote->of(false); $quote->mrc_first_name = 'Anonymized'; $quote->mrc_last_name = 'Customer'; $quote->mrc_email = $this->anonymousEmail($review['email_hash']); foreach (['mrc_phone', 'mrc_address', 'mrc_address_2', 'mrc_city', 'mrc_zip', 'mrc_country', 'mrc_notes'] as $field) if ($quote->hasField($field)) $quote->set($field, ''); if ($quote->hasField('mrc_quote_customer_user_id')) $quote->mrc_quote_customer_user_id = 0; if ($quote->hasField('mrc_quote_token_seed')) $quote->mrc_quote_token_seed = bin2hex(random_bytes(24)); $this->wire('pages')->save($quote); $quotes++; }
        $accountChanged = false; $account = $this->wire('users')->get('email=' . $this->wire('sanitizer')->selectorValue($email)); if ($account && $account->id && !$account->isSuperuser()) { $pushRevoked += $this->commerce->pushNotificationService()->revokeOwner('account', (int) $account->id); $account->of(false); $account->email = $this->anonymousEmail($review['email_hash']); foreach (['mrc_first_name', 'mrc_last_name', 'mrc_phone', 'mrc_customer_addresses', 'mrc_customer_preferences', 'mrc_customer_verification', 'mrc_customer_password_reset'] as $field) if ($account->hasField($field)) $account->set($field, ''); if ($account->hasField('mrc_customer_verified')) $account->mrc_customer_verified = 0; $account->addStatus(Page::statusLocked); $this->wire('users')->save($account); $accountChanged = true; }
        $this->commerce->suppressRecoveryEmail($email, 'privacy_anonymization');
        $this->commerce->privacyAnonymized(['request_id' => $requestId, 'email_hash' => $review['email_hash'], 'orders' => $changed, 'quotes' => $quotes]);
        $this->audit('request_completed', ['request_id' => $requestId, 'request_type' => $requestType, 'request_status' => 'completed', 'policy_version' => $version, 'email_hash' => $review['email_hash'], 'orders' => $changed, 'quotes' => $quotes, 'completed_at' => date(DATE_ATOM), 'operator' => (string) $this->wire('user')->name]);
        return ['request_id' => $requestId, 'status' => 'completed', 'orders_anonymized' => $changed, 'quotes_anonymized' => $quotes, 'account_anonymized' => $accountChanged, 'push_registrations_revoked' => $pushRevoked, 'signed_links_invalidated' => $changed + $quotes];
    }

    public function deleteCustomerData(string $email, string $reason, string $policyVersion = ''): array {
        return $this->anonymizeCustomer($email, $reason, $policyVersion, 'deletion');
    }

    public function setLegalHold(Page $order, bool $hold, string $reason): array {
        if (!$order->hasField('mrc_privacy_legal_hold')) throw new WireException('Privacy fields are missing. Run installer/repair.');
        $order->of(false); $order->mrc_privacy_legal_hold = $hold ? 1 : 0; $details = json_decode((string) ($order->mrc_privacy_details ?? ''), true); $details = is_array($details) ? $details : []; $details['legal_hold'] = ['active' => $hold, 'reason' => trim($reason), 'operator' => (string) $this->wire('user')->name, 'at' => date(DATE_ATOM)]; if ($order->hasField('mrc_privacy_details')) $order->mrc_privacy_details = json_encode($details, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE); $this->wire('pages')->save($order);
        $result = ['order_id' => (int) $order->id, 'legal_hold' => $hold, 'reason' => trim($reason), 'operator' => (string) $this->wire('user')->name]; $this->audit('legal_hold_' . ($hold ? 'enabled' : 'released'), $result); return $result;
    }

    public function runRetention(bool $dryRun = true, int $limit = 100, ?int $now = null): array {
        $now ??= time(); $limit = max(1, min(500, $limit)); $rules = ['customer_data_days' => $this->commerce->getCustomerDataRetentionDays(), 'email_log_days' => (int) ($this->commerce->email_log_retention_days ?? 180), 'payment_attempt_days' => (int) ($this->commerce->payment_attempt_retention_days ?? 180), 'operational_log_days' => (int) ($this->commerce->operational_log_retention_days ?? 365), 'provider_reference_days' => (int) ($this->commerce->provider_reference_retention_days ?? 0), 'webhook_payload_days' => $this->commerce->getWebhookPayloadRetentionDays()]; $rules = $this->commerce->privacyRetentionRules($rules);
        $result = ['dry_run' => $dryRun, 'at' => date(DATE_ATOM, $now), 'limit' => $limit, 'rules' => $rules, 'orders' => ['matched' => 0, 'anonymized' => 0, 'blocked' => 0, 'rows' => []], 'provider_references' => ['matched' => 0, 'redacted' => 0], 'logs' => []];
        $days = max(0, (int) ($rules['customer_data_days'] ?? 0)); if ($days > 0) foreach ($this->wire('pages')->find('template=' . $this->wire('sanitizer')->selectorValue((string) $this->commerce->order_template) . ', include=all, sort=created, limit=' . $limit) as $order) { if (!MercatoPrivacyRetentionPolicy::isOlderThan((int) $order->created, $days, $now) || trim((string) ($order->mrc_privacy_anonymized_date ?? '')) !== '') continue; $blockers = $this->orderBlockers($order); $result['orders']['matched']++; $result['orders']['rows'][] = ['order_id' => (int) $order->id, 'created' => date(DATE_ATOM, (int) $order->created), 'action' => $blockers ? 'blocked' : 'anonymize', 'blockers' => $blockers]; if ($blockers) { $result['orders']['blocked']++; continue; } if (!$dryRun && $this->anonymizeOrder($order, hash('sha256', strtolower((string) $order->mrc_email)), 'scheduled-retention')) $result['orders']['anonymized']++; }
        $providerDays = max(0, (int) ($rules['provider_reference_days'] ?? 0)); if ($providerDays > 0) foreach ($this->wire('pages')->find('template=' . $this->wire('sanitizer')->selectorValue((string) $this->commerce->order_template) . ', include=all, mrc_payment_complete=0, sort=created, limit=' . $limit) as $order) { if (!MercatoPrivacyRetentionPolicy::isOlderThan((int) $order->created, $providerDays, $now) || $this->orderBlockers($order)) continue; $hasReference = trim((string) ($order->mrc_stripe_payment_intent_id ?? '')) !== '' || trim((string) ($order->mrc_mollie_payment_id ?? '')) !== '' || trim((string) ($order->mrc_stripe_customer_id ?? '')) !== ''; if (!$hasReference) continue; $result['provider_references']['matched']++; if (!$dryRun) { $order->of(false); foreach (['mrc_stripe_payment_intent_id', 'mrc_mollie_payment_id', 'mrc_stripe_customer_id'] as $field) if ($order->hasField($field)) $order->set($field, ''); $this->wire('pages')->save($order); $result['provider_references']['redacted']++; } }
        foreach (['mercato-notifications' => max(1, (int) ($rules['email_log_days'] ?? 180)), 'mercato-payment-attempts' => max(1, (int) ($rules['payment_attempt_days'] ?? 180)), 'mercato-customer-notes' => max(1, (int) ($rules['operational_log_days'] ?? 365)), 'mercato-order-notes' => max(1, (int) ($rules['operational_log_days'] ?? 365)), 'mercato-recovery' => max(1, (int) ($rules['operational_log_days'] ?? 365))] as $log => $retentionDays) $result['logs'][$log] = $this->redactLog($log, $retentionDays, $limit, $dryRun, $now);
        if (!$dryRun) { $webhook = new MercatoWebhookEventLog(); $webhook->setWire($this->wire()); $result['logs']['mercato-webhooks'] = $webhook->redactPayloadsOlderThan(max(1, (int) $rules['webhook_payload_days'])); }
        else $result['logs']['mercato-webhooks'] = ['dry_run' => true, 'retention_days' => max(1, (int) $rules['webhook_payload_days'])];
        $this->audit('retention_' . ($dryRun ? 'dry_run' : 'completed'), ['summary' => $result, 'operator' => (string) ($this->wire('user')->name ?: 'system')]); return $result;
    }

    private function anonymizeOrder(Page $order, string $hash, string $requestId): bool {
        if (trim((string) ($order->mrc_privacy_anonymized_date ?? '')) !== '') return false; $order->of(false);
        $this->commerce->pushNotificationService()->revokeOwner('order', (int) $order->id);
        foreach (['mrc_first_name' => 'Anonymized', 'mrc_last_name' => 'Customer', 'mrc_email' => $this->anonymousEmail($hash), 'mrc_phone' => '', 'mrc_address' => '', 'mrc_address_2' => '', 'mrc_city' => '', 'mrc_zip' => '', 'mrc_country' => '', 'mrc_notes' => '', 'mrc_fulfilment_notes' => '', 'mrc_fulfilment_tracking_url' => ''] as $field => $value) if ($order->hasField($field)) $order->set($field, $value);
        foreach (['mrc_billing_address', 'mrc_shipping_address'] as $field) if ($order->hasField($field)) $order->set($field, json_encode(['redacted' => true, 'request_id' => $requestId]));
        if ($order->hasField('mrc_customer_user_id')) $order->mrc_customer_user_id = 0; if ($order->hasField('mrc_customer_claim_details')) $order->mrc_customer_claim_details = '';
        if ($order->hasField('mrc_status_token_seed')) $order->mrc_status_token_seed = bin2hex(random_bytes(24)); if ($order->hasField('mrc_privacy_anonymized_date')) $order->mrc_privacy_anonymized_date = date('Y-m-d H:i:s'); if ($order->hasField('mrc_privacy_details')) $order->mrc_privacy_details = json_encode(['request_id' => $requestId, 'email_hash' => $hash, 'at' => date(DATE_ATOM)], JSON_UNESCAPED_SLASHES); $this->wire('pages')->save($order); return true;
    }

    private function orderBlockers(Page $order): array { $details = strtolower((string) ($order->mrc_payment_details ?? '')); return MercatoPrivacyRetentionPolicy::orderBlockers(['legal_hold' => (bool) ($order->mrc_privacy_legal_hold ?? false), 'payment_status' => (string) $order->mrc_payment_status, 'paid' => (int) $order->mrc_payment_complete === 1, 'dispute_open' => str_contains($details, 'dispute') && !str_contains($details, 'dispute_closed'), 'inventory_reserved' => (int) ($order->mrc_inventory_reserved ?? 0) === 1, 'fulfilment_status' => (string) ($order->mrc_fulfilment_status ?? '')]); }
    private function findOrders(string $email): PageArray { return $this->wire('pages')->find('template=' . $this->wire('sanitizer')->selectorValue((string) $this->commerce->order_template) . ', mrc_email=' . $this->wire('sanitizer')->selectorValue($email) . ', include=all, sort=created, limit=10000'); }
    private function findQuotes(string $email): PageArray { return $this->wire('pages')->find('template=mrc-quote, mrc_email=' . $this->wire('sanitizer')->selectorValue($email) . ', include=all, sort=created, limit=10000'); }
    private function anonymousEmail(string $hash): string { return 'anonymous-' . substr($hash, 0, 20) . '@privacy.invalid'; }
    private function portableOrder(Page $order): array { return ['id' => (int) $order->id, 'invoice' => (string) ($order->mrc_invoice_number ?: $order->title), 'created' => date(DATE_ATOM, (int) $order->created), 'contact' => ['first_name' => (string) $order->mrc_first_name, 'last_name' => (string) $order->mrc_last_name, 'email' => (string) $order->mrc_email, 'phone' => (string) $order->mrc_phone], 'billing_address' => json_decode((string) $order->mrc_billing_address, true), 'shipping_address' => json_decode((string) $order->mrc_shipping_address, true), 'items' => json_decode((string) $order->mrc_items, true), 'amounts' => ['currency' => (string) $order->mrc_currency, 'subtotal' => (float) $order->mrc_subtotal_amount, 'shipping' => (float) $order->mrc_shipping_amount, 'discount' => (float) $order->mrc_discount_total, 'tax' => (float) $order->mrc_tax_amount, 'total' => (float) $order->mrc_total_amount, 'refunded' => (float) $order->mrc_refunded_amount], 'payment' => ['method' => (string) $order->mrc_payment_method, 'status' => (string) $order->mrc_payment_status], 'fulfilment' => ['method' => (string) $order->mrc_fulfilment_method, 'status' => (string) $order->mrc_fulfilment_status, 'tracking' => (string) $order->mrc_fulfilment_tracking], 'policy_acceptance' => json_decode((string) $order->mrc_policy_acceptance_details, true)]; }
    private function redactLog(string $name, int $days, int $limit, bool $dryRun, int $now): array { $path = rtrim((string) $this->wire('config')->paths->logs, '/') . '/' . $name . '.txt'; $result = ['matched' => 0, 'redacted' => 0, 'retention_days' => $days, 'dry_run' => $dryRun]; if (!is_readable($path)) return $result; $lines = file($path, FILE_IGNORE_NEW_LINES) ?: []; foreach ($lines as $i => $line) { if ($result['matched'] >= $limit) break; $created = strtotime(substr($line, 0, 19)) ?: 0; if (!MercatoPrivacyRetentionPolicy::isOlderThan($created, $days, $now)) continue; $json = strstr($line, '{'); $row = $json ? json_decode($json, true) : null; if (!is_array($row) || !empty($row['privacy_retention_redacted'])) continue; $result['matched']++; if ($dryRun) continue; foreach (['recipient', 'email', 'message', 'context', 'payload'] as $key) if (array_key_exists($key, $row)) $row[$key] = '[redacted]'; $row['privacy_retention_redacted'] = true; $row['privacy_retention_at'] = date(DATE_ATOM, $now); $lines[$i] = substr($line, 0, (int) strpos($line, '{')) . json_encode($row, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE); $result['redacted']++; } if (!$dryRun && $result['redacted'] > 0) { $tmp = $path . '.privacy-' . getmypid(); file_put_contents($tmp, implode(PHP_EOL, $lines) . PHP_EOL, LOCK_EX); rename($tmp, $path); } return $result; }
    private function audit(string $event, array $data): array { $log = new MercatoEventLog($this->logName); $log->setWire($this->wire()); return $log->record(['event' => $event, 'policy_version' => (string) ($this->commerce->privacy_policy_version ?: 'unversioned')] + $data, $event); }
}
