<?php
declare(strict_types=1);

use ProcessWire\Page;
use ProcessWire\ProcessWire;
use ProcessWire\User;
use ProcessWire\WireException;

$action=$argv[1]??''; $site=rtrim((string)getenv('MERCATO_E2E_SITE'),'/'); $stateFile=(string)getenv('MERCATO_E2E_STATE');
if(!in_array($action,['setup','capture','verify','cleanup'],true)||$site===''||$stateFile===''){fwrite(STDERR,"Usage: MERCATO_E2E_SITE=/site MERCATO_E2E_STATE=/tmp/state.json php public-visual-fixtures.php setup|capture|verify|cleanup\n");exit(2);}
require $site.'/wire/core/ProcessWire.php'; $config=ProcessWire::buildConfig($site);$config->dbHost='127.0.0.1';$wire=new ProcessWire($config);$commerce=$wire->modules->get('Mercato');
if(!$commerce||!empty($commerce->production))throw new WireException('Public visual fixtures are forbidden in production mode.');$superuser=$wire->users->get('template=user,roles.name=superuser');if(!$superuser->id)throw new WireException('A superuser is required.');$wire->users->setCurrentUser($superuser);$wire->set('page',$wire->pages->get('/'));
$write=static function(array $state)use($stateFile):void{if(file_put_contents($stateFile,json_encode($state,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE))===false)throw new WireException('Could not persist public visual state.');};
$load=static function()use($stateFile):array{if(!is_file($stateFile))throw new WireException('Public visual state is missing.');return json_decode((string)file_get_contents($stateFile),true,512,JSON_THROW_ON_ERROR);};
$cleanup=static function(array $state)use($wire,$commerce):array{$run=(string)($state['run_id']??'');$deleted=['orders'=>0,'quotes'=>0,'products'=>0,'pages'=>0,'users'=>0,'logs'=>0];$deletedPageIds=array_merge((array)($state['order_ids']??[]),(array)($state['quote_ids']??[]),(array)($state['product_ids']??[]),(array)($state['page_ids']??[]));
 foreach((array)($state['order_ids']??[])as$id){$p=$wire->pages->get((int)$id);if(!$p->id)continue;if(!str_contains(strtolower((string)$p->mrc_email),$run))throw new WireException("Refusing order {$p->id} cleanup.");$wire->pages->delete($p,true);$deleted['orders']++;}
 $email=(string)($state['checkout_email']??'');if($email!==''){foreach($wire->pages->find('template='.$wire->sanitizer->selectorValue((string)$commerce->order_template).',include=all,mrc_email='.$wire->sanitizer->selectorValue($email))as$p){$deletedPageIds[]=(int)$p->id;$wire->pages->delete($p,true);$deleted['orders']++;}}
 foreach((array)($state['quote_ids']??[])as$id){$p=$wire->pages->get((int)$id);if($p->id){$wire->pages->delete($p,true);$deleted['quotes']++;}}
 foreach(array_reverse((array)($state['product_ids']??[]))as$id){$p=$wire->pages->get((int)$id);if($p->id){if(!str_starts_with((string)$p->name,'e2e-public-visual-'))throw new WireException("Refusing product {$p->id} cleanup.");$wire->pages->delete($p,true);$deleted['products']++;}}
 foreach(array_reverse((array)($state['page_ids']??[]))as$id){$p=$wire->pages->get((int)$id);if($p->id){if(!str_starts_with((string)$p->name,'e2e-public-visual-'))throw new WireException("Refusing page {$p->id} cleanup.");$wire->pages->delete($p,true);$deleted['pages']++;}}
 foreach((array)($state['users']??[])as$row){$u=$wire->users->get((int)$row['id']);if($u->id){if((string)$u->name!==(string)$row['name'])throw new WireException("Refusing user {$u->id} cleanup.");$wire->users->delete($u);$deleted['users']++;}}
 $stored=(array)$wire->modules->getConfig('Mercato');foreach((array)($state['original_config']??[])as$k=>$v){if(!empty($v['exists']))$stored[$k]=$v['value'];else unset($stored[$k]);}$wire->modules->saveConfig('Mercato',$stored);
 $root=rtrim((string)$wire->config->paths->logs,'/').'/';foreach(glob($root.'*.txt')?:[]as$path){$lines=file($path);if($lines===false)continue;$kept=[];foreach($lines as$line){if($run!==''&&str_contains($line,$run)){$deleted['logs']++;continue;}$kept[]=$line;}if(count($kept)!==count($lines)){if($kept===[])@unlink($path);else file_put_contents($path,implode('',$kept),LOCK_EX);}}
 $pageExists=$wire->database->prepare('SELECT COUNT(*) FROM pages WHERE id=:id');foreach(array_unique(array_map('intval',$deletedPageIds))as$id){$pageExists->execute([':id'=>$id]);if((int)$pageExists->fetchColumn()!==0)throw new WireException("Fixture page {$id} remains after cleanup.");}
 foreach((array)($state['users']??[])as$row){$pageExists->execute([':id'=>(int)$row['id']]);if((int)$pageExists->fetchColumn()!==0)throw new WireException("Fixture user {$row['id']} remains after cleanup.");}
 $restored=(array)$wire->modules->getConfig('Mercato');foreach((array)($state['original_config']??[])as$k=>$v){if(!empty($v['exists'])&&(!array_key_exists($k,$restored)||$restored[$k]!==$v['value']))throw new WireException("Config {$k} was not restored exactly.");if(empty($v['exists'])&&array_key_exists($k,$restored))throw new WireException("Config {$k} was not removed during cleanup.");}
 foreach(glob($root.'*.txt')?:[]as$path)if($run!==''&&str_contains((string)file_get_contents($path),$run))throw new WireException("Run-owned log data remains in {$path}.");
 return$deleted;};
if($action==='cleanup'){if(!is_file($stateFile)){echo"No public visual state; nothing to clean.\n";exit(0);}$result=$cleanup($load());if(!unlink($stateFile))throw new WireException('Could not remove the cleaned public visual state file.');echo json_encode(['cleaned'=>true]+$result,JSON_UNESCAPED_SLASHES)."\n";exit(0);}
if($action!=='setup'){$state=$load();$safe=$wire->sanitizer->selectorValue((string)$state['checkout_email']);$found=$wire->pages->find('template='.$wire->sanitizer->selectorValue((string)$commerce->order_template).",include=all,mrc_email={$safe},limit=2");if($found->count()!==1)throw new WireException('Expected one browser-created visual checkout order.');$order=$found->first();
 if($action==='capture'){$relative=static function(string$url):string{$p=(string)(parse_url($url,PHP_URL_PATH)?:'/');$q=(string)(parse_url($url,PHP_URL_QUERY)?:'');return$p.($q!==''?'?'.$q:'');};$state['browser_order_id']=(int)$order->id;$state['browser_invoice']=(string)$order->mrc_invoice_number;$state['status_url']=$relative($commerce->getOrderStatusUrl($order));$state['receipt_url']=$relative($commerce->getOrderReceiptUrl($order));$state['access_url']=$relative($commerce->getOrderAccessRecoveryUrl($order));$state['unsubscribe_url']=$relative($commerce->getRecoveryUnsubscribeUrl((string)$order->mrc_email));if(!empty($state['large_items'])){$order->of(false);$order->mrc_items=(string)$state['large_items'];$order->mrc_subtotal_amount=495;$order->mrc_total_amount=495;$wire->pages->save($order);$order=$wire->pages->getById((int)$order->id,['cache'=>false])->first();}$state['large_status_url']=$relative($commerce->getOrderStatusUrl($order));$state['large_receipt_url']=$relative($commerce->getOrderReceiptUrl($order));$write($state);echo json_encode(['captured'=>true,'order_id'=>(int)$order->id],JSON_UNESCAPED_SLASHES)."\n";exit(0);}
 if((string)$order->mrc_payment_status!=='paid'||(int)$order->mrc_payment_complete!==1||(int)$order->mrc_inventory_adjusted!==1)throw new WireException('Visual checkout did not persist exact paid/inventory state.');$product=$wire->pages->getById((int)$state['checkout_product_id'],['cache'=>false])->first();if((int)$product->mrc_stock!==(int)$state['checkout_initial_stock']-1)throw new WireException('Visual checkout stock changed incorrectly.');foreach((array)$state['order_ids']as$id){$p=$wire->pages->get((int)$id);if(!$p->id||(string)$p->mrc_payment_status!=='paid')throw new WireException('Visual account history fixture regressed.');}echo json_encode(['verified'=>true,'screens'=>15,'products'=>count($state['product_ids']),'orders'=>count($state['order_ids'])+1,'stock'=>(int)$product->mrc_stock],JSON_UNESCAPED_SLASHES)."\n";exit(0);}
$run=gmdate('YmdHis').'-'.bin2hex(random_bytes(3));$password='E2E-Public-Visual-42!';$stored=(array)$wire->modules->getConfig('Mercato');$values=['enabled_payment_methods'=>['demo'],'checkout_enabled'=>true,'customer_accounts_mode'=>'optional','enabled_notification_events'=>[],'notification_sender_email'=>'','analytics_enabled'=>false,'access_recovery_enabled'=>true,'quote_requests_enabled'=>true,'quote_inventory_policy'=>'none','account_orders_per_page'=>5,'recovery_suppressed_emails'=>(string)($stored['recovery_suppressed_emails']??'')];$original=[];foreach($values as$k=>$v){$original[$k]=['exists'=>array_key_exists($k,$stored),'value'=>$stored[$k]??null];$stored[$k]=$v;}$wire->modules->saveConfig('Mercato',$stored);foreach($values as$k=>$v)$commerce->set($k,$v);
$state=['schema_version'=>1,'run_id'=>$run,'password'=>$password,'product_ids'=>[],'page_ids'=>[],'order_ids'=>[],'quote_ids'=>[],'users'=>[],'original_config'=>$original,'checkout_email'=>"e2e-{$run}-checkout@example.test",'checkout_initial_stock'=>30];$write($state);
$products=$wire->pages->get('/products/');$collections=$wire->pages->get('/collections/');$quotes=$wire->pages->get('/quotes/');if(!$products->id||!$collections->id||!$quotes->id)throw new WireException('Demo storefront parents are required.');
$makeCollection=static function(string$suffix,string$title,string$description='')use($wire,$collections,$run,&$state,$write):Page{$p=new Page();$p->template='mrc-collection';$p->parent=$collections;$p->name="e2e-public-visual-{$run}-{$suffix}";$p->title=$title;if($description!==''&&$p->hasField('mrc_description'))$p->mrc_description=$description;$wire->pages->save($p);$state['page_ids'][]=(int)$p->id;$write($state);return$p;};$normalCollection=$makeCollection('collection','Colección 日本語 العربية '.str_repeat('LongCollection',8),'<p>Collection longue 日本語 وصف عربي '.str_repeat('UnbrokenCollection',8).'</p>');$emptyCollection=$makeCollection('empty-collection','Empty visual collection');for($i=1;$i<=16;$i++)$makeCollection('large-collection-'.$i,sprintf('Visual collection %02d · Español 日本語',$i));
$long='LongContent'.str_repeat('Unbroken日本語العربية',10);for($i=1;$i<=24;$i++){$p=new Page();$p->template='mrc-product';$p->parent=$products;$p->name="e2e-public-visual-{$run}-product-{$i}";$p->title=$i===1?"Présentation 日本語 العربية {$long}":sprintf('Public visual product %02d · Español 日本語',$i);$p->mrc_description=$i===1?'<p>Mehrsprachiger Inhalt 日本語の説明 وصف عربي '.$long.'</p>':'<p>Deterministic visual product.</p>';$p->mrc_price=20+$i;$p->mrc_tax_rate=0;$p->mrc_shipping_price=4.5;$p->mrc_sku='PV-'.strtoupper(substr(hash('sha256',$run.$i),0,10));$p->mrc_product_type=$i%5===0?'digital':'physical';$p->mrc_product_status='active';$p->mrc_stock=$i===1?30:($i%6);$p->mrc_stock_policy=$i%7===0?'preorder':'deny';if($p->hasField('mrc_collections'))$p->mrc_collections->add($normalCollection);$wire->pages->save($p);$state['product_ids'][]=(int)$p->id;if($i===1){$state['checkout_product_id']=(int)$p->id;$state['long_product_url']=(string)$p->url;}$write($state);}
$largeProduct=$wire->pages->get((int)$state['product_ids'][1]);$variantValues=[];$variants=[];for($i=1;$i<=30;$i++){$id='edition-'.$i;$variantValues[]=['id'=>$id,'label'=>sprintf('Edition %02d · 日本語',$i)];$variants[]=['id'=>$id,'options'=>['edition'=>$id],'sku'=>(string)$largeProduct->mrc_sku.'-'.$i,'price'=>(float)$largeProduct->mrc_price+$i,'stock'=>5,'stock_policy'=>'deny','status'=>'active'];}$commerce->variantService()->saveDefinition($largeProduct,[['id'=>'edition','label'=>'Edition','values'=>$variantValues]],$variants);$state['large_product_url']=(string)$largeProduct->url;$write($state);
$content=new Page();$content->template='mrc-page';$content->parent=$wire->pages->get('/');$content->name="e2e-public-visual-{$run}-content";$content->title='Contenu long 日本語 العربية '.$long;if($content->hasField('body'))$content->body='<p>Contenido traducido 日本語 وصف عربي '.$long.'</p>';$wire->pages->save($content);$state['page_ids'][]=(int)$content->id;
$role=$wire->roles->get('mercato-customer');if(!$role->id)throw new WireException('The mercato-customer role is required.');$user=new User();$user->name='e2e-public-visual-'.substr(hash('sha256',$run),0,12);$user->email="e2e-{$run}-customer@example.test";$user->pass=$password;$user->addRole($role);$user->mrc_customer_verified=1;$user->mrc_first_name='Présentation'.str_repeat('LongProfile',10);$user->mrc_last_name='日本語 العربية';$wire->users->save($user);$state['users'][]=['id'=>(int)$user->id,'name'=>(string)$user->name];$state['customer_email']=(string)$user->email;
$emptyUser=new User();$emptyUser->name='e2e-public-visual-empty-'.substr(hash('sha256',$run),0,10);$emptyUser->email="e2e-{$run}-empty@example.test";$emptyUser->pass=$password;$emptyUser->addRole($role);$emptyUser->mrc_customer_verified=1;$emptyUser->mrc_first_name='Empty';$emptyUser->mrc_last_name='Quotes';$wire->users->save($emptyUser);$state['users'][]=['id'=>(int)$emptyUser->id,'name'=>(string)$emptyUser->name];$state['empty_quote_email']=(string)$emptyUser->email;
$items=[['id'=>'visual-service','product_id'=>0,'title'=>'Service visuel 日本語 العربية '.str_repeat('LongOrderItem',8),'sku'=>'PV-SVC','price'=>25,'quantity'=>1,'tax_rate'=>0,'product_type'=>'service','stock_policy'=>'allow','uid'=>'visual-service']];for($i=1;$i<=14;$i++){$o=$commerce->orderRepository()->savePendingOrder(['first_name'=>'Présentation','last_name'=>'Customer','email'=>(string)$user->email,'payment_method'=>'demo','payment_status'=>'paid','payment_complete'=>1,'mrc_items'=>json_encode($items,JSON_UNESCAPED_UNICODE),'mrc_total_amount'=>25,'mrc_currency'=>'USD','mrc_fulfilment_status'=>'delivered','mrc_customer_user_id'=>(int)$user->id,'mrc_notes'=>$run]);$state['order_ids'][]=(int)$o->id;}
$largeItems=[];for($i=1;$i<=30;$i++)$largeItems[]=['id'=>'visual-large-'.$i,'product_id'=>0,'title'=>sprintf('Long signed item %02d · Español 日本語 العربية %s',$i,str_repeat('UnbrokenItem',4)),'sku'=>'PV-LARGE-'.$i,'price'=>1+$i,'quantity'=>1,'tax_rate'=>0,'product_type'=>'service','stock_policy'=>'allow','uid'=>'visual-large-'.$i];$state['large_items']=json_encode($largeItems,JSON_UNESCAPED_UNICODE);
for($i=1;$i<=12;$i++){$quote=new Page();$quote->template=(string)$commerce->quote_template;$quote->parent=$quotes;$quote->title='Q-VISUAL-'.$i.'-日本語-'.str_repeat('LONG',8);$quote->addStatus(Page::statusHidden);$quote->mrc_quote_number=(string)$quote->title;$quote->mrc_quote_status='quoted';$quote->mrc_quote_customer_user_id=(int)$user->id;$quote->mrc_email=(string)$user->email;$quote->mrc_first_name='Présentation';$quote->mrc_last_name='Customer';$quote->mrc_items=json_encode($items,JSON_UNESCAPED_UNICODE);$quote->mrc_total_amount=25+$i;$quote->mrc_quote_amount=24+$i;$quote->mrc_currency='USD';$quote->mrc_quote_expires=date('Y-m-d H:i:s',time()+86400);$quote->mrc_quote_token_seed=bin2hex(random_bytes(16));$quote->mrc_quote_details=json_encode(['history'=>[]]);$wire->pages->save($quote);$state['quote_ids'][]=(int)$quote->id;}
$state+=['home_url'=>'/','empty_home_url'=>'/?min_price=99999999','catalog_url'=>(string)$products->url,'empty_catalog_url'=>rtrim((string)$products->url,'/').'/?min_price=99999999','large_catalog_url'=>rtrim((string)$products->url,'/').'/?sort=newest','collections_url'=>(string)$collections->url,'empty_collections_url'=>rtrim((string)$collections->url,'/').'/?min_price=99999999','collection_url'=>(string)$normalCollection->url,'empty_collection_url'=>(string)$emptyCollection->url,'content_url'=>(string)$content->url,'checkout_url'=>'/checkout/','success_url'=>'/checkout/success/','account_url'=>'/account/','quotes_url'=>'/my-quotes/','lookup_url'=>'/api/mercato/order-lookup'];$write($state);echo json_encode(['ready'=>true,'run_id'=>$run,'screens'=>15,'products'=>24,'collections'=>18,'orders'=>14,'quotes'=>12],JSON_UNESCAPED_SLASHES)."\n";
