const { test, expect } = require('@playwright/test');
const { execFileSync } = require('node:child_process');
const fs = require('node:fs');
const path = require('node:path');
const { fixture, assertAccessible, assertResponsive } = require('./helpers');

const origin = new URL(process.env.MERCATO_E2E_BASE_URL || 'https://mercato.test').origin;
function prepare(action) { execFileSync('php', [path.join(__dirname, 'public-visual-fixtures.php'), action], { cwd: path.join(__dirname, '../..'), env: process.env, encoding: 'utf8', stdio: ['ignore','pipe','pipe'] }); return fixture(); }
function failuresFor(page) { const failures=[]; page.on('console',m=>{if(m.type()!=='error')return;if(/Failed to load resource: the server responded with a status of (400|404)/i.test(m.text()))return;failures.push(`console: ${m.text()}`);});page.on('requestfailed',r=>{if(['document','xhr','fetch'].includes(r.resourceType()))failures.push(`request: ${r.method()} ${r.url()} — ${r.failure()?.errorText||'failed'}`);});page.on('response',r=>{if(new URL(r.url()).origin!==origin)return;const type=r.request().resourceType();if(r.status()>=500||([400,404].includes(r.status())&&!['document','xhr','fetch'].includes(type)))failures.push(`response: ${r.status()} ${r.url()}`);});return failures; }
async function evidence(page,testInfo,keyOrKeys){const keys=Array.isArray(keyOrKeys)?keyOrKeys:[keyOrKeys];const label=keys.join(', ');await expect(page.locator('body')).toBeVisible();await assertResponsive(page,label);await assertAccessible(page,label);const desktop=await page.screenshot({fullPage:true,animations:'disabled'});for(const key of keys)fs.writeFileSync(testInfo.outputPath(`${key}.png`),desktop);await page.setViewportSize({width:390,height:844});await assertResponsive(page,`${label} responsive`);await assertAccessible(page,`${label} responsive`);const mobile=await page.screenshot({fullPage:true,animations:'disabled'});for(const key of keys)fs.writeFileSync(testInfo.outputPath(`${key}-responsive.png`),mobile);await page.setViewportSize({width:1440,height:1000});}
function accountForm(page,action){return page.locator('form').filter({has:page.locator(`input[name="mrc_account_action"][value="${action}"]`)});}
async function login(page,state,email=state.customer_email){await page.goto(state.account_url,{waitUntil:'domcontentloaded'});const form=accountForm(page,'login');await form.locator('input[name="email"]').fill(email);await form.locator('input[name="password"]').fill(state.password);await Promise.all([page.waitForNavigation({waitUntil:'domcontentloaded'}),form.getByRole('button',{name:'Sign in'}).click()]);}
async function logout(page){const form=accountForm(page,'logout');await Promise.all([page.waitForNavigation({waitUntil:'domcontentloaded'}),form.getByRole('button',{name:'Sign out'}).click()]);}
async function staleCatalogError(page,testInfo,url,key){await page.goto(url,{waitUntil:'domcontentloaded'});const form=page.locator('form.mrc-card-purchase-form').first();await form.locator('input[name="product_id"]').evaluate(input=>{input.value='999999999';});await Promise.all([page.waitForNavigation({waitUntil:'domcontentloaded'}),form.getByRole('button',{name:/Add to cart/i}).click()]);await expect(page.getByText(/Error: Product is no longer available/i)).toBeVisible();await evidence(page,testInfo,key);}
async function addCatalogLines(page,state,target){await page.goto(state.large_catalog_url,{waitUntil:'domcontentloaded'});const forms=page.locator('form.mrc-card-purchase-form');const count=await forms.count();let added=0;for(let i=0;i<count&&added<target;i++){const form=forms.nth(i);const productId=await form.locator('input[name="product_id"]').inputValue();if(Number(productId)===Number(state.checkout_product_id))continue;const result=await form.evaluate(async element=>{const response=await fetch(element.action,{method:'POST',body:new FormData(element),credentials:'same-origin'});return{ok:response.ok,status:response.status};});expect(result.ok,`catalog add ${productId} returned ${result.status}`).toBeTruthy();added++;}expect(added,'large checkout fixture needs enough independently purchasable catalog products').toBeGreaterThanOrEqual(target);}

test('15 storefront and public screens expose deterministic visual states',async({browser},testInfo)=>{
  test.setTimeout(240_000);let state=fixture();const context=await browser.newContext({viewport:{width:1440,height:1000},ignoreHTTPSErrors:true});const page=await context.newPage();const failures=failuresFor(page);
  try{
    let response=await page.goto(state.home_url,{waitUntil:'domcontentloaded'});expect(response?.ok()).toBeTruthy();await evidence(page,testInfo,['storefront-home-normal','storefront-home-long','storefront-home-translated','storefront-home-large']);
    response=await page.goto(state.large_catalog_url,{waitUntil:'domcontentloaded'});expect(response?.ok()).toBeTruthy();await evidence(page,testInfo,['storefront-catalog-large','storefront-catalog-long','storefront-catalog-translated']);
    for(const [keys,url] of [[['storefront-product-long-translated'],state.long_product_url],[['storefront-collections-normal','storefront-collections-long','storefront-collections-large'],state.collections_url],[['storefront-collection-large','storefront-collection-long'],state.collection_url],[['storefront-content-long-translated'],state.content_url]]){response=await page.goto(url,{waitUntil:'domcontentloaded'});expect(response?.ok()).toBeTruthy();await evidence(page,testInfo,keys);}
    response=await page.goto(state.large_product_url,{waitUntil:'domcontentloaded'});expect(response?.ok()).toBeTruthy();await expect(page.locator('select[name="variant_options[edition]"] option')).toHaveCount(30);await evidence(page,testInfo,'storefront-product-large');
    await test.step('home and catalog expose empty and real filter-loading states',async()=>{await page.goto(state.empty_home_url,{waitUntil:'domcontentloaded'});await expect(page.getByRole('status').filter({hasText:'No products are available yet.'})).toBeVisible();await evidence(page,testInfo,'storefront-home-empty');const homeForm=page.locator('[data-mrc-product-filters]');await homeForm.evaluate(el=>el.addEventListener('submit',event=>event.preventDefault(),{once:true,capture:true}));await homeForm.getByRole('button',{name:'Apply filters'}).click();await expect(page.locator('#mrc-catalog-results')).toHaveAttribute('aria-busy','true');await assertResponsive(page,'storefront-home-loading');await assertAccessible(page,'storefront-home-loading');await page.screenshot({path:testInfo.outputPath('storefront-home-loading.png'),fullPage:true});await page.goto(state.empty_catalog_url,{waitUntil:'domcontentloaded'});await expect(page.getByRole('status').filter({hasText:'No products are available yet.'})).toBeVisible();await evidence(page,testInfo,'storefront-catalog-empty');await page.goto(state.large_catalog_url,{waitUntil:'domcontentloaded'});const form=page.locator('[data-mrc-product-filters]');await form.evaluate(el=>el.addEventListener('submit',event=>event.preventDefault(),{once:true,capture:true}));await form.getByRole('button',{name:'Apply filters'}).click();await expect(page.locator('#mrc-catalog-results')).toHaveAttribute('aria-busy','true');await assertResponsive(page,'storefront-catalog-loading');await assertAccessible(page,'storefront-catalog-loading');await page.screenshot({path:testInfo.outputPath('storefront-catalog-loading.png'),fullPage:true});});
    await staleCatalogError(page,testInfo,state.home_url,'storefront-home-error');await staleCatalogError(page,testInfo,state.catalog_url,'storefront-catalog-error');
    await page.goto(state.empty_collections_url,{waitUntil:'domcontentloaded'});await expect(page.getByText('No products match these filters yet.')).toBeVisible();await evidence(page,testInfo,'storefront-collections-empty');
    await page.goto(state.empty_collection_url,{waitUntil:'domcontentloaded'});await evidence(page,testInfo,'storefront-collection-empty');
    await page.goto(state.collection_url,{waitUntil:'domcontentloaded'});const staleForm=page.locator('form.mrc-card-purchase-form').first();await staleForm.locator('input[name="product_id"]').evaluate(input=>{input.value='999999999';});await Promise.all([page.waitForNavigation({waitUntil:'domcontentloaded'}),staleForm.getByRole('button',{name:/Add to cart/i}).click()]);await expect(page.getByText(/Error: Product is no longer available/i)).toBeVisible();await evidence(page,testInfo,'storefront-collection-error');
    await page.goto(state.checkout_url,{waitUntil:'domcontentloaded'});await evidence(page,testInfo,'storefront-checkout-empty');
    await page.goto(state.long_product_url,{waitUntil:'domcontentloaded'});let add=page.locator('form').filter({has:page.locator('input[name="mrc_action"][value="add_to_cart"]')}).first();const invalidQuantity=add.locator('input[name="quantity"]');await invalidQuantity.evaluate(input=>input.removeAttribute('max'));await invalidQuantity.fill('999999');await Promise.all([page.waitForNavigation({waitUntil:'domcontentloaded'}),add.getByRole('button',{name:/Add to Cart/i}).click()]);await expect(page.getByText(/^Error:/)).toBeVisible();await evidence(page,testInfo,'storefront-product-error');await page.goto(state.long_product_url,{waitUntil:'domcontentloaded'});add=page.locator('form').filter({has:page.locator('input[name="mrc_action"][value="add_to_cart"]')}).first();await Promise.all([page.waitForNavigation({waitUntil:'domcontentloaded'}),add.getByRole('button',{name:/Add to Cart/i}).click()]);await addCatalogLines(page,state,8);await page.goto(state.checkout_url,{waitUntil:'domcontentloaded'});await expect(page.locator('input[name^="cart_quantity["]')).toHaveCount(9);await evidence(page,testInfo,['storefront-checkout-normal','storefront-checkout-long','storefront-checkout-translated','storefront-checkout-large']);await page.getByRole('button',{name:/Continue to payment/i}).click();await expect(page.locator(':invalid').first()).toBeVisible();await evidence(page,testInfo,'storefront-checkout-error');
    for(const[name,value]of[['first_name','Visual'],['last_name','State'],['email',state.checkout_email],['address','10 Visual Street'],['city','New York'],['zip','10001']]){const f=page.locator(`input[name="${name}"]`);if(await f.count()&&await f.isVisible())await f.fill(value);}const country=page.locator('select[name="country"]');if(await country.count()&&await country.isVisible())await country.selectOption('US');await page.locator('select[name="payment_method"]').selectOption('demo');const policy=page.locator('input[name="policy_accepted"]');if(await policy.count())await policy.check();await Promise.all([page.waitForURL(/checkout\/success/),page.getByRole('button',{name:/Continue to payment/i}).click()]);await evidence(page,testInfo,['storefront-success-normal','storefront-success-long','storefront-success-translated','storefront-success-large']);state=prepare('capture');await page.goto(state.success_url,{waitUntil:'domcontentloaded'});await expect(page.getByText('No completed payment is available for this session.').first()).toBeVisible();await evidence(page,testInfo,'storefront-success-error');
    await login(page,state);await page.goto(state.account_url,{waitUntil:'domcontentloaded'});await expect(page.locator('.mrc-table tbody tr')).toHaveCount(5);await evidence(page,testInfo,['storefront-account-large-translated','storefront-account-long']);await page.goto(state.quotes_url,{waitUntil:'domcontentloaded'});await expect(page.getByText(/Q-VISUAL/).first()).toBeVisible();await expect(page.locator('.mrc-table tbody tr')).toHaveCount(12);await evidence(page,testInfo,['storefront-my-quotes-normal','storefront-my-quotes-long','storefront-my-quotes-translated','storefront-my-quotes-large']);await page.goto(state.account_url,{waitUntil:'domcontentloaded'});await logout(page);await login(page,state,state.empty_quote_email);await expect(page.getByText('No orders are attached to this account.')).toBeVisible();await evidence(page,testInfo,'storefront-account-empty');await page.goto(state.quotes_url,{waitUntil:'domcontentloaded'});await expect(page.getByText('No quote requests are attached to this account.')).toBeVisible();await evidence(page,testInfo,'storefront-my-quotes-empty');
    response=await page.goto(state.lookup_url,{waitUntil:'domcontentloaded'});expect(response?.status()).toBe(200);await evidence(page,testInfo,'public-order-lookup-empty');response=await page.goto(`${state.lookup_url}?order=missing-${state.run_id}&email=missing%40example.test`,{waitUntil:'domcontentloaded'});expect(response?.status()).toBe(404);await evidence(page,testInfo,'public-order-lookup-error');response=await page.goto(`${state.lookup_url}?order=${'LONG'.repeat(45)}&email=missing%40example.test`,{waitUntil:'domcontentloaded'});expect(response?.status()).toBe(404);await expect(page.locator('input[name="order"]')).toHaveValue('LONG'.repeat(45));await evidence(page,testInfo,'public-order-lookup-long');
    for(const[key,url]of[['public-order-status-normal',state.status_url],['public-receipt-normal',state.receipt_url],['public-access-recovery-normal',state.access_url]]){response=await page.goto(url,{waitUntil:'domcontentloaded'});expect(response?.status()).toBe(200);await evidence(page,testInfo,key);}
    for(const[key,url]of[['public-order-status-large-long',state.large_status_url],['public-receipt-large-long',state.large_receipt_url]]){response=await page.goto(url,{waitUntil:'domcontentloaded'});expect(response?.status()).toBe(200);await expect(page.locator('tbody tr')).toHaveCount(30);await evidence(page,testInfo,key);}
    for(const[key,url]of[['public-order-status-error','/order/status/malformed/'],['public-receipt-error','/order/receipt/malformed/'],['public-access-recovery-error','/access/recovery/malformed/']]){response=await page.goto(url,{waitUntil:'domcontentloaded'});expect(response?.status()).toBe(404);await evidence(page,testInfo,key);}
    response=await page.goto(state.unsubscribe_url,{waitUntil:'domcontentloaded'});expect(response?.status()).toBe(200);await evidence(page,testInfo,'public-recovery-unsubscribe-normal');response=await page.goto('/api/mercato/recovery-unsubscribe?email=bad%40example.test&token=malformed',{waitUntil:'domcontentloaded'});expect(response?.status()).toBe(400);await evidence(page,testInfo,'public-recovery-unsubscribe-error');
    expect(failures,'public visual console/network/server failures').toEqual([]);
  }finally{await context.close();}
});
