<?php
namespace ProcessWire;
$site = getenv('MERCATO_TEST_SITE');
if (!$site) { echo "Mercato privacy integration test skipped (set MERCATO_TEST_SITE).\n"; exit(0); }
$_SERVER['HTTP_HOST'] = 'mercato.test'; $_SERVER['SERVER_NAME'] = 'mercato.test'; $_SERVER['REQUEST_URI'] = '/'; $_SERVER['SCRIPT_NAME'] = '/index.php'; $_SERVER['SCRIPT_FILENAME'] = $site . '/index.php';
require $site . '/wire/core/ProcessWire.php'; $config = ProcessWire::buildConfig($site); $config->dbHost = '127.0.0.1'; $wire = new ProcessWire($config); $wire->users->setCurrentUser($wire->users->get('template=user, roles.name=superuser')); /** @var Mercato $commerce */ $commerce = $wire->modules->get('Mercato');
$originalModuleConfig = (array) $wire->modules->getConfig('Mercato'); $originalSuppressed = $originalModuleConfig['recovery_suppressed_emails'] ?? '';
$email = 'privacy-' . bin2hex(random_bytes(6)) . '@example.test'; $items = [['id' => 'privacy-fixture', 'product_id' => 999991, 'title' => 'Privacy fixture', 'sku' => 'PRIVACY-1', 'price' => 42, 'quantity' => 1, 'tax_rate' => 0, 'product_type' => 'service', 'uid' => 'privacy-fixture']];
$order = $commerce->orderRepository()->savePendingOrder(['first_name' => 'Private', 'last_name' => 'Customer', 'email' => $email, 'phone' => '+1 555 0100', 'address' => 'Private Street', 'city' => 'Private City', 'zip' => '10001', 'country' => 'US', 'payment_method' => 'stripe-card', 'payment_status' => MercatoPaymentStatus::PAID, 'payment_complete' => 1, 'mrc_currency' => 'USD', 'mrc_items' => json_encode($items), 'mrc_subtotal_amount' => 42, 'mrc_total_amount' => 42, 'mrc_fulfilment_status' => MercatoFulfilmentStatus::DELIVERED, 'stripe_payment_intent_id' => 'pi_privacy_fixture']);
$order = $wire->pages->getById((int) $order->id, ['cache' => false])->first();
$push=$commerce->pushNotificationService()->register(['token'=>hash('sha256','privacy-push-'.$email),'installation_id'=>'privacy-push-'.bin2hex(random_bytes(8)),'environment'=>'sandbox','bundle_id'=>trim((string)$commerce->apns_bundle_id)?:'org.smnv.mercato','locale'=>'en','topics'=>['order_updates']],'order',(int)$order->id);
$order->of(false); $order->mrc_status_token_seed = 'before-privacy-token'; $wire->pages->save($order); $beforeToken = $commerce->getOrderStatusToken($order); $beforeItems = (string) $order->mrc_items; $beforeTotal = (float) $order->mrc_total_amount; $beforeProvider = (string) $order->mrc_stripe_payment_intent_id;
$originalLinkDays = max(1, (int) $commerce->signed_link_retention_days); if (!$commerce->areOrderSignedLinksExpired($order, (int) $order->created + ($originalLinkDays * 86400))) throw new \RuntimeException('Signed-link age boundary failed.');
$export = $commerce->privacyService()->exportCustomer($email); if (($export['format'] ?? '') !== 'mercato-privacy-export-v1' || count($export['categories']['orders'] ?? []) !== 1 || ($export['categories']['orders'][0]['items'][0]['sku'] ?? '') !== 'PRIVACY-1') throw new \RuntimeException('Portable privacy export categories failed.');
$commerce->privacyService()->setLegalHold($order, true, 'Integration legal hold'); $blocked = false; try { $commerce->privacyService()->deleteCustomerData($email, 'Fixture deletion request', 'test-v1'); } catch (WireException $e) { $blocked = str_contains($e->getMessage(), 'blocked'); } if (!$blocked) throw new \RuntimeException('Legal hold did not block anonymization.');
$commerce->privacyService()->setLegalHold($order, false, 'Integration hold released'); $result = $commerce->privacyService()->deleteCustomerData($email, 'Fixture deletion request approved', 'test-v1'); $fresh = $wire->pages->getById((int) $order->id, ['cache' => false])->first();
if (($result['orders_anonymized'] ?? 0) !== 1 || ($result['push_registrations_revoked'] ?? 0) !== 1 || !str_ends_with((string) $fresh->mrc_email, '@privacy.invalid') || (string) $fresh->mrc_phone !== '' || trim((string) $fresh->mrc_privacy_anonymized_date) === '') throw new \RuntimeException('Customer PII or push registration was not anonymized.');
if ((string) $fresh->mrc_items !== $beforeItems || (float) $fresh->mrc_total_amount !== $beforeTotal || (string) $fresh->mrc_stripe_payment_intent_id !== $beforeProvider) throw new \RuntimeException('Financial integrity/provider linkage was damaged.');
if ($commerce->getOrderStatusToken($fresh) === $beforeToken) throw new \RuntimeException('Signed order links were not invalidated.');
$retry = $commerce->privacyService()->deleteCustomerData($email, 'Retry fixture request', 'test-v1'); if (($retry['orders_anonymized'] ?? -1) !== 0) throw new \RuntimeException('Privacy retry was not idempotent.');
$dryRun = $commerce->privacyService()->runRetention(true, 10, time()); if (empty($dryRun['dry_run']) || !isset($dryRun['orders'], $dryRun['logs'])) throw new \RuntimeException('Retention dry-run report failed.');
$originalModuleConfig['recovery_suppressed_emails'] = $originalSuppressed; $wire->modules->saveConfig('Mercato', $originalModuleConfig); $commerce->set('recovery_suppressed_emails', $originalSuppressed);
$pushCleanup=$wire->database->prepare('DELETE FROM mercato_push_devices WHERE registration_id=:id');$pushCleanup->execute([':id'=>$push['id']]);
echo "Mercato privacy integration tests passed; fixture order {$fresh->id}.\n";
