<?php
namespace ProcessWire;
$site=getenv('MERCATO_TEST_SITE');if(!$site){echo "Mercato headless API integration test skipped (set MERCATO_TEST_SITE).\n";exit(0);}require $site.'/wire/core/ProcessWire.php';$config=ProcessWire::buildConfig($site);$config->dbHost='127.0.0.1';$wire=new ProcessWire($config);$wire->users->setCurrentUser($wire->users->get('template=user, roles.name=superuser'));$wire->set('page',$wire->pages->get('/'));/** @var Mercato $commerce */$commerce=$wire->modules->get('Mercato');$service=$commerce->headlessApiService();$product=null;foreach($wire->pages->find('template=mrc-product,mrc_product_status=active,mrc_product_type=physical,include=all')as$candidate){if($commerce->variantService()->getDefinition($candidate)['variants']===[]){$product=$candidate;break;}}if(!$product instanceof Page||!$product->id)throw new \RuntimeException('Non-variant physical fixture product missing.');$originalStock=(int)$product->mrc_stock;$originalPrice=(float)$product->mrc_price;$originalStatus=(int)$product->status;$originalCart=$commerce->cart()->toArray();$originalMethods=$commerce->enabled_payment_methods;$originalAccountMode=$commerce->customer_accounts_mode;$commerce->set('enabled_payment_methods',['demo']);$order=null;$nonce=bin2hex(random_bytes(6));
$customer=['first_name'=>'Native','last_name'=>'Fixture','email'=>'api-'.$nonce.'@example.test','address'=>'API Street','city'=>'Test City','zip'=>'10001','country'=>'US'];$options=['fulfilment_method'=>'carrier_delivery','payment_method'=>'demo','policy_accepted'=>true];$body=['items'=>[['product_id'=>(int)$product->id,'quantity'=>1]],'customer'=>$customer,'options'=>$options];$cartResource=null;
try{
 $cartResource=$service->createCart(['items'=>$body['items']],'cart-create-'.$nonce);$cartReplay=$service->createCart(['items'=>$body['items']],'cart-create-'.$nonce);if($cartResource['id']!==$cartReplay['id']||empty($cartResource['token'])||$cartResource['version']!==1)throw new \RuntimeException('Server cart creation was not idempotent.');$cartRead=$service->cart($cartResource['id'],$cartResource['token']);if(count($cartRead['lines'])!==1)throw new \RuntimeException('Server cart snapshot could not be restored.');$cartUpdated=$service->updateCart($cartResource['id'],$cartResource['token'],['expected_version'=>1,'items'=>[]],'cart-update-'.$nonce);if($cartUpdated['version']!==2||$cartUpdated['lines']!==[])throw new \RuntimeException('Server cart optimistic update failed.');$conflict=false;try{$service->updateCart($cartResource['id'],$cartResource['token'],['expected_version'=>1,'items'=>[]],'cart-stale-'.$nonce);}catch(MercatoHeadlessApiException $e){$conflict=$e->apiCode==='version_conflict'&&$e->httpStatus===409;}if(!$conflict)throw new \RuntimeException('Stale server cart update was accepted.');
 $store=$service->store();if(empty($store['support']['url'])||!str_starts_with((string)$store['support']['url'],'http'))throw new \RuntimeException('Store support contract is incomplete.');$catalog=$service->products(['limit'=>5]);$facets=$catalog['meta']['facets']??null;if(!is_array($facets)||!isset($facets['types'],$facets['collections'],$facets['availability'],$facets['price'],$facets['options']))throw new \RuntimeException('Catalog facet metadata is incomplete.');$typed=$service->products(['type'=>'physical','availability'=>'available','limit'=>50]);foreach($typed['data']as$item)if(($item['type']??'')!=='physical'||empty($item['purchasability']['purchasable']))throw new \RuntimeException('Catalog filters were not applied before pagination.');
 $quote=$service->quote($body);if(($quote['item_count']??0)!==1||(float)$quote['total']<=0)throw new \RuntimeException('Authoritative API quote failed.');$wrongCurrency=$body;$wrongCurrency['options']['currency']='USD';$currencyQuote=$service->quote($wrongCurrency);if(($currencyQuote['currency']??'')!==strtoupper((string)$commerce->currency))throw new \RuntimeException('API allowed a client to relabel authoritative currency.');
 $product->addStatus(Page::statusHidden);$wire->pages->save($product);$hidden=false;try{$service->product((int)$product->id);}catch(MercatoHeadlessApiException $e){$hidden=$e->httpStatus===404;}if(!$hidden)throw new \RuntimeException('Hidden product remained publicly readable.');$product->status=$originalStatus;$wire->pages->save($product);
 $commerce->set('customer_accounts_mode','required_verified');$accountBlocked=false;try{$service->createCheckout($body,'account-'.$nonce);}catch(MercatoHeadlessApiException $e){$accountBlocked=$e->apiCode==='account_required'&&$e->httpStatus===403;}if(!$accountBlocked)throw new \RuntimeException('Required verified account mode was bypassed.');$commerce->set('customer_accounts_mode',$originalAccountMode);
 $product->of(false);$product->mrc_price=$originalPrice+1;$wire->pages->save($product);$changed=$service->quote($body);if((float)$changed['subtotal']<=(float)$quote['subtotal'])throw new \RuntimeException('API trusted stale client pricing.');$product->mrc_price=$originalPrice;$wire->pages->save($product);
 $created=$service->createCheckout($body,'create-'.$nonce);$replayed=$service->createCheckout($body,'create-'.$nonce);if($created['id']!==$replayed['id']||empty($created['token']))throw new \RuntimeException('Checkout creation was not idempotent.');$order=$wire->pages->get('template=mrc-order,include=all,mrc_api_checkout_id='.$wire->sanitizer->selectorValue($created['id']));if(!$order->id)throw new \RuntimeException('Opaque checkout was not persisted.');
 $notFound=false;try{$service->checkout($created['id'],'wrong-token');}catch(MercatoHeadlessApiException $e){$notFound=$e->httpStatus===404;}if(!$notFound)throw new \RuntimeException('Invalid token disclosed checkout state.');
 $first=$service->complete($created['id'],$created['token'],[],'complete-'.$nonce);$second=$service->complete($created['id'],$created['token'],[],'complete-'.$nonce);if(empty($first['payment_complete'])||empty($second['replayed']))throw new \RuntimeException('Completion replay was not idempotent.');$public=$service->order($created['order_id'],$created['token']);if(($public['payment_status']??'')!==MercatoPaymentStatus::PAID||isset($public['email'])||isset($public['address'])||!isset($public['return_eligibility'])||empty($public['cancellation_eligibility']['can_request']))throw new \RuntimeException('Order API status, privacy, return, or cancellation eligibility contract failed.');$cancelBody=['reason'=>'Ordered by mistake'];$cancel=$service->createCancellation($created['order_id'],$created['token'],$cancelBody,'cancel-'.$nonce);$cancelReplay=$service->createCancellation($created['order_id'],$created['token'],$cancelBody,'cancel-'.$nonce);if(empty($cancel['request_id'])||$cancel['request_id']!==$cancelReplay['request_id']||isset($cancel['order_id'])||isset($cancel['email']))throw new \RuntimeException('Cancellation request API idempotency or privacy contract failed.');$afterCancel=$service->order($created['order_id'],$created['token']);if(($afterCancel['cancellation_request']['request_id']??'')!==$cancel['request_id']||!empty($afterCancel['cancellation_eligibility']['can_request']))throw new \RuntimeException('Cancellation request was not reflected in the order resource.');
 $order->of(false);$order->mrc_fulfilment_status=MercatoFulfilmentStatus::SHIPPED;$wire->pages->save($order);$returnBody=['reason'=>'Integration fixture return','items'=>[['product_id'=>(int)$product->id,'quantity'=>1]]];$return=$service->createReturn($created['order_id'],$created['token'],$returnBody,'return-'.$nonce);$returnReplay=$service->createReturn($created['order_id'],$created['token'],$returnBody,'return-'.$nonce);if(empty($return['request_id'])||$return['request_id']!==$returnReplay['request_id']||isset($return['email'])||isset($return['order_id']))throw new \RuntimeException('Return request API idempotency or privacy contract failed.');$invalidReturn=false;try{$service->createReturn($created['order_id'],$created['token'],['reason'=>'Invalid quantity','items'=>[['product_id'=>(int)$product->id,'quantity'=>999]]],'invalid-return-'.$nonce);}catch(MercatoHeadlessApiException $e){$invalidReturn=$e->apiCode==='validation_failed'&&$e->httpStatus===422;}if(!$invalidReturn)throw new \RuntimeException('Return API accepted a quantity not present in the order snapshot.');
 $details=json_decode((string)$order->mrc_api_details,true);$details['expires_at']=time()-1;$order->of(false);$order->mrc_api_details=json_encode($details);$wire->pages->save($order);$expired=false;try{$service->checkout($created['id'],$created['token']);}catch(MercatoHeadlessApiException $e){$expired=$e->httpStatus===410;}if(!$expired)throw new \RuntimeException('Expired API token remained usable.');
 $product->of(false);$product->mrc_stock=0;$wire->pages->save($product);$blocked=false;try{$service->createCheckout($body,'stock-'.$nonce);}catch(WireException $e){$blocked=str_contains(strtolower($e->getMessage()),'stock')||str_contains(strtolower($e->getMessage()),'available');}if(!$blocked)throw new \RuntimeException('Insufficient stock checkout was accepted.');
}finally{$commerce->set('enabled_payment_methods',$originalMethods);$commerce->set('customer_accounts_mode',$originalAccountMode);$commerce->cart($originalCart);$product->of(false);$product->status=$originalStatus;$product->mrc_price=$originalPrice;$product->mrc_stock=$originalStock;$wire->pages->save($product);if(is_array($cartResource)&&!empty($cartResource['id'])){$secret=(string)($wire->config->userAuthSalt?:__FILE__);$wire->cache->delete('Mercato.api.cart.'.hash_hmac('sha256',(string)$cartResource['id'],$secret));}if($order instanceof Page&&$order->id){$order->of(false);$wire->pages->delete($order,true);}}
echo "Mercato headless API integration tests passed.\n";
