<?php
namespace ProcessWire;
$site = getenv('MERCATO_TEST_SITE'); if (!$site) { echo "Mercato customer account integration test skipped (set MERCATO_TEST_SITE).\n"; exit(0); } if (session_status() !== PHP_SESSION_ACTIVE) session_start();
$_SERVER['HTTP_HOST']='mercato.test'; $_SERVER['SERVER_NAME']='mercato.test'; $_SERVER['REQUEST_URI']='/'; $_SERVER['SCRIPT_NAME']='/index.php'; $_SERVER['SCRIPT_FILENAME']=$site.'/index.php';
require $site.'/wire/core/ProcessWire.php'; $config=ProcessWire::buildConfig($site); $config->dbHost='127.0.0.1'; $wire=new ProcessWire($config); $super=$wire->users->get('template=user, roles.name=superuser'); $wire->users->setCurrentUser($super); /** @var Mercato $commerce */ $commerce=$wire->modules->get('Mercato');
$originalMode=$commerce->customer_accounts_mode; $originalSender=$commerce->notification_sender_email; $commerce->set('customer_accounts_mode','optional'); $commerce->set('notification_sender_email',''); $service=$commerce->customerAccountService(); $email='account-'.bin2hex(random_bytes(5)).'@example.test'; $password='Test-account-42!';
$registered=$service->register($email,$password,['first_name'=>'Account','last_name'=>'Fixture']); $duplicate=$service->register($email,$password); if (($registered['message']??'')!==($duplicate['message']??'')) throw new \RuntimeException('Registration leaks account existence.');
$account=$wire->users->get('email='.$wire->sanitizer->selectorValue($email)); if (!$account->id || !$account->hasRole('mercato-customer')) throw new \RuntimeException('Customer account was not created.'); $verify=json_decode((string)$account->mrc_customer_verification,true); if (!is_array($verify)) throw new \RuntimeException('Verification state missing.');
$expired=$verify; $expired['expires']=time()-1; $account->of(false); $account->mrc_customer_verification=json_encode($expired); $wire->users->save($account); if ($service->verify((int)$account->id,'not-a-token')) throw new \RuntimeException('Expired/invalid verification accepted.');
$ref=new \ReflectionClass($service); $issue=$ref->getMethod('issueToken'); $token=$issue->invoke($service,$account,'verify'); if (!$service->verify((int)$account->id,$token)) throw new \RuntimeException('Valid verification failed.');
$api=$commerce->headlessApiService(); $native=$api->loginAccount(['email'=>$email,'password'=>$password]); $nativeToken=(string)($native['token']??''); if($nativeToken===''||($native['profile']['email']??'')!==$email) throw new \RuntimeException('Native account login/profile failed.'); $nativeProfile=$api->accountProfile($nativeToken); $nativeUpdated=$api->updateAccountProfile($nativeToken,['revision'=>(int)$nativeProfile['revision'],'profile'=>['phone'=>'+1 555 0100','preferences'=>['commerce_email'=>true]]],'profile-native-'.bin2hex(random_bytes(4))); if(($nativeUpdated['phone']??'')!=='+1 555 0100'||empty($nativeUpdated['preferences']['commerce_email'])) throw new \RuntimeException('Native account profile or notification preference update failed.'); if(session_status()!==PHP_SESSION_ACTIVE)session_start();
$pushInput=['token'=>hash('sha256','account-push-'.$email),'installation_id'=>'account-push-'.bin2hex(random_bytes(8)),'environment'=>'sandbox','bundle_id'=>trim((string)$commerce->apns_bundle_id)?:'org.smnv.mercato','locale'=>'en','topics'=>['order_updates']];$push=$api->registerPushDevice($nativeToken,$pushInput,'push-native-'.bin2hex(random_bytes(4)));if(!str_starts_with((string)($push['id']??''),'dev_')||isset($push['token']))throw new \RuntimeException('Native push registration failed or exposed its token.');$pushRevoked=$api->revokePushDevice((string)$push['id'],$nativeToken,[],'push-revoke-'.bin2hex(random_bytes(4)));if(($pushRevoked['status']??'')!=='revoked')throw new \RuntimeException('Native push revocation failed.');$pushCleanup=$wire->database->prepare('DELETE FROM mercato_push_devices WHERE registration_id=:id');$pushCleanup->execute([':id'=>$push['id']]);
$favoriteProduct=$wire->pages->get('template='.$wire->sanitizer->selectorValue((string)$commerce->product_template).', status<'.Page::statusHidden.', mrc_product_status=active'); if($favoriteProduct->id){$favorites=$api->updateAccountFavorites($nativeToken,['expected_revision'=>(int)$nativeUpdated['revision'],'product_ids'=>[(int)$favoriteProduct->id]],'favorites-native-'.bin2hex(random_bytes(4)));$favoriteRead=$api->accountFavorites($nativeToken);if(($favorites['products'][0]['id']??0)!==(int)$favoriteProduct->id||($favoriteRead['products'][0]['id']??0)!==(int)$favoriteProduct->id)throw new \RuntimeException('Native favorites write/read failed.');$profileAfterFavorite=$api->accountProfile($nativeToken);$api->updateAccountProfile($nativeToken,['revision'=>(int)$profileAfterFavorite['revision'],'profile'=>['phone'=>'+1 555 0101','preferences'=>['commerce_email'=>false]]],'profile-after-favorite-'.bin2hex(random_bytes(4)));if(($api->accountFavorites($nativeToken)['products'][0]['id']??0)!==(int)$favoriteProduct->id)throw new \RuntimeException('Profile update erased native favorites.');}
$unknown=$service->login('unknown-'.$email,'wrong','127.0.0.1'); $wrong=$service->login($email,'wrong','127.0.0.2'); if (($unknown['message']??'')!==($wrong['message']??'')) throw new \RuntimeException('Login response permits enumeration.');
$before=session_id(); $login=$service->login($email,$password,'127.0.0.3'); if (empty($login['ok']) || $wire->user->id!=$account->id) throw new \RuntimeException('Verified customer sign-in failed.'); $after=session_id(); if ($before!=='' && $after!=='' && hash_equals($before,$after)) throw new \RuntimeException('Session ID was not rotated on sign-in.');
$profile=$service->profile($wire->user); $updated=$service->updateProfile($wire->user,['phone'=>'+1 555 0199','addresses'=>[['label'=>'Home','country'=>'US']],'preferences'=>['commerce_email'=>true]],(int)$profile['revision']); $stale=false; try{$service->updateProfile($wire->user,['phone'=>'stale'],(int)$profile['revision']);}catch(WireException $e){$stale=$e->getCode()===409;} if(!$stale || ($updated['addresses'][0]['country']??'')!=='US') throw new \RuntimeException('Concurrent profile/address handling failed.');
$wire->users->setCurrentUser($super); $items=[['id'=>'account-fixture','product_id'=>999992,'title'=>'Account fixture','sku'=>'ACCOUNT-1','price'=>12,'quantity'=>1,'tax_rate'=>0,'product_type'=>'service','uid'=>'account-fixture']]; $order=$commerce->orderRepository()->savePendingOrder(['first_name'=>'Account','last_name'=>'Fixture','email'=>$email,'payment_status'=>MercatoPaymentStatus::PAID,'payment_complete'=>1,'mrc_items'=>json_encode($items),'mrc_total_amount'=>12,'mrc_currency'=>'USD','mrc_fulfilment_status'=>MercatoFulfilmentStatus::DELIVERED]); $order=$wire->pages->getById((int)$order->id,['cache'=>false])->first(); if((int)$order->mrc_customer_user_id!==0) throw new \RuntimeException('Guest order was linked without verification.');
$wire->users->setCurrentUser($account); $claim=$service->requestGuestOrderClaim($account,$order); if(empty($claim['ok'])) throw new \RuntimeException('Eligible guest claim request failed.'); $order=$wire->pages->getById((int)$order->id,['cache'=>false])->first(); $claimData=json_decode((string)$order->mrc_customer_claim_details,true); if(!is_array($claimData)) throw new \RuntimeException('Claim proof was not stored.');
$claimToken=''; $order->of(false); $claimToken=bin2hex(random_bytes(32)); $claimData['token_hash']=hash('sha256',$claimToken); $order->mrc_customer_claim_details=json_encode($claimData); $wire->users->setCurrentUser($super); $wire->pages->save($order); $wire->users->setCurrentUser($account); if(!$service->claimGuestOrder($account,$order,$claimToken) || !$service->ownsOrder($account,$order)) throw new \RuntimeException('Guest order claim/ownership failed.'); if($service->ownsOrder($super,$order)) throw new \RuntimeException('Non-owner accessed customer order.');
$nativeOrders=$api->accountOrders($nativeToken,['page'=>1,'limit'=>10]); if(empty($nativeOrders['data'])||!str_starts_with((string)($nativeOrders['data'][0]['id']??''),'aord_')) throw new \RuntimeException('Native owned order history failed.'); $api->logoutAccount($nativeToken); $revoked=false; try{$api->accountProfile($nativeToken);}catch(MercatoHeadlessApiException $e){$revoked=$e->httpStatus===401;} if(!$revoked) throw new \RuntimeException('Native logout did not revoke the account token.');
$commerce->set('customer_accounts_mode','disabled'); $blocked=false; try{$service->register('disabled-'.$email,$password);}catch(WireException $e){$blocked=$e->getCode()===403;} if(!$blocked) throw new \RuntimeException('Disabled account mode accepted registration.');
$commerce->set('customer_accounts_mode',$originalMode); $commerce->set('notification_sender_email',$originalSender); $wire->users->setCurrentUser($super); $wire->set('page',$wire->pages->get('/')); $account->of(false); $wire->users->delete($account); echo "Mercato customer account integration tests passed; fixture order {$order->id}.\n";
