<?php
namespace ProcessWire;
$site=getenv('MERCATO_TEST_SITE');if(!$site){echo "Mercato operations integration test skipped (set MERCATO_TEST_SITE).\n";exit(0);}$_SERVER['HTTP_HOST']='mercato.test';$_SERVER['SERVER_NAME']='mercato.test';$_SERVER['REQUEST_URI']='/';$_SERVER['SCRIPT_NAME']='/index.php';$_SERVER['SCRIPT_FILENAME']=$site.'/index.php';require $site.'/wire/core/ProcessWire.php';$config=ProcessWire::buildConfig($site);$config->dbHost='127.0.0.1';$wire=new ProcessWire($config);$super=$wire->users->get('template=user, roles.name=superuser');$wire->users->setCurrentUser($super);/** @var Mercato $commerce */$commerce=$wire->modules->get('Mercato');$service=$commerce->operationalService();$stored=(array)$wire->modules->getConfig($commerce);$originalEvidence=$stored['backup_evidence']??'';$originalCheckout=$commerce->checkout_enabled;$originalRequired=$commerce->preupgrade_backup_required;
try{
$commerce->set('backup_evidence','');$missing=$service->backupStatus();if(!empty($missing['recorded'])||!empty($missing['fresh']))throw new \RuntimeException('Missing backup was reported as fresh.');
$commerce->set('backup_evidence',json_encode(['created_at'=>date(DATE_ATOM,time()-172800),'scope'=>['database','site_files'],'destination_category'=>'offsite']));$stale=$service->backupStatus();if(!empty($stale['fresh'])||empty($stale['recorded']))throw new \RuntimeException('Stale backup boundary failed.');
$fresh=$service->recordBackupEvidence(['created_at'=>time(),'scope'=>['database','site_files','product_assets','configuration','release_metadata'],'destination_category'=>'offsite','restore_verified_at'=>time(),'release'=>'integration-fixture']);if(empty($fresh['fresh'])||empty($fresh['restore_verified']))throw new \RuntimeException('Fresh verified backup evidence failed.');
$commerce->set('preupgrade_backup_required',true);$service->assertPreUpgradeBackup();$commerce->set('backup_evidence',json_encode(['created_at'=>date(DATE_ATOM,time()-172800),'scope'=>['database','site_files','configuration','release_metadata'],'destination_category'=>'offsite']));$blocked=false;try{$service->assertPreUpgradeBackup();}catch(WireException){$blocked=true;}if(!$blocked)throw new \RuntimeException('Stale pre-upgrade backup did not block migration.');
$commerce->set('checkout_enabled',false);$maintenance=false;try{$commerce->paymentService()->initializePayment([]);}catch(WireException $e){$maintenance=$e->getCode()===503;}if(!$maintenance)throw new \RuntimeException('Maintenance mode did not fail checkout closed.');
$items=[['id'=>'restore-fixture','product_id'=>999993,'title'=>'Restore fixture','sku'=>'RESTORE-1','price'=>8,'quantity'=>1,'tax_rate'=>0,'product_type'=>'service','uid'=>'restore-fixture']];$order=$commerce->orderRepository()->savePendingOrder(['first_name'=>'Restore','last_name'=>'Fixture','email'=>'restore-fixture@example.test','payment_status'=>MercatoPaymentStatus::PENDING,'payment_complete'=>0,'mrc_items'=>json_encode($items),'mrc_total_amount'=>8,'mrc_currency'=>'USD']);$order->of(false);$order->mrc_inventory_reserved=1;$order->mrc_inventory_reserved_until=date('Y-m-d H:i:s',time()-60);$wire->pages->save($order);if($commerce->orderRepository()->cleanupExpiredReservations()<1)throw new \RuntimeException('Restored expired reservation was not released.');$order=$wire->pages->getById((int)$order->id,['cache'=>false])->first();if((int)$order->mrc_inventory_reserved!==0)throw new \RuntimeException('Restored reservation remains active.');
$audit=$commerce->paymentReconciliationAuditService()->inspect($order,[],false);if(!array_key_exists('healthy',$audit)||!isset($audit['issues'],$audit['order_id']))throw new \RuntimeException('Post-restore reconciliation inspection failed.');
$health=$service->health(true);$json=json_encode($health);if(!isset($health['checks']['database'],$health['checks']['storage'],$health['checks']['backup'],$health['checks']['reservations'])||str_contains((string)$json,'restore-fixture@example.test'))throw new \RuntimeException('Health diagnostics are incomplete or contain PII.');
}finally{$stored['backup_evidence']=$originalEvidence;$wire->modules->saveConfig($commerce,$stored);$commerce->set('backup_evidence',$originalEvidence);$commerce->set('checkout_enabled',$originalCheckout);$commerce->set('preupgrade_backup_required',$originalRequired);}
echo "Mercato operations integration tests passed; fixture order {$order->id}.\n";
