<?php
namespace ProcessWire;
$site=getenv('MERCATO_TEST_SITE');if(!$site){echo "Mercato headless API integration test skipped (set MERCATO_TEST_SITE).\n";exit(0);}require $site.'/wire/core/ProcessWire.php';$config=ProcessWire::buildConfig($site);$config->dbHost='localhost';$wire=new ProcessWire($config);$wire->users->setCurrentUser($wire->users->get('template=user, roles.name=superuser'));$wire->set('page',$wire->pages->get('/'));/** @var Mercato $commerce */$commerce=$wire->modules->get('Mercato');$service=$commerce->headlessApiService();$product=null;foreach($wire->pages->find('template=mrc-product,mrc_product_status=active,mrc_product_type=physical,include=all')as$candidate){if($commerce->variantService()->getDefinition($candidate)['variants']===[]){$product=$candidate;break;}}if(!$product instanceof Page||!$product->id)throw new \RuntimeException('Non-variant physical fixture product missing.');$originalStock=(int)$product->mrc_stock;$originalPrice=(float)$product->mrc_price;$originalCart=$commerce->cart()->toArray();$originalMethods=$commerce->enabled_payment_methods;$commerce->set('enabled_payment_methods',['demo']);$order=null;$nonce=bin2hex(random_bytes(6));
$customer=['first_name'=>'Native','last_name'=>'Fixture','email'=>'api-'.$nonce.'@example.test','address'=>'API Street','city'=>'Test City','zip'=>'10001','country'=>'US'];$options=['fulfilment_method'=>'carrier_delivery','payment_method'=>'demo','policy_accepted'=>true];$body=['items'=>[['product_id'=>(int)$product->id,'quantity'=>1]],'customer'=>$customer,'options'=>$options];
try{
 $quote=$service->quote($body);if(($quote['item_count']??0)!==1||(float)$quote['total']<=0)throw new \RuntimeException('Authoritative API quote failed.');
 $product->of(false);$product->mrc_price=$originalPrice+1;$wire->pages->save($product);$changed=$service->quote($body);if((float)$changed['subtotal']<=(float)$quote['subtotal'])throw new \RuntimeException('API trusted stale client pricing.');$product->mrc_price=$originalPrice;$wire->pages->save($product);
 $created=$service->createCheckout($body,'create-'.$nonce);$replayed=$service->createCheckout($body,'create-'.$nonce);if($created['id']!==$replayed['id']||empty($created['token']))throw new \RuntimeException('Checkout creation was not idempotent.');$order=$wire->pages->get('template=mrc-order,include=all,mrc_api_checkout_id='.$wire->sanitizer->selectorValue($created['id']));if(!$order->id)throw new \RuntimeException('Opaque checkout was not persisted.');
 $notFound=false;try{$service->checkout($created['id'],'wrong-token');}catch(MercatoHeadlessApiException $e){$notFound=$e->httpStatus===404;}if(!$notFound)throw new \RuntimeException('Invalid token disclosed checkout state.');
 $first=$service->complete($created['id'],$created['token'],[],'complete-'.$nonce);$second=$service->complete($created['id'],$created['token'],[],'complete-'.$nonce);if(empty($first['payment_complete'])||empty($second['replayed']))throw new \RuntimeException('Completion replay was not idempotent.');$public=$service->order($created['order_id'],$created['token']);if(($public['payment_status']??'')!==MercatoPaymentStatus::PAID||isset($public['email'])||isset($public['address']))throw new \RuntimeException('Order API status or privacy contract failed.');
 $details=json_decode((string)$order->mrc_api_details,true);$details['expires_at']=time()-1;$order->of(false);$order->mrc_api_details=json_encode($details);$wire->pages->save($order);$expired=false;try{$service->checkout($created['id'],$created['token']);}catch(MercatoHeadlessApiException $e){$expired=$e->httpStatus===410;}if(!$expired)throw new \RuntimeException('Expired API token remained usable.');
 $product->of(false);$product->mrc_stock=0;$wire->pages->save($product);$blocked=false;try{$service->createCheckout($body,'stock-'.$nonce);}catch(WireException $e){$blocked=str_contains(strtolower($e->getMessage()),'stock')||str_contains(strtolower($e->getMessage()),'available');}if(!$blocked)throw new \RuntimeException('Insufficient stock checkout was accepted.');
}finally{$commerce->set('enabled_payment_methods',$originalMethods);$commerce->cart($originalCart);$product->of(false);$product->mrc_price=$originalPrice;$product->mrc_stock=$originalStock;$wire->pages->save($product);if($order instanceof Page&&$order->id){$order->of(false);$wire->pages->delete($order,true);}}
echo "Mercato headless API integration tests passed.\n";
