<?php
namespace ProcessWire;
$site=getenv('MERCATO_TEST_SITE');if(!$site){echo "Mercato analytics integration test skipped (set MERCATO_TEST_SITE).\n";exit(0);}$_SERVER['HTTP_HOST']='mercato.dev';$_SERVER['SERVER_NAME']='mercato.dev';$_SERVER['REQUEST_URI']='/';$_SERVER['SCRIPT_NAME']='/index.php';$_SERVER['SCRIPT_FILENAME']=$site.'/index.php';require $site.'/wire/core/ProcessWire.php';$config=ProcessWire::buildConfig($site);$config->dbHost='localhost';$wire=new ProcessWire($config);$wire->users->setCurrentUser($wire->users->get('template=user, roles.name=superuser'));/** @var Mercato $commerce */$commerce=$wire->modules->get('Mercato');$original=['enabled'=>$commerce->analytics_enabled,'adapters'=>$commerce->analytics_adapters,'default'=>$commerce->analytics_default_consent,'identifier'=>$commerce->analytics_order_identifier];$commerce->set('analytics_enabled',true);$commerce->set('analytics_adapters',['data_layer','first_party']);$commerce->set('analytics_default_consent','denied');$commerce->set('analytics_order_identifier','hash');$analytics=$commerce->analyticsService();$analytics->setConsent(['analytics'=>false]);
$items=[['id'=>'analytics-fixture','product_id'=>999994,'title'=>'Analytics fixture','sku'=>'AN-1','price'=>48.125,'quantity'=>2,'tax_rate'=>0,'product_type'=>'service','variant_id'=>'blue','uid'=>'analytics-fixture']];$order=$commerce->orderRepository()->savePendingOrder(['first_name'=>'Private','last_name'=>'Analytics','email'=>'analytics-private@example.test','address'=>'Secret Street','payment_status'=>MercatoPaymentStatus::PAID,'payment_complete'=>1,'mrc_items'=>json_encode($items),'mrc_subtotal_amount'=>96.25,'mrc_shipping_amount'=>5,'mrc_discount_code'=>'SAVE10','mrc_discount_total'=>10,'mrc_tax_amount'=>12.25,'mrc_total_amount'=>91.25,'mrc_currency'=>'EUR','mrc_fulfilment_status'=>MercatoFulfilmentStatus::DELIVERED]);$order=$wire->pages->getById((int)$order->id,['cache'=>false])->first();
$first=$analytics->trackOrder($order,'purchase',[],'purchase:'.$order->id);$retry=$analytics->trackOrder($order,'purchase',[],'purchase:'.$order->id);if(($first['status']??'')!=='pending_consent'||($retry['status']??'')!=='duplicate'||$analytics->consumeOrderEvent($order,'purchase')!==[])throw new \RuntimeException('Consent/idempotency behavior failed.');
$analytics->setConsent(['analytics'=>true]);$purchase=$analytics->consumeOrderEvent($order,'purchase');$refresh=$analytics->consumeOrderEvent($order,'purchase');if(!$purchase||$refresh!==[]||abs((float)($purchase['value']??0)-91.25)>0.001||($purchase['currency']??'')!=='EUR'||abs((float)($purchase['discount']??0)-10)>0.001||abs((float)($purchase['tax']??0)-12.25)>0.001||strlen((string)($purchase['order_identifier']??''))!==64)throw new \RuntimeException('Delayed purchase delivery or immutable totals failed.');
$analytics->trackOrder($order,'refund',['refund_amount'=>10],'refund:'.$order->id.':r1');$analytics->trackOrder($order,'refund',['refund_amount'=>5],'refund:'.$order->id.':r2');$duplicateRefund=$analytics->trackOrder($order,'refund',['refund_amount'=>5],'refund:'.$order->id.':r2');if(($duplicateRefund['status']??'')!=='duplicate')throw new \RuntimeException('Refund retry emitted twice.');$state=json_decode((string)$wire->pages->getById((int)$order->id,['cache'=>false])->first()->mrc_analytics_details,true);if(count((array)($state['events']??[]))!==3)throw new \RuntimeException('Partial refund business transitions were not exact-once.');
$json=json_encode($state);foreach(['analytics-private@example.test','Secret Street','payment_details','token','signed_url']as$forbidden)if(str_contains((string)$json,$forbidden))throw new \RuntimeException('Analytics order state leaked PII or secrets.');
$commerce->set('analytics_adapters',['failing']);$wire->addHookAfter('Mercato::analyticsAdapters',function(HookEvent $event){$event->return=['failing'=>new class implements MercatoAnalyticsAdapterInterface{public function getAnalyticsAdapterKey():string{return'failing';}public function getConsentCategory():string{return'analytics';}public function dispatch(array $event):array{throw new \RuntimeException('fixture adapter failure');}}];});$failed=$analytics->track('search',['query_length'=>4,'result_count'=>2]);if(($failed['status']??'')!=='processed'||!empty($failed['adapters']['failing']['accepted']))throw new \RuntimeException('Adapter failure interrupted analytics pipeline.');
$commerce->set('analytics_enabled',$original['enabled']);$commerce->set('analytics_adapters',$original['adapters']);$commerce->set('analytics_default_consent',$original['default']);$commerce->set('analytics_order_identifier',$original['identifier']);echo "Mercato analytics integration tests passed; fixture order {$order->id}.\n";
