<?php
namespace ProcessWire;

final class MercatoHeadlessApiException extends WireException {
    public function __construct(public readonly string $apiCode, string $message, public readonly int $httpStatus = 400, public readonly array $fields = []) { parent::__construct($message, $httpStatus); }
}

final class MercatoHeadlessApiService extends Wire {
    public function __construct(private readonly Mercato $commerce) { parent::__construct(); }

    public function maxBodyBytes(): int { return max(1024, min(1048576, (int) ($this->commerce->headless_api_max_body_bytes ?? 65536))); }
    public function requestHeaders(): array {
        $headers=[]; foreach ($_SERVER as $key=>$value) if (str_starts_with($key,'HTTP_')) $headers[strtolower(str_replace('_','-',substr($key,5)))] = (string) $value; return $headers;
    }
    public function isAllowedOrigin(string $origin): bool {
        if (!preg_match('#^https://[^/]+$#i', $origin)) return false;
        $allowed=preg_split('/[\r\n,]+/', (string) ($this->commerce->headless_api_allowed_origins ?? ''), -1, PREG_SPLIT_NO_EMPTY) ?: [];
        return in_array(strtolower($origin), array_map(static fn($v)=>strtolower(trim($v)), $allowed), true);
    }
    public function assertRequestAllowed(string $bucket): void {
        if (!empty($this->commerce->production) && !str_starts_with(strtolower($this->commerce->getHttpRoot()), 'https://')) throw new MercatoHeadlessApiException('https_required','Production API requires HTTPS.',503);
        $limit=max(1,min(1000,(int)($this->commerce->headless_api_rate_limit_per_minute??60))); $ip=(string)($this->wire('session')->getIP()?:'unknown'); $window=(int)floor(time()/60);
        $key='Mercato.api.rate.'.hash('sha256',$ip.'|'.$bucket.'|'.$window); $count=(int)$this->wire('cache')->get($key); if($count >= $limit) throw new MercatoHeadlessApiException('rate_limited','Too many API requests.',429);
        $this->wire('cache')->save($key,(string)($count+1),90);
    }

    public function dispatch(string $method,string $resource='',string $id='',string $action='',array $body=[],array $query=[],array $headers=[]): array {
        $resource=strtolower(trim($resource?:'store')); $action=strtolower(trim($action));
        if($method==='GET'&&$resource==='store') return ['resource'=>'store','data'=>$this->store()];
        if($method==='GET'&&$resource==='products'&&$id==='') return ['resource'=>'products']+$this->products($query);
        if($method==='GET'&&$resource==='products') return ['resource'=>'product','data'=>$this->product($id)];
        if($method==='GET'&&$resource==='collections'&&$id==='') return ['resource'=>'collections']+$this->collections($query);
        if($method==='GET'&&$resource==='collections') return ['resource'=>'collection','data'=>$this->collection($id,$query)];
        if($method==='POST'&&$resource==='quotes'&&$id==='') return ['status'=>200,'resource'=>'quote','data'=>$this->quote($body)];
        if($method==='POST'&&$resource==='checkouts'&&$id==='') return ['status'=>201,'resource'=>'checkout','data'=>$this->createCheckout($body,$this->requireIdempotency($headers))];
        if($method==='GET'&&$resource==='checkouts'&&$id!=='') return ['resource'=>'checkout','data'=>$this->checkout($id,$this->token($headers))];
        if($method==='POST'&&$resource==='checkouts'&&$id!==''&&$action==='complete') return ['resource'=>'checkout','data'=>$this->complete($id,$this->token($headers),$body,$this->requireIdempotency($headers))];
        if($method==='GET'&&$resource==='orders'&&$id!=='') return ['resource'=>'order','data'=>$this->order($id,$this->token($headers))];
        throw new MercatoHeadlessApiException('route_not_found','API route not found.',404);
    }

    public function store(): array {
        $policies=[]; foreach($this->commerce->getPolicyPages() as $page) $policies[]=['title'=>(string)($page->title?:$page->name),'url'=>(string)$page->httpUrl()];
        $payments=[]; foreach((array)($this->commerce->enabled_payment_methods??[]) as $method){ try{$gateway=$this->commerce->getGateway((string)$method);$status=$gateway->getSetupStatus();$payments[]=['id'=>(string)$method,'gateway'=>$gateway->getName(),'label'=>$gateway->getPaymentMethods()[$method]??$gateway->getLabel(),'ready'=>$status->ready,'capabilities'=>$gateway->getCapabilities()->toArray()];}catch(\Throwable){} }
        return $this->extend(['name'=>(string)($this->commerce->seo_site_name?:'Mercato Store'),'currency'=>MercatoCurrency::normalizeCode((string)$this->commerce->currency),'api_version'=>'v1','checkout_available'=>$this->commerce->operationalService()->isCheckoutAvailable(),'payments'=>$payments,'policies'=>$policies,'links'=>['products'=>'/api/mercato/v1/products','collections'=>'/api/mercato/v1/collections','quotes'=>'/api/mercato/v1/quotes','checkouts'=>'/api/mercato/v1/checkouts']], 'store');
    }
    public function products(array $query): array {
        $page=max(1,(int)($query['page']??1));$limit=max(1,min(50,(int)($query['limit']??20)));$start=($page-1)*$limit;$template=$this->safe((string)($this->commerce->product_template?:'mrc-product'));
        $parts=["template=$template",'mrc_product_status=active'];$q=trim((string)($query['q']??''));if($q!=='')$parts[]='title|mrc_sku|mrc_description%='.$this->safe($q);$type=trim((string)($query['type']??''));if($type!=='')$parts[]='mrc_product_type='.$this->safe($type);$collection=(int)($query['collection']??0);if($collection>0)$parts[]='mrc_collections='.$collection;
        $sort=match((string)($query['sort']??'title')){'price'=>'mrc_price','-price'=>'-mrc_price','-created'=>'-created',default=>'title'};$base=implode(', ',$parts);$total=(int)$this->wire('pages')->count($base);$items=[];foreach($this->wire('pages')->find("$base, sort=$sort, start=$start, limit=$limit") as $p)$items[]=$this->serializeProduct($p);
        return ['data'=>$items,'meta'=>$this->pagination($page,$limit,$total)];
    }
    public function product(string|int $id): array { $p=$this->findProduct($id);if(!$p)throw new MercatoHeadlessApiException('not_found','Product not found.',404);return $this->serializeProduct($p); }
    public function collections(array $query): array {
        $page=max(1,(int)($query['page']??1));$limit=max(1,min(50,(int)($query['limit']??20)));$start=($page-1)*$limit;$base='template=mrc-collection';$total=(int)$this->wire('pages')->count($base);$items=[];foreach($this->wire('pages')->find("$base, sort=sort, sort=title, start=$start, limit=$limit")as$p)$items[]=$this->serializeCollection($p);return ['data'=>$items,'meta'=>$this->pagination($page,$limit,$total)];
    }
    public function collection(string|int $id,array $query=[]): array { $p=$this->findPage('mrc-collection',$id);if(!$p)throw new MercatoHeadlessApiException('not_found','Collection not found.',404);$data=$this->serializeCollection($p);$query['collection']=$p->id;$data['products']=$this->products($query);return $data; }
    public function quote(array $body): array {
        $items=$this->requestedItems($body['items']??[]);$customer=is_array($body['customer']??null)?$body['customer']:[];$options=is_array($body['options']??null)?$body['options']:[];$quote=$this->commerce->getHeadlessCheckoutQuote($items,$customer,$options);
        if(!empty($options['discount_code'])&&empty($quote['discount_valid']))throw new MercatoHeadlessApiException('validation_failed','Coupon could not be applied.',422,['discount_code'=>'Coupon is invalid or unavailable.']);
        return $this->publicQuote($quote);
    }
    public function createCheckout(array $body,string $idempotency): array {
        $requestHash=hash('sha256',$this->canonical($body));$cacheKey=$this->idemKey('create',$idempotency);$cached=$this->cached($cacheKey,$requestHash);if($cached!==null)return $cached;
        $items=$this->requestedItems($body['items']??[]);$customer=is_array($body['customer']??null)?$body['customer']:[];$options=is_array($body['options']??null)?$body['options']:[];$fields=$this->validateCheckoutInput($customer,$options);if($fields)throw new MercatoHeadlessApiException('validation_failed','Checkout data is invalid.',422,$fields);
        $quote=$this->commerce->getHeadlessCheckoutQuote($items,$customer,$options);if(!empty($options['discount_code'])&&empty($quote['discount_valid']))throw new MercatoHeadlessApiException('validation_failed','Coupon could not be applied.',422,['discount_code'=>'Coupon is invalid or unavailable.']);
        $session=$this->wire('session');$sessionKeys=['mrc_cart_items','mrc_cart_updated_at','mrc_discount_code','mrc_pending_order','mrc_checkout_started_nonce','mrc_checkout_redirect'];$snapshot=[];foreach($sessionKeys as$key)$snapshot[$key]=$session->get($key);$originalCart=$this->commerce->cart()->toArray();
        try{
            $this->commerce->cart($items);$data=array_merge($customer,$options,['mrc_policy_accepted'=>!empty($options['policy_accepted'])?1:0,'checkout_nonce'=>'api_'.$requestHash]);$redirect=$this->commerce->initializePayment($data);$pending=$session->get('mrc_pending_order');if(!is_array($pending)||empty($pending['mrc_order_page_id']))throw new WireException('Payment initialization did not create an order.',502);
            $order=$this->commerce->getOrder((int)$pending['mrc_order_page_id']);if(!$order)throw new WireException('Pending order was not found.',502);$token=$this->idempotentToken($cacheKey,$requestHash);$checkoutId=$this->opaque('chk',18);$orderId=$this->opaque('ord',18);$expires=time()+max(5,min(10080,(int)($this->commerce->headless_api_token_ttl_minutes??60)))*60;
            $details=['version'=>1,'token_hash'=>$this->tokenHash($token),'expires_at'=>$expires,'scopes'=>['checkout:read','checkout:complete','order:read'],'payment_context_encrypted'=>$this->encryptContext($this->paymentContext($pending)),'created_idempotency_hash'=>hash('sha256',$idempotency),'complete_keys'=>[]];
            $order->of(false);$order->mrc_api_checkout_id=$checkoutId;$order->mrc_api_order_id=$orderId;$order->mrc_api_details=json_encode($details,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);$this->wire('pages')->save($order);
            $result=['id'=>$checkoutId,'order_id'=>$orderId,'token'=>$token,'token_expires_at'=>gmdate(DATE_ATOM,$expires),'state'=>$this->serializeCheckout($order),'quote'=>$this->publicQuote($quote),'payment'=>$this->paymentInstructions($order,$pending,$redirect)];$this->storeCached($cacheKey,$requestHash,$result,$expires-time());return $result;
        }finally{foreach($snapshot as$key=>$value){if($value===null)$session->remove($key);else$session->set($key,$value);}$this->commerce->cart($originalCart);}
    }
    public function checkout(string $id,string $token): array {$order=$this->authorizedOrder('mrc_api_checkout_id',$id,$token,'checkout:read');return $this->serializeCheckout($order)+['order_id'=>(string)$order->mrc_api_order_id];}
    public function complete(string $id,string $token,array $body,string $idempotency): array {
        $order=$this->authorizedOrder('mrc_api_checkout_id',$id,$token,'checkout:complete');$details=$this->details($order);$keyHash=hash('sha256',$idempotency);$payloadHash=hash('sha256',$this->canonical($body));
        if(isset($details['complete_keys'][$keyHash])){if(!hash_equals((string)$details['complete_keys'][$keyHash],$payloadHash))throw new MercatoHeadlessApiException('idempotency_conflict','Idempotency key was reused with different input.',409);return $this->serializeCheckout($order)+['order_id'=>(string)$order->mrc_api_order_id,'replayed'=>true];}
        if((int)$order->mrc_payment_complete!==1){$session=$this->wire('session');$old=$session->get('mrc_pending_order');try{$pending=array_merge($this->commerce->orderRepository()->pageToPendingData($order),$this->decryptContext((string)($details['payment_context_encrypted']??'')));$session->set('mrc_pending_order',$pending);$order=$this->commerce->completePayment($body);}finally{if($old===null)$session->remove('mrc_pending_order');else$session->set('mrc_pending_order',$old);}}
        $details=$this->details($order);$details['complete_keys'][$keyHash]=$payloadHash;$order->of(false);$order->mrc_api_details=json_encode($details,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);$this->wire('pages')->save($order);return $this->serializeCheckout($order)+['order_id'=>(string)$order->mrc_api_order_id,'replayed'=>false];
    }
    public function order(string $id,string $token): array {$order=$this->authorizedOrder('mrc_api_order_id',$id,$token,'order:read');return $this->serializeOrder($order);}

    private function serializeProduct(Page $p):array{$purchase=$this->commerce->getProductPurchasability($p);$images=[];if($p->hasField('mrc_images'))foreach($p->mrc_images as$image)$images[]=['url'=>(string)$image->httpUrl(),'width'=>(int)$image->width,'height'=>(int)$image->height,'alt'=>(string)($image->description?:$p->title)];$collections=[];if($p->hasField('mrc_collections'))foreach($p->mrc_collections as$c)$collections[]=['id'=>(int)$c->id,'name'=>(string)$c->name,'title'=>(string)$c->title];$definition=$this->commerce->variantService()->getDefinition($p);$data=['id'=>(int)$p->id,'name'=>(string)$p->name,'title'=>(string)$p->title,'url'=>(string)$p->httpUrl(),'description'=>trim(strip_tags((string)$p->mrc_description)),'sku'=>(string)$p->mrc_sku,'type'=>(string)($p->mrc_product_type?:'physical'),'price'=>round((float)$p->mrc_price,2),'currency'=>MercatoCurrency::normalizeCode((string)$this->commerce->currency),'tax_rate'=>round((float)$p->mrc_tax_rate,4),'images'=>$images,'collections'=>$collections,'purchasability'=>['purchasable'=>(bool)$purchase['ok'],'reason'=>(string)($purchase['first_error']??''),'stock_state'=>(string)($purchase['stock_label']??''),'available_stock'=>(int)($purchase['available_stock']??0),'stock_policy'=>(string)($purchase['stock_policy']??'')],'variant_options'=>$definition['options'],'variants'=>$definition['variants']];return $this->extend($data,'product',['page'=>$p]);}
    private function serializeCollection(Page $p):array{$images=[];if($p->hasField('mrc_images'))foreach($p->mrc_images as$image)$images[]=['url'=>(string)$image->httpUrl(),'alt'=>(string)($image->description?:$p->title)];return $this->extend(['id'=>(int)$p->id,'name'=>(string)$p->name,'title'=>(string)$p->title,'url'=>(string)$p->httpUrl(),'description'=>trim(strip_tags((string)$p->mrc_description)),'images'=>$images],'collection',['page'=>$p]);}
    private function serializeCheckout(Page $o):array{return ['id'=>(string)$o->mrc_api_checkout_id,'payment_status'=>(string)$o->mrc_payment_status,'payment_complete'=>(int)$o->mrc_payment_complete===1,'order_status'=>$this->commerce->getDerivedOrderStatus($o),'reservation_expires_at'=>(string)$o->mrc_inventory_reserved_until,'total'=>round((float)$o->mrc_total_amount,2),'currency'=>(string)$o->mrc_currency,'updated_at'=>gmdate(DATE_ATOM,(int)$o->modified)];}
    private function serializeOrder(Page $o):array{$items=json_decode((string)$o->mrc_items,true);$data=['id'=>(string)$o->mrc_api_order_id,'invoice'=>(string)$o->mrc_invoice_number,'created_at'=>gmdate(DATE_ATOM,(int)$o->created),'payment_status'=>(string)$o->mrc_payment_status,'payment_complete'=>(int)$o->mrc_payment_complete===1,'order_status'=>$this->commerce->getDerivedOrderStatus($o),'fulfilment'=>['method'=>(string)$o->mrc_fulfilment_method,'status'=>(string)$o->mrc_fulfilment_status,'label'=>(string)$o->mrc_fulfilment_label,'tracking'=>(string)$o->mrc_fulfilment_tracking,'tracking_url'=>(string)$o->mrc_fulfilment_tracking_url],'items'=>is_array($items)?array_map(static fn($i)=>array_intersect_key($i,array_flip(['product_id','title','sku','variant_id','variant_options','price','quantity','product_type'])),$items):[],'totals'=>['subtotal'=>round((float)$o->mrc_subtotal_amount,2),'shipping'=>round((float)$o->mrc_shipping_amount,2),'discount'=>round((float)$o->mrc_discount_total,2),'tax'=>round((float)$o->mrc_tax_amount,2),'total'=>round((float)$o->mrc_total_amount,2),'currency'=>(string)$o->mrc_currency],'links'=>['status'=>$this->commerce->getOrderStatusUrl($o),'receipt'=>$this->commerce->getOrderReceiptUrl($o)]];return $this->extend($data,'order',['page'=>$o]);}
    private function publicQuote(array $q):array{return array_intersect_key($q,array_flip(['items','item_count','currency','subtotal','shipping','discount','tax','total','discount_code','discount_valid','fulfilment_method','fulfilment_label','fulfilment_methods','requires_payment']));}
    private function requestedItems(mixed $items):array{if(!is_array($items)||$items===[])throw new MercatoHeadlessApiException('validation_failed','At least one item is required.',422,['items'=>'Add at least one product.']);$out=[];foreach($items as$i=>$item){if(!is_array($item)||empty($item['product_id'])||(float)($item['quantity']??0)<=0)throw new MercatoHeadlessApiException('validation_failed','Items are invalid.',422,["items.$i"=>'product_id and positive quantity are required.']);$out[]=['product_id'=>(int)$item['product_id'],'id'=>(int)$item['product_id'],'quantity'=>(float)$item['quantity'],'variant_id'=>(string)($item['variant_id']??'')];}return$out;}
    private function validateCheckoutInput(array $c,array $o):array{$e=[];foreach(['first_name','last_name']as$k)if(trim((string)($c[$k]??''))==='')$e["customer.$k"]='Required.';$email=(string)$this->wire('sanitizer')->email((string)($c['email']??''));if($email==='')$e['customer.email']='Valid email required.';if(trim((string)($o['payment_method']??''))==='')$e['options.payment_method']='Required.';if($this->commerce->getPolicyPages()->count()>0&&empty($o['policy_accepted']))$e['options.policy_accepted']='Store policies must be accepted.';return$e;}
    private function paymentInstructions(Page $o,array $p,string $redirect):array{if(!empty($p['stripe_client_secret']))return['mode'=>'client_confirmation','provider'=>'stripe','client_secret'=>(string)$p['stripe_client_secret'],'confirmation'=>'native_sdk','return_url'=>$this->returnUrl($o)];if((string)$o->mrc_payment_method==='bank-transfer')return['mode'=>'offline','provider'=>'bank-transfer','instructions'=>(string)$this->commerce->bank_transfer_instructions];if($redirect!==''){if(!empty($this->commerce->production)&&strtolower((string)parse_url($redirect,PHP_URL_SCHEME))!=='https')throw new MercatoHeadlessApiException('invalid_payment_redirect','Payment provider returned a non-HTTPS redirect.',502);return['mode'=>'redirect','provider'=>(string)$o->mrc_payment_method,'url'=>$redirect,'return_url'=>$this->returnUrl($o)];}return['mode'=>'processing','provider'=>(string)$o->mrc_payment_method];}
    private function returnUrl(Page $o):string{return rtrim($this->commerce->getHttpRoot(),'/').'/api/mercato/v1/checkouts/'.rawurlencode((string)$o->mrc_api_checkout_id);}
    private function paymentContext(array $p):array{return array_intersect_key($p,array_flip(['payment_attempt_id','payment_attempt_idempotency_key','stripe_payment_intent_id','stripe_client_secret','mollie_payment_id','payment_id']));}
    private function authorizedOrder(string $field,string $id,string $token,string $scope):Page{if($id===''||$token==='')throw new MercatoHeadlessApiException('not_found','Resource not found.',404);$o=$this->wire('pages')->get('template='.$this->safe((string)$this->commerce->order_template).', include=all, '.$field.'='.$this->safe($id));if(!$o||!$o->id)throw new MercatoHeadlessApiException('not_found','Resource not found.',404);$d=$this->details($o);if((int)($d['expires_at']??0)<time())throw new MercatoHeadlessApiException('token_expired','Resource credential expired.',410);if(!hash_equals((string)($d['token_hash']??''),$this->tokenHash($token))||!in_array($scope,(array)($d['scopes']??[]),true))throw new MercatoHeadlessApiException('not_found','Resource not found.',404);return$o;}
    private function token(array $h):string{$auth=(string)($h['authorization']??'');if(preg_match('/^Bearer\s+(.+)$/i',$auth,$m))return trim($m[1]);return trim((string)($h['x-mercato-token']??''));}
    private function requireIdempotency(array $h):string{$key=trim((string)($h['idempotency-key']??''));if(!preg_match('/^[A-Za-z0-9._:-]{8,128}$/',$key))throw new MercatoHeadlessApiException('idempotency_key_required','A valid Idempotency-Key header is required.',400,['Idempotency-Key'=>'Use 8-128 safe characters.']);return$key;}
    private function cached(string $key,string $hash):?array{$v=$this->wire('cache')->get($key);if(!$v)return null;$d=json_decode((string)$v,true);if(!is_array($d))return null;if(!hash_equals((string)$d['request_hash'],$hash))throw new MercatoHeadlessApiException('idempotency_conflict','Idempotency key was reused with different input.',409);$response=(array)$d['response'];$response['token']=$this->idempotentToken($key,$hash);return$response;}
    private function storeCached(string $key,string $hash,array $response,int $ttl):void{unset($response['token']);$this->wire('cache')->save($key,json_encode(['request_hash'=>$hash,'response'=>$response],JSON_UNESCAPED_SLASHES),max(300,$ttl));}
    private function idemKey(string $scope,string $key):string{return'Mercato.api.idem.'.hash_hmac('sha256',$scope.'|'.$key,$this->secret());}
    private function tokenHash(string $token):string{return hash_hmac('sha256',$token,$this->secret());}private function secret():string{return(string)($this->wire('config')->userAuthSalt?:__FILE__);}private function opaque(string $prefix,int $bytes=32):string{return$prefix.'_'.rtrim(strtr(base64_encode(random_bytes($bytes)),'+/','-_'),'=');}private function idempotentToken(string $key,string $hash):string{return'tok_'.rtrim(strtr(base64_encode(hash_hmac('sha256',$key.'|'.$hash,$this->secret(),true)),'+/','-_'),'=');}
    private function encryptContext(array $context):string{$iv=random_bytes(12);$tag='';$cipher=openssl_encrypt(json_encode($context,JSON_UNESCAPED_SLASHES),'aes-256-gcm',hash('sha256',$this->secret(),true),OPENSSL_RAW_DATA,$iv,$tag);if($cipher===false)throw new WireException('Could not protect API payment context.',500);return rtrim(strtr(base64_encode($iv.$tag.$cipher),'+/','-_'),'=');}
    private function decryptContext(string $encoded):array{if($encoded==='')return[];$raw=base64_decode(strtr($encoded,'-_','+/'),true);if($raw===false||strlen($raw)<29)throw new MercatoHeadlessApiException('invalid_checkout_state','Checkout payment context is unavailable.',409);$iv=substr($raw,0,12);$tag=substr($raw,12,16);$plain=openssl_decrypt(substr($raw,28),'aes-256-gcm',hash('sha256',$this->secret(),true),OPENSSL_RAW_DATA,$iv,$tag);$data=$plain!==false?json_decode($plain,true):null;if(!is_array($data))throw new MercatoHeadlessApiException('invalid_checkout_state','Checkout payment context is unavailable.',409);return$data;}
    private function canonical(array $v):string{$sort=function(&$x)use(&$sort){if(!is_array($x))return;foreach($x as&$y)$sort($y);if(!array_is_list($x))ksort($x);};$sort($v);return(string)json_encode($v,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);}
    private function details(Page $o):array{$d=json_decode((string)$o->mrc_api_details,true);return is_array($d)?$d:[];}private function safe(string $v):string{return(string)$this->wire('sanitizer')->selectorValue($v);}
    private function findProduct(string|int $id):?Page{return$this->findPage((string)($this->commerce->product_template?:'mrc-product'),$id);}private function findPage(string $template,string|int $id):?Page{$selector='template='.$this->safe($template).', include=all, ';$selector.=ctype_digit((string)$id)?'id='.(int)$id:'name='.$this->safe((string)$id);$p=$this->wire('pages')->get($selector);return$p&&$p->id?$p:null;}
    private function pagination(int $p,int $l,int $t):array{return['page'=>$p,'limit'=>$l,'total'=>$t,'pages'=>(int)ceil($t/$l),'has_next'=>$p*$l<$t];}
    private function extend(array $resource,string $type,array $context=[]):array{$hooked=$this->commerce->headlessApiResource($resource,$type,$context);return is_array($hooked)?$hooked:$resource;}
}
