<?php
namespace ProcessWire;

final class MercatoHeadlessApiException extends WireException {
    public function __construct(public readonly string $apiCode, string $message, public readonly int $httpStatus = 400, public readonly array $fields = []) { parent::__construct($message, $httpStatus); }
}

final class MercatoHeadlessApiService extends Wire {
    public function __construct(private readonly Mercato $commerce) { parent::__construct(); }

    public function maxBodyBytes(): int { return max(1024, min(1048576, (int) ($this->commerce->headless_api_max_body_bytes ?? 65536))); }
    public function requestHeaders(): array {
        $headers=[]; foreach ($_SERVER as $key=>$value) if (str_starts_with($key,'HTTP_')) $headers[strtolower(str_replace('_','-',substr($key,5)))] = (string) $value; return $headers;
    }
    public function isAllowedOrigin(string $origin): bool {
        if (!preg_match('#^https://[^/]+$#i', $origin)) return false;
        $allowed=preg_split('/[\r\n,]+/', (string) ($this->commerce->headless_api_allowed_origins ?? ''), -1, PREG_SPLIT_NO_EMPTY) ?: [];
        return in_array(strtolower($origin), array_map(static fn($v)=>strtolower(trim($v)), $allowed), true);
    }
    public function assertRequestAllowed(string $bucket): void {
        if (!empty($this->commerce->production) && !str_starts_with(strtolower($this->commerce->getHttpRoot()), 'https://')) throw new MercatoHeadlessApiException('https_required','Production API requires HTTPS.',503);
        $limit=max(1,min(1000,(int)($this->commerce->headless_api_rate_limit_per_minute??60))); $ip=(string)($this->wire('session')->getIP()?:'unknown'); $window=(int)floor(time()/60);
        $key='Mercato.api.rate.'.hash('sha256',$ip.'|'.$bucket.'|'.$window); $count=(int)$this->wire('cache')->get($key); if($count >= $limit) throw new MercatoHeadlessApiException('rate_limited','Too many API requests.',429);
        $this->wire('cache')->save($key,(string)($count+1),90);
    }

    public function dispatch(string $method,string $resource='',string $id='',string $action='',array $body=[],array $query=[],array $headers=[]): array {
        $resource=strtolower(trim($resource?:'store')); $action=strtolower(trim($action));
        if($method==='GET'&&$resource==='store') return ['resource'=>'store','data'=>$this->store()];
        if($method==='GET'&&$resource==='products'&&$id==='') return ['resource'=>'products']+$this->products($query);
        if($method==='GET'&&$resource==='products') return ['resource'=>'product','data'=>$this->product($id,$query)];
        if($method==='GET'&&$resource==='collections'&&$id==='') return ['resource'=>'collections']+$this->collections($query);
        if($method==='GET'&&$resource==='collections') return ['resource'=>'collection','data'=>$this->collection($id,$query)];
        if($method==='POST'&&$resource==='carts'&&$id==='') return ['status'=>201,'resource'=>'cart','data'=>$this->createCart($body,$this->requireIdempotency($headers))];
        if($method==='GET'&&$resource==='carts'&&$id!=='') return ['resource'=>'cart','data'=>$this->cart($id,$this->token($headers))];
        if($method==='POST'&&$resource==='carts'&&$id!=='') return ['resource'=>'cart','data'=>$this->updateCart($id,$this->token($headers),$body,$this->requireIdempotency($headers))];
        if($method==='POST'&&$resource==='account'&&$id==='register') return ['status'=>202,'resource'=>'account','data'=>$this->registerAccount($body)];
        if($method==='POST'&&$resource==='account'&&$id==='login') return ['resource'=>'account_session','data'=>$this->loginAccount($body)];
        if($method==='POST'&&$resource==='account'&&$id==='password-reset') return ['status'=>202,'resource'=>'account','data'=>$this->requestAccountPasswordReset($body)];
        if($method==='GET'&&$resource==='account'&&$id==='') return ['resource'=>'account','data'=>$this->accountProfile($this->token($headers))];
        if($method==='POST'&&$resource==='account'&&$id==='profile') return ['resource'=>'account','data'=>$this->updateAccountProfile($this->token($headers),$body,$this->requireIdempotency($headers))];
        if($method==='GET'&&$resource==='account'&&$id==='favorites') return ['resource'=>'account_favorites','data'=>$this->accountFavorites($this->token($headers))];
        if($method==='POST'&&$resource==='account'&&$id==='favorites') return ['resource'=>'account_favorites','data'=>$this->updateAccountFavorites($this->token($headers),$body,$this->requireIdempotency($headers))];
        if($method==='POST'&&$resource==='account'&&$id==='logout') return ['resource'=>'account_session','data'=>$this->logoutAccount($this->token($headers))];
        if($method==='GET'&&$resource==='account'&&$id==='orders') return ['resource'=>'account_orders']+$this->accountOrders($this->token($headers),$query);
        if($method==='GET'&&$resource==='account'&&$id==='deletion-review') return ['resource'=>'account_deletion','data'=>$this->accountDeletionReview($this->token($headers))];
        if($method==='POST'&&$resource==='account'&&$id==='delete') return ['resource'=>'account_deletion','data'=>$this->deleteAccount($this->token($headers),$body,$this->requireIdempotency($headers))];
        if($method==='POST'&&$resource==='devices'&&$id==='') return ['status'=>201,'resource'=>'push_device','data'=>$this->registerPushDevice($this->token($headers),$body,$this->requireIdempotency($headers))];
        if($method==='POST'&&$resource==='devices'&&$id!==''&&$action==='revoke') return ['resource'=>'push_device','data'=>$this->revokePushDevice($id,$this->token($headers),$body,$this->requireIdempotency($headers))];
        if($method==='POST'&&$resource==='quotes'&&$id==='') return ['status'=>200,'resource'=>'quote','data'=>$this->quote($body)];
        if($method==='POST'&&$resource==='checkouts'&&$id==='') return ['status'=>201,'resource'=>'checkout','data'=>$this->createCheckout($body,$this->requireIdempotency($headers),$this->token($headers))];
        if($method==='GET'&&$resource==='checkouts'&&$id!=='') return ['resource'=>'checkout','data'=>$this->checkout($id,$this->token($headers))];
        if($method==='POST'&&$resource==='checkouts'&&$id!==''&&$action==='complete') return ['resource'=>'checkout','data'=>$this->complete($id,$this->token($headers),$body,$this->requireIdempotency($headers))];
        if($method==='GET'&&$resource==='orders'&&$id!=='') return ['resource'=>'order','data'=>$this->order($id,$this->token($headers))];
        if($method==='POST'&&$resource==='orders'&&$id!==''&&$action==='returns') return ['status'=>201,'resource'=>'return_request','data'=>$this->createReturn($id,$this->token($headers),$body,$this->requireIdempotency($headers))];
        if($method==='POST'&&$resource==='orders'&&$id!==''&&$action==='cancellations') return ['status'=>201,'resource'=>'cancellation_request','data'=>$this->createCancellation($id,$this->token($headers),$body,$this->requireIdempotency($headers))];
        throw new MercatoHeadlessApiException('route_not_found','API route not found.',404);
    }

    public function store(): array {
        $this->activateMarketLanguage('default');
        $policies=[]; foreach($this->commerce->getPolicyPages() as $page) $policies[]=['title'=>(string)($page->title?:$page->name),'url'=>(string)$page->httpUrl()];
        $payments=[]; foreach((array)($this->commerce->enabled_payment_methods??[]) as $method){ try{$gateway=$this->commerce->getGateway((string)$method);$status=$gateway->getSetupStatus();$payments[]=['id'=>(string)$method,'gateway'=>$gateway->getName(),'label'=>$gateway->getPaymentMethods()[$method]??$gateway->getLabel(),'ready'=>$status->ready,'capabilities'=>$gateway->getCapabilities()->toArray()];}catch(\Throwable){} }
        $countries=$this->commerce->getAllowedDeliveryCountries();$regions=[];foreach($this->commerce->getDeliveryRegionsByCountry()as$country=>$items){$regions[$country]=[];foreach($items as$code=>$label)$regions[$country][]=['code'=>(string)$code,'label'=>(string)$label];}
        $currency=MercatoCurrency::normalizeCode((string)$this->commerce->currency);$markets=$this->commerce->marketService()->all();$contact=$this->wire('pages')->get('/contact-us/');$contactUrl=$contact&&$contact->id&&(int)$contact->status<Page::statusHidden?(string)$contact->httpUrl():rtrim($this->commerce->getHttpRoot(),'/').'/contact-us/';$supportEmail=(string)$this->wire('sanitizer')->email((string)($this->commerce->notification_reply_to??''));$support=['url'=>$contactUrl,'email'=>$supportEmail,'transactional_email_available'=>(string)$this->wire('sanitizer')->email((string)($this->commerce->notification_sender_email??''))!=='','transactional_push_available'=>$this->commerce->pushNotificationService()->isReady()];
        $accountMode=MercatoAccountPolicy::normalizeMode((string)($this->commerce->customer_accounts_mode??'disabled'));$links=['products'=>'/api/mercato/v1/products','collections'=>'/api/mercato/v1/collections','carts'=>'/api/mercato/v1/carts','quotes'=>'/api/mercato/v1/quotes','checkouts'=>'/api/mercato/v1/checkouts','devices'=>'/api/mercato/v1/devices'];if($accountMode!=='disabled')$links['account']='/api/mercato/v1/account';
        return $this->extend(['name'=>(string)($this->commerce->seo_site_name?:'Mercato Store'),'currency'=>$currency,'api_version'=>'v1','checkout_available'=>$this->commerce->operationalService()->isCheckoutAvailable(),'account_mode'=>$accountMode,'markets'=>$markets,'commerce_context'=>$this->commerce->marketService()->context(),'delivery'=>['countries_restricted'=>$countries!==[],'countries'=>$countries,'regions'=>(object)$regions],'payments'=>$payments,'policies'=>$policies,'support'=>$support,'links'=>$links], 'store');
    }
    public function products(array $query): array {
        $marketId=$this->marketId($query);$this->activateMarketLanguage($marketId);$page=max(1,(int)($query['page']??1));$limit=max(1,min(50,(int)($query['limit']??20)));$start=($page-1)*$limit;$template=$this->safe((string)($this->commerce->product_template?:'mrc-product'));
        $facetParts=["template=$template",'status<'.Page::statusHidden,'mrc_product_status=active'];$q=trim((string)($query['q']??''));if($q!=='')$facetParts[]='title|mrc_sku|mrc_description%='.$this->safe($q);
        $minimum=isset($query['min_price'])&&is_numeric($query['min_price'])?max(0,(float)$query['min_price']):null;$maximum=isset($query['max_price'])&&is_numeric($query['max_price'])?max(0,(float)$query['max_price']):null;
        $parts=$facetParts;$type=trim((string)($query['type']??''));if(in_array($type,['physical','service','digital'],true))$parts[]='mrc_product_type='.$this->safe($type);$collection=(int)($query['collection']??0);if($collection>0)$parts[]='mrc_collections='.$collection;
        $sort=(string)($query['sort']??'title');$base=implode(', ',$parts);$availability=trim((string)($query['availability']??''));$optionFilters=[];foreach($query as$key=>$value){if(count($optionFilters)>=10||!str_starts_with((string)$key,'option_'))continue;$option=substr((string)$key,7);if(preg_match('/^[A-Za-z0-9_-]{1,80}$/',$option)&&is_scalar($value)&&trim((string)$value)!=='')$optionFilters[$option]=substr(trim((string)$value),0,120);}
        $matching=[];foreach($this->wire('pages')->find("$base, sort=title")as$p){try{$data=$this->serializeProduct($p,$marketId);}catch(WireException){continue;}$price=(float)$data['price'];if($minimum!==null&&$price<$minimum)continue;if($maximum!==null&&$price>$maximum)continue;$purchasable=!empty($data['purchasability']['purchasable']);if($availability==='available'&&!$purchasable)continue;if($availability==='unavailable'&&$purchasable)continue;if(!$this->matchesOptionFilters($data,$optionFilters))continue;$matching[]=$data;}
        if($sort==='price'||$sort==='-price')usort($matching,static fn(array$a,array$b):int=>($sort==='price'?1:-1)*((float)$a['price']<=>(float)$b['price']));elseif($sort==='-created')usort($matching,static fn(array$a,array$b):int=>strcmp((string)($b['created_at']??''),(string)($a['created_at']??'')));
        $total=count($matching);$items=array_slice($matching,$start,$limit);$facetPages=$this->wire('pages')->find(implode(', ',$facetParts).', sort=title');$meta=$this->pagination($page,$limit,$total);$meta['facets']=$this->catalogFacets($facetPages,$marketId);
        return ['data'=>$items,'meta'=>$meta];
    }
    public function product(string|int $id,array $query=[]): array { $marketId=$this->marketId($query);$this->activateMarketLanguage($marketId);$p=$this->findProduct($id);if(!$p)throw new MercatoHeadlessApiException('not_found','Product not found.',404);try{return $this->serializeProduct($p,$marketId);}catch(WireException){throw new MercatoHeadlessApiException('not_found','Product is not available in this market.',404);} }
    public function collections(array $query): array {
        $marketId=$this->marketId($query);$this->activateMarketLanguage($marketId);$page=max(1,(int)($query['page']??1));$limit=max(1,min(50,(int)($query['limit']??20)));$start=($page-1)*$limit;$base='template=mrc-collection, status<'.Page::statusHidden;$total=(int)$this->wire('pages')->count($base);$items=[];foreach($this->wire('pages')->find("$base, sort=sort, sort=title, start=$start, limit=$limit")as$p)$items[]=$this->serializeCollection($p);$meta=$this->pagination($page,$limit,$total);$meta['commerce_context']=$this->commerce->marketService()->context($marketId);return ['data'=>$items,'meta'=>$meta];
    }
    public function collection(string|int $id,array $query=[]): array { $marketId=$this->marketId($query);$this->activateMarketLanguage($marketId);$p=$this->findPage('mrc-collection',$id);if(!$p)throw new MercatoHeadlessApiException('not_found','Collection not found.',404);$data=$this->serializeCollection($p);$data['commerce_context']=$this->commerce->marketService()->context($marketId);$query['collection']=$p->id;$query['market_id']=$marketId;$data['products']=$this->products($query);return $data; }
    public function createCart(array $body,string $idempotency):array{$requestHash=hash('sha256',$this->canonical($body));$cacheKey=$this->idemKey('cart-create',$idempotency);$cached=$this->cached($cacheKey,$requestHash);if($cached!==null)return$cached;$lock=$this->idempotencyLock($cacheKey);try{$cached=$this->cached($cacheKey,$requestHash);if($cached!==null)return$cached;$items=$this->normalizeCartItems($body['items']??[]);$marketId=$this->marketId($body);$id=$this->opaque('cart',18);$token=$this->idempotentToken($cacheKey,$requestHash);$expires=time()+2592000;$record=['id'=>$id,'token_hash'=>$this->tokenHash($token),'version'=>1,'market_id'=>$marketId,'items'=>$items,'expires_at'=>$expires,'updated_at'=>time()];$this->storeCartRecord($record);$result=$this->serializeCart($record)+['token'=>$token];$this->storeCached($cacheKey,$requestHash,$result,$expires-time());return$result;}finally{$this->releaseIdempotencyLock($lock);}}
    public function cart(string $id,string $token):array{return$this->serializeCart($this->authorizedCart($id,$token));}
    public function updateCart(string $id,string $token,array $body,string $idempotency):array{$requestHash=hash('sha256',$this->canonical($body));$cacheKey=$this->idemKey('cart-update|'.$id,$idempotency);$cached=$this->mutationCached($cacheKey,$requestHash);if($cached!==null)return$cached;$lock=$this->idempotencyLock($this->cartRecordKey($id));try{$record=$this->authorizedCart($id,$token);if(!array_key_exists('expected_version',$body))throw new MercatoHeadlessApiException('validation_failed','Cart version is required.',422,['expected_version'=>'Reload the cart and include its version.']);if((int)$body['expected_version']!==(int)$record['version'])throw new MercatoHeadlessApiException('version_conflict','The cart changed in another session. Reload and try again.',409,['expected_version'=>'Current version is '.(int)$record['version'].'.']);$record['items']=$this->normalizeCartItems($body['items']??[]);if(array_key_exists('market_id',$body))$record['market_id']=$this->marketId($body);$record['version']=(int)$record['version']+1;$record['expires_at']=time()+2592000;$record['updated_at']=time();$this->storeCartRecord($record);$result=$this->serializeCart($record);$this->storeMutationCached($cacheKey,$requestHash,$result,3600);return$result;}finally{$this->releaseIdempotencyLock($lock);}}
    public function quote(array $body): array {
        $items=$this->requestedItems($body['items']??[]);$customer=is_array($body['customer']??null)?$body['customer']:[];$options=is_array($body['options']??null)?$body['options']:[];$quote=$this->commerce->getHeadlessCheckoutQuote($items,$customer,$options);
        if(!empty($options['discount_code'])&&empty($quote['discount_valid']))throw new MercatoHeadlessApiException('validation_failed','Coupon could not be applied.',422,['discount_code'=>'Coupon is invalid or unavailable.']);
        return $this->publicQuote($quote);
    }
    public function createCheckout(array $body,string $idempotency,string $accountToken=''): array {
        $accountUser=$accountToken!==''?$this->authorizedAccount($accountToken):null;if($this->commerce->customerAccountService()->isRequiredAtCheckout()&&!$accountUser)throw new MercatoHeadlessApiException('account_required','A verified customer account is required for checkout.',403);
        $requestHash=hash('sha256',$this->canonical($body));$cacheKey=$this->idemKey('create',$idempotency);$cached=$this->cached($cacheKey,$requestHash);if($cached!==null)return $cached;
        $lock=$this->idempotencyLock($cacheKey);try{$cached=$this->cached($cacheKey,$requestHash);if($cached!==null)return $cached;
        $items=$this->requestedItems($body['items']??[]);$customer=is_array($body['customer']??null)?$body['customer']:[];$options=is_array($body['options']??null)?$body['options']:[];$fields=$this->validateCheckoutInput($customer,$options);if($fields)throw new MercatoHeadlessApiException('validation_failed','Checkout data is invalid.',422,$fields);
        $quote=$this->commerce->getHeadlessCheckoutQuote($items,$customer,$options);if(!empty($options['discount_code'])&&empty($quote['discount_valid']))throw new MercatoHeadlessApiException('validation_failed','Coupon could not be applied.',422,['discount_code'=>'Coupon is invalid or unavailable.']);
        $session=$this->wire('session');$sessionKeys=['mrc_cart_items','mrc_cart_updated_at','mrc_discount_code','mrc_pending_order','mrc_checkout_started_nonce','mrc_checkout_redirect'];$snapshot=[];foreach($sessionKeys as$key)$snapshot[$key]=$session->get($key);$originalCart=$this->commerce->cart()->toArray();
        try{
            $this->commerce->cart($quote['items']);$data=array_merge($customer,$options,['mrc_market_id'=>(string)$quote['market_id'],'mrc_policy_accepted'=>!empty($options['policy_accepted'])?1:0,'checkout_nonce'=>'api_'.$requestHash]);$redirect=$this->commerce->initializePayment($data);$pending=$session->get('mrc_pending_order');if(!is_array($pending)||empty($pending['mrc_order_page_id']))throw new WireException('Payment initialization did not create an order.',502);
            $order=$this->commerce->getOrder((int)$pending['mrc_order_page_id']);if(!$order)throw new WireException('Pending order was not found.',502);if($accountUser&&$order->hasField('mrc_customer_user_id')){$order->of(false);$order->mrc_customer_user_id=(int)$accountUser->id;$this->wire('pages')->save($order);} $token=$this->idempotentToken($cacheKey,$requestHash);$checkoutId=$this->opaque('chk',18);$orderId=$this->opaque('ord',18);$expires=time()+max(5,min(10080,(int)($this->commerce->headless_api_token_ttl_minutes??60)))*60;
            $details=['version'=>1,'token_hash'=>$this->tokenHash($token),'expires_at'=>$expires,'scopes'=>['checkout:read','checkout:complete','order:read'],'payment_context_encrypted'=>$this->encryptContext($this->paymentContext($pending)),'created_idempotency_hash'=>hash('sha256',$idempotency),'complete_keys'=>[]];
            $order->of(false);$order->mrc_api_checkout_id=$checkoutId;$order->mrc_api_order_id=$orderId;$order->mrc_api_details=json_encode($details,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);$this->wire('pages')->save($order);
            $result=['id'=>$checkoutId,'order_id'=>$orderId,'token'=>$token,'token_expires_at'=>gmdate(DATE_ATOM,$expires),'state'=>$this->serializeCheckout($order),'quote'=>$this->publicQuote($quote),'payment'=>$this->paymentInstructions($order,$pending,$redirect)];$this->storeCached($cacheKey,$requestHash,$result,$expires-time());return $result;
        }finally{foreach($snapshot as$key=>$value){if($value===null)$session->remove($key);else$session->set($key,$value);}$this->commerce->cart($originalCart);}}finally{$this->releaseIdempotencyLock($lock);}
    }
    public function checkout(string $id,string $token): array {$order=$this->authorizedOrder('mrc_api_checkout_id',$id,$token,'checkout:read');return $this->serializeCheckout($order)+['order_id'=>(string)$order->mrc_api_order_id];}
    public function complete(string $id,string $token,array $body,string $idempotency): array {
        $order=$this->authorizedOrder('mrc_api_checkout_id',$id,$token,'checkout:complete');$details=$this->details($order);$keyHash=hash('sha256',$idempotency);$payloadHash=hash('sha256',$this->canonical($body));
        if(isset($details['complete_keys'][$keyHash])){if(!hash_equals((string)$details['complete_keys'][$keyHash],$payloadHash))throw new MercatoHeadlessApiException('idempotency_conflict','Idempotency key was reused with different input.',409);return $this->serializeCheckout($order)+['order_id'=>(string)$order->mrc_api_order_id,'replayed'=>true];}
        if((int)$order->mrc_payment_complete!==1){$session=$this->wire('session');$old=$session->get('mrc_pending_order');try{$pending=array_merge($this->commerce->orderRepository()->pageToPendingData($order),$this->decryptContext((string)($details['payment_context_encrypted']??'')));$session->set('mrc_pending_order',$pending);$order=$this->commerce->completePayment($body);}finally{if($old===null)$session->remove('mrc_pending_order');else$session->set('mrc_pending_order',$old);}}
        $details=$this->details($order);$details['complete_keys'][$keyHash]=$payloadHash;$order->of(false);$order->mrc_api_details=json_encode($details,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);$this->wire('pages')->save($order);return $this->serializeCheckout($order)+['order_id'=>(string)$order->mrc_api_order_id,'replayed'=>false];
    }
    public function order(string $id,string $token): array {$order=$this->authorizedOrder('mrc_api_order_id',$id,$token,'order:read');return $this->serializeOrder($order);}

    public function createReturn(string $id,string $token,array $body,string $idempotency):array{
        $order=str_starts_with($token,'acct_')?$this->authorizedAccountOrder($this->authorizedAccount($token),$id):$this->authorizedOrder('mrc_api_order_id',$id,$token,'order:read');$eligibility=$this->returnEligibility($order);if(empty($eligibility['can_request']))throw new MercatoHeadlessApiException('return_unavailable',(string)$eligibility['message'],409);
        $reason=trim((string)($body['reason']??''));$reasonLength=function_exists('mb_strlen')?mb_strlen($reason):strlen($reason);if($reasonLength<3||$reasonLength>1000)throw new MercatoHeadlessApiException('validation_failed','Return request is invalid.',422,['reason'=>'Enter a reason from 3 to 1000 characters.']);$requested=$body['items']??null;if(!is_array($requested)||$requested===[])throw new MercatoHeadlessApiException('validation_failed','Select at least one item to return.',422,['items'=>'Select at least one order item.']);
        $orderItems=json_decode((string)$order->mrc_items,true);$available=[];foreach(is_array($orderItems)?$orderItems:[]as$item){if(!is_array($item))continue;$productId=(int)($item['product_id']??$item['id']??0);$variantId=(string)($item['variant_id']??'');$available[$productId.'|'.$variantId]=$item;}$items=[];$fields=[];
        foreach($requested as$index=>$item){if(!is_array($item)){$fields["items.$index"]='Invalid item.';continue;}$productId=(int)($item['product_id']??0);$variantId=(string)($item['variant_id']??'');$key=$productId.'|'.$variantId;$quantity=(int)($item['quantity']??0);$source=$available[$key]??null;$ordered=is_array($source)?max(1,(int)($source['quantity']??1)):0;if(!$source)$fields["items.$index"]='Item is not part of this order.';elseif($quantity<1||$quantity>$ordered)$fields["items.$index.quantity"]="Choose a quantity from 1 to $ordered.";else$items[]=['product_id'=>$productId,'variant_id'=>$variantId,'variant_options'=>(array)($source['variant_options']??[]),'title'=>(string)($source['title']??$source['name']??''),'sku'=>(string)($source['sku']??''),'quantity'=>$quantity];}
        if($fields)throw new MercatoHeadlessApiException('validation_failed','Return items are invalid.',422,$fields);$requestHash=hash('sha256',$this->canonical(['order'=>(int)$order->id,'reason'=>$reason,'items'=>$items]));$cacheKey=$this->idemKey('return|'.(int)$order->id,$idempotency);$cached=$this->mutationCached($cacheKey,$requestHash);if($cached!==null)return$cached;$lock=$this->idempotencyLock($cacheKey);try{$cached=$this->mutationCached($cacheKey,$requestHash);if($cached!==null)return$cached;$created=$this->commerce->createReturnRequest($order,['reason'=>$reason,'items'=>$items,'email'=>(string)$order->mrc_email,'source'=>'headless_api']);$public=['request_id'=>(string)($created['request_id']??''),'status'=>(string)($created['status']??'requested'),'reason'=>(string)($created['reason']??$reason),'items'=>(array)($created['items']??$items),'created_at'=>(string)($created['created_at']??date(DATE_ATOM))];$this->storeMutationCached($cacheKey,$requestHash,$public,86400);return$public;}finally{$this->releaseIdempotencyLock($lock);}
    }

    public function createCancellation(string $id,string $token,array $body,string $idempotency):array{
        $order=str_starts_with($token,'acct_')?$this->authorizedAccountOrder($this->authorizedAccount($token),$id):$this->authorizedOrder('mrc_api_order_id',$id,$token,'order:read');$reason=trim((string)($body['reason']??''));$length=function_exists('mb_strlen')?mb_strlen($reason):strlen($reason);if($length<3||$length>1000)throw new MercatoHeadlessApiException('validation_failed','Cancellation request is invalid.',422,['reason'=>'Enter a reason from 3 to 1000 characters.']);$requestHash=hash('sha256',$this->canonical(['order'=>(int)$order->id,'reason'=>$reason]));$cacheKey=$this->idemKey('cancellation|'.(int)$order->id,$idempotency);$cached=$this->mutationCached($cacheKey,$requestHash);if($cached!==null)return$cached;$lock=$this->idempotencyLock($cacheKey);try{$cached=$this->mutationCached($cacheKey,$requestHash);if($cached!==null)return$cached;$eligibility=$this->commerce->getOrderCancellationEligibility($order);if(empty($eligibility['can_request']))throw new MercatoHeadlessApiException('cancellation_unavailable',(string)$eligibility['message'],409);try{$created=$this->commerce->createCancellationRequest($order,['reason'=>$reason,'source'=>'headless_api']);}catch(WireException $error){if((int)$error->getCode()===409)throw new MercatoHeadlessApiException('cancellation_unavailable',$error->getMessage(),409);throw$error;}$public=array_intersect_key($created,array_flip(['request_id','status','reason','created_at']));$this->storeMutationCached($cacheKey,$requestHash,$public,86400);return$public;}finally{$this->releaseIdempotencyLock($lock);}
    }

    public function registerAccount(array $body):array{
        $email=(string)($body['email']??'');$password=(string)($body['password']??'');$profile=is_array($body['profile']??null)?$body['profile']:[];
        return $this->commerce->customerAccountService()->register($email,$password,$profile);
    }

    public function loginAccount(array $body):array{
        $email=(string)($body['email']??'');$password=(string)($body['password']??'');
        $result=$this->commerce->customerAccountService()->login($email,$password,(string)($_SERVER['REMOTE_ADDR']??''));
        if(empty($result['ok']))throw new MercatoHeadlessApiException('invalid_credentials',(string)($result['message']??'Email or password is incorrect.'),401);
        $user=$this->wire('user');try{$profile=$this->commerce->customerAccountService()->profile($user);$credential=$this->issueAccountToken($user);return $credential+['profile'=>$profile];}finally{$this->commerce->customerAccountService()->logout();}
    }

    public function requestAccountPasswordReset(array $body):array{
        return $this->commerce->customerAccountService()->requestPasswordReset((string)($body['email']??''));
    }

    public function accountProfile(string $token):array{
        return $this->commerce->customerAccountService()->profile($this->authorizedAccount($token));
    }

    public function updateAccountProfile(string $token,array $body,string $idempotency):array{
        $user=$this->authorizedAccount($token);$requestHash=hash('sha256',$this->canonical($body));$cacheKey=$this->idemKey('account-profile|'.$this->accountTokenHash($token),$idempotency);$cached=$this->mutationCached($cacheKey,$requestHash);if($cached!==null)return$cached;
        if(!array_key_exists('revision',$body))throw new MercatoHeadlessApiException('validation_failed','Profile revision is required.',422,['revision'=>'Reload the profile and include its revision.']);
        $profile=is_array($body['profile']??null)?$body['profile']:$body;unset($profile['revision']);if(is_array($profile['preferences']??null)){$current=$this->commerce->customerAccountService()->profile($user);$currentPreferences=is_array($current['preferences']??null)?$current['preferences']:[];if(isset($currentPreferences['favorite_product_ids']))$profile['preferences']['favorite_product_ids']=$currentPreferences['favorite_product_ids'];}$updated=$this->commerce->customerAccountService()->updateProfile($user,$profile,(int)$body['revision']);$this->storeMutationCached($cacheKey,$requestHash,$updated,3600);return$updated;
    }

    public function accountFavorites(string $token):array{
        return $this->favoritesForUser($this->authorizedAccount($token));
    }

    public function updateAccountFavorites(string $token,array $body,string $idempotency):array{
        $user=$this->authorizedAccount($token);$requestHash=hash('sha256',$this->canonical($body));$cacheKey=$this->idemKey('account-favorites|'.$this->accountTokenHash($token),$idempotency);$cached=$this->mutationCached($cacheKey,$requestHash);if($cached!==null)return$cached;
        if(!array_key_exists('expected_revision',$body))throw new MercatoHeadlessApiException('validation_failed','Account revision is required.',422,['expected_revision'=>'Reload favorites and include their revision.']);$ids=$body['product_ids']??null;if(!is_array($ids)||count($ids)>500)throw new MercatoHeadlessApiException('validation_failed','Favorite products are invalid.',422,['product_ids'=>'Use an array containing at most 500 product IDs.']);
        $normalized=[];foreach($ids as$i=>$id){$product=is_scalar($id)?$this->findProduct((int)$id):null;if(!$product)throw new MercatoHeadlessApiException('validation_failed','Favorite products are invalid.',422,["product_ids.$i"=>'Product is unavailable.']);$normalized[(int)$product->id]=true;}$profile=$this->commerce->customerAccountService()->profile($user);$preferences=is_array($profile['preferences']??null)?$profile['preferences']:[];$preferences['favorite_product_ids']=array_keys($normalized);
        try{$this->commerce->customerAccountService()->updateProfile($user,['preferences'=>$preferences],(int)$body['expected_revision']);}catch(WireException $error){if((int)$error->getCode()===409)throw new MercatoHeadlessApiException('version_conflict','The account changed in another session. Reload favorites and try again.',409,['expected_revision'=>'The account revision is no longer current.']);throw$error;}
        $result=$this->favoritesForUser($user);$this->storeMutationCached($cacheKey,$requestHash,$result,3600);return$result;
    }

    public function logoutAccount(string $token):array{
        if($token!=='')$this->wire('cache')->delete($this->accountTokenCacheKey($token));return['logged_out'=>true];
    }

    public function accountOrders(string $token,array $query=[]):array{
        $user=$this->authorizedAccount($token);$page=max(1,(int)($query['page']??1));$limit=max(1,min(50,(int)($query['limit']??20)));$orders=$this->commerce->customerAccountService()->findOrders($user,$page,$limit);$items=[];foreach($orders as$order){$data=$this->serializeOrder($order);$data['id']=$this->accountOrderId($user,$order);$items[]=$data;}$total=method_exists($orders,'getTotal')?(int)$orders->getTotal():count($items);return['data'=>$items,'meta'=>$this->pagination($page,$limit,$total)];
    }

    public function accountDeletionReview(string $token):array{
        $user=$this->authorizedAccount($token);$review=$this->commerce->privacyService()->reviewCustomer((string)$user->email);return['can_delete'=>(int)$review['blocked']===0,'orders'=>(int)$review['total'],'blocked'=>(int)$review['blocked'],'eligible'=>(int)$review['eligible'],'quotes'=>(int)$review['quotes'],'message'=>(int)$review['blocked']===0?'The account and eligible personal data can be anonymized. Financial and audit records may be retained as required.':'Account deletion requires support review because one or more orders have an active legal, payment, reservation, refund, dispute, or fulfilment hold.'];
    }

    public function deleteAccount(string $token,array $body,string $idempotency):array{
        $requestHash=hash('sha256',$this->canonical($body));$cacheKey=$this->idemKey('account-delete|'.$this->accountTokenHash($token),$idempotency);$cached=$this->mutationCached($cacheKey,$requestHash);if($cached!==null)return$cached;$user=$this->authorizedAccount($token);
        if((string)($body['confirmation']??'')!=='DELETE MY ACCOUNT')throw new MercatoHeadlessApiException('confirmation_required','Exact account deletion confirmation is required.',422,['confirmation'=>'Enter DELETE MY ACCOUNT.']);$password=(string)($body['password']??'');if($password==='')throw new MercatoHeadlessApiException('reauthentication_required','Enter the account password to continue.',401);
        $expectedId=(int)$user->id;$login=$this->commerce->customerAccountService()->login((string)$user->email,$password,(string)($_SERVER['REMOTE_ADDR']??''));$authenticated=!empty($login['ok'])&&(int)$this->wire('user')->id===$expectedId;$this->commerce->customerAccountService()->logout();if(!$authenticated)throw new MercatoHeadlessApiException('reauthentication_failed','Account credentials could not be verified.',401);
        $review=$this->commerce->privacyService()->reviewCustomer((string)$user->email);if((int)$review['blocked']>0)throw new MercatoHeadlessApiException('human_review_required','Account deletion requires support review before it can continue.',409);
        $result=$this->commerce->privacyService()->deleteCustomerData((string)$user->email,'customer_requested_native_account_deletion');$public=['status'=>(string)($result['status']??'completed'),'request_id'=>(string)($result['request_id']??''),'account_deleted'=>!empty($result['account_anonymized'])];$this->wire('cache')->delete($this->accountTokenCacheKey($token));$this->storeMutationCached($cacheKey,$requestHash,$public,86400);return$public;
    }

    public function registerPushDevice(string $token,array $body,string $idempotency):array{
        [$ownerType,$ownerId]=$this->pushOwner($token,$body);$requestHash=hash('sha256',$this->canonical($body));$cacheKey=$this->idemKey('push-register|'.$ownerType.'|'.$ownerId,$idempotency);$cached=$this->mutationCached($cacheKey,$requestHash);if($cached!==null)return$cached;
        try{$result=$this->commerce->pushNotificationService()->register($body,$ownerType,$ownerId);}catch(WireException$error){$status=in_array((int)$error->getCode(),[403,404,422],true)?(int)$error->getCode():422;throw new MercatoHeadlessApiException($status===403?'bundle_not_allowed':'validation_failed',$error->getMessage(),$status);}
        $this->storeMutationCached($cacheKey,$requestHash,$result,86400);return$result;
    }

    public function revokePushDevice(string $registrationId,string $token,array $body,string $idempotency):array{
        if(!preg_match('/^dev_[A-Za-z0-9_-]{20,70}$/',$registrationId))throw new MercatoHeadlessApiException('not_found','Push registration not found.',404);[$ownerType,$ownerId]=$this->pushOwner($token,$body);$requestHash=hash('sha256',$registrationId.'|'.$ownerType.'|'.$ownerId);$cacheKey=$this->idemKey('push-revoke|'.$registrationId,$idempotency);$cached=$this->mutationCached($cacheKey,$requestHash);if($cached!==null)return$cached;
        try{$result=$this->commerce->pushNotificationService()->revoke($registrationId,$ownerType,$ownerId);}catch(WireException$error){throw new MercatoHeadlessApiException('not_found','Push registration not found.',404);}$this->storeMutationCached($cacheKey,$requestHash,$result,86400);return$result;
    }

    private function pushOwner(string $token,array $body):array{
        if(str_starts_with($token,'acct_'))return['account',(int)$this->authorizedAccount($token)->id];$orderId=trim((string)($body['order_id']??''));if($orderId==='')throw new MercatoHeadlessApiException('authentication_required','An account or exact order credential is required for push registration.',401,['order_id'=>'Include the order identifier for a guest order credential.']);$order=$this->authorizedOrder('mrc_api_order_id',$orderId,$token,'order:read');return['order',(int)$order->id];
    }

    private function issueAccountToken(User $user):array{
        $ttl=max(15,min(43200,(int)($this->commerce->headless_api_account_token_ttl_minutes??43200)))*60;$expires=time()+$ttl;$token='acct_'.rtrim(strtr(base64_encode(random_bytes(32)),'+/','-_'),'=');$payload=['version'=>1,'user_id'=>(int)$user->id,'expires_at'=>$expires,'scopes'=>['account:read','account:write','orders:read','checkout:create']];$this->wire('cache')->save($this->accountTokenCacheKey($token),json_encode($payload,JSON_UNESCAPED_SLASHES),$ttl);return['token'=>$token,'token_expires_at'=>gmdate(DATE_ATOM,$expires)];
    }

    private function authorizedAccount(string $token):User{
        if($token===''||!str_starts_with($token,'acct_'))throw new MercatoHeadlessApiException('authentication_required','Customer authentication is required.',401);$raw=$this->wire('cache')->get($this->accountTokenCacheKey($token));$data=$raw?json_decode((string)$raw,true):null;if(!is_array($data)||(int)($data['expires_at']??0)<time())throw new MercatoHeadlessApiException('authentication_expired','Customer authentication has expired.',401);$user=$this->wire('users')->get((int)($data['user_id']??0));if(!$user||!$user->id)throw new MercatoHeadlessApiException('authentication_required','Customer authentication is required.',401);try{$this->commerce->customerAccountService()->profile($user);}catch(WireException){throw new MercatoHeadlessApiException('authentication_required','Customer authentication is required.',401);}return$user;
    }

    private function favoritesForUser(User $user):array{
        $profile=$this->commerce->customerAccountService()->profile($user);$preferences=is_array($profile['preferences']??null)?$profile['preferences']:[];$ids=is_array($preferences['favorite_product_ids']??null)?$preferences['favorite_product_ids']:[];$products=[];$seen=[];foreach(array_slice($ids,0,500)as$id){$product=$this->findProduct((int)$id);if(!$product||isset($seen[$product->id]))continue;$seen[$product->id]=true;$products[]=$this->serializeProduct($product);}return['revision'=>(int)($profile['revision']??0),'products'=>$products];
    }

    private function accountTokenHash(string $token):string{return hash_hmac('sha256',$token,$this->secret());}
    private function accountTokenCacheKey(string $token):string{return'Mercato.api.account.'.$this->accountTokenHash($token);}
    private function accountOrderId(User $user,Page $order):string{return'aord_'.rtrim(strtr(base64_encode(hash_hmac('sha256',(int)$user->id.'|'.(int)$order->id,$this->secret(),true)),'+/','-_'),'=');}
    private function authorizedAccountOrder(User $user,string $id):Page{if($id===''||!str_starts_with($id,'aord_'))throw new MercatoHeadlessApiException('not_found','Resource not found.',404);$template=$this->safe((string)$this->commerce->order_template);foreach($this->wire('pages')->find("template=$template, include=all, mrc_customer_user_id=".(int)$user->id.', limit=10000')as$order)if(hash_equals($this->accountOrderId($user,$order),$id))return$order;throw new MercatoHeadlessApiException('not_found','Resource not found.',404);}

    private function serializeProduct(Page $p,string $marketId='default'):array{
        $market=$this->commerce->marketService()->resolve($marketId);$purchase=$this->commerce->getProductPurchasability($p);$images=[];if($p->hasField('mrc_images'))foreach($p->mrc_images as$image)$images[]=['url'=>$this->publicUrl((string)$image->httpUrl()),'width'=>(int)$image->width,'height'=>(int)$image->height,'alt'=>(string)($image->description?:$p->title)];$collections=[];if($p->hasField('mrc_collections'))foreach($p->mrc_collections as$c)$collections[]=['id'=>(int)$c->id,'name'=>(string)$c->name,'title'=>(string)$c->title];
        $definition=$this->commerce->variantService()->getDefinition($p);$base=$this->commerce->marketService()->applyToItem($p,['price'=>(float)$p->mrc_price,'shipping_price'=>$p->hasField('mrc_shipping_price')?(float)$p->mrc_shipping_price:0.0,'product_type'=>(string)($p->mrc_product_type?:'physical'),'stripe_price_id'=>(string)($p->mrc_stripe_price_id??'')],$market['id']);$variants=[];foreach($definition['variants']as$variant){try{$priced=$this->commerce->marketService()->applyToItem($p,$this->commerce->variantService()->hydrateItem($p,['quantity'=>1,'variant_id'=>(string)$variant['id']]),$market['id']);$variant['price']=(float)$priced['price'];$variant['price_adjustment']=0.0;if(isset($priced['stripe_price_id']))$variant['stripe_price_id']=(string)$priced['stripe_price_id'];$variants[]=$variant;}catch(WireException){continue;}}
        $data=['id'=>(int)$p->id,'name'=>(string)$p->name,'title'=>(string)$p->title,'url'=>$this->publicUrl((string)$p->httpUrl()),'description'=>trim(strip_tags((string)$p->mrc_description)),'sku'=>(string)$p->mrc_sku,'type'=>(string)($p->mrc_product_type?:'physical'),'price'=>(float)$base['price'],'currency'=>$market['currency'],'market_id'=>$market['id'],'tax_rate'=>round((float)$p->mrc_tax_rate,4),'images'=>$images,'collections'=>$collections,'purchasability'=>['purchasable'=>(bool)$purchase['ok']&&($definition['variants']===[]||$variants!==[]),'reason'=>(string)($purchase['first_error']??''),'stock_state'=>(string)($purchase['stock_label']??''),'available_stock'=>(int)($purchase['available_stock']??0),'stock_policy'=>(string)($purchase['stock_policy']??'')],'variant_options'=>$definition['options'],'variants'=>$variants];return $this->extend($data,'product',['page'=>$p,'market'=>$market]);
    }
    private function serializeCollection(Page $p):array{$images=[];if($p->hasField('mrc_images'))foreach($p->mrc_images as$image)$images[]=['url'=>$this->publicUrl((string)$image->httpUrl()),'alt'=>(string)($image->description?:$p->title)];return $this->extend(['id'=>(int)$p->id,'name'=>(string)$p->name,'title'=>(string)$p->title,'url'=>$this->publicUrl((string)$p->httpUrl()),'description'=>trim(strip_tags((string)$p->mrc_description)),'images'=>$images],'collection',['page'=>$p]);}
    private function matchesOptionFilters(array $product,array $filters):bool{if($filters===[])return true;foreach((array)($product['variants']??[])as$variant){if((string)($variant['status']??'active')!=='active')continue;$options=(array)($variant['options']??[]);$matches=true;foreach($filters as$key=>$value){if((string)($options[$key]??'')!==$value){$matches=false;break;}}if($matches)return true;}return false;}
    private function catalogFacets(iterable $pages,string $marketId='default'):array{$types=[];$collections=[];$availability=['available'=>0,'unavailable'=>0];$options=[];$minimum=null;$maximum=null;foreach($pages as$page){try{$product=$this->serializeProduct($page,$marketId);}catch(WireException){continue;}$type=(string)($product['type']??'physical');$types[$type]=($types[$type]??0)+1;$price=(float)($product['price']??0);$minimum=$minimum===null?$price:min($minimum,$price);$maximum=$maximum===null?$price:max($maximum,$price);$available=!empty($product['purchasability']['purchasable']);$availability[$available?'available':'unavailable']++;foreach((array)($product['collections']??[])as$collection){$id=(int)($collection['id']??0);if($id<=0)continue;if(!isset($collections[$id]))$collections[$id]=['id'=>$id,'title'=>(string)($collection['title']??''),'count'=>0];$collections[$id]['count']++;}foreach((array)($product['variant_options']??[])as$option){$id=(string)($option['id']??'');if($id==='')continue;if(!isset($options[$id]))$options[$id]=['id'=>$id,'label'=>(string)($option['label']??$id),'values'=>[]];foreach((array)($option['values']??[])as$value){$valueId=(string)($value['id']??'');if($valueId==='')continue;if(!isset($options[$id]['values'][$valueId]))$options[$id]['values'][$valueId]=['value'=>$valueId,'label'=>(string)($value['label']??$valueId),'count'=>0];$options[$id]['values'][$valueId]['count']++;}}}
        $typeItems=[];foreach(['physical'=>'Physical','service'=>'Services','digital'=>'Digital']as$value=>$label)if(isset($types[$value]))$typeItems[]=['value'=>$value,'label'=>$label,'count'=>$types[$value]];$optionItems=[];foreach($options as$option){$option['values']=array_values($option['values']);$optionItems[]=$option;}$currency=$this->commerce->marketService()->resolve($marketId)['currency'];return['types'=>$typeItems,'collections'=>array_values($collections),'availability'=>[['value'=>'available','label'=>'Available','count'=>$availability['available']],['value'=>'unavailable','label'=>'Unavailable','count'=>$availability['unavailable']]],'price'=>['min'=>round((float)($minimum??0),2),'max'=>round((float)($maximum??0),2),'currency'=>$currency],'options'=>$optionItems];}
    private function serializeCheckout(Page $o):array{return ['id'=>(string)$o->mrc_api_checkout_id,'payment_status'=>(string)$o->mrc_payment_status,'payment_complete'=>(int)$o->mrc_payment_complete===1,'order_status'=>$this->commerce->getDerivedOrderStatus($o),'reservation_expires_at'=>(string)$o->mrc_inventory_reserved_until,'total'=>round((float)$o->mrc_total_amount,2),'currency'=>(string)$o->mrc_currency,'updated_at'=>gmdate(DATE_ATOM,(int)$o->modified)];}
    private function serializeOrder(Page $o):array{$items=json_decode((string)$o->mrc_items,true);$cancellation=$this->commerce->getOrderCancellationRequest($o);$retry=$this->commerce->isOrderPaymentRetryAvailable($o);$data=['id'=>(string)$o->mrc_api_order_id,'invoice'=>(string)$o->mrc_invoice_number,'created_at'=>gmdate(DATE_ATOM,(int)$o->created),'payment_status'=>(string)$o->mrc_payment_status,'payment_complete'=>(int)$o->mrc_payment_complete===1,'order_status'=>$this->commerce->getDerivedOrderStatus($o),'payment'=>['method'=>(string)$o->mrc_payment_method,'status'=>(string)$o->mrc_payment_status,'complete'=>(int)$o->mrc_payment_complete===1,'retry_available'=>$retry,'instructions'=>(string)$o->mrc_payment_method==='bank-transfer'?(string)$this->commerce->bank_transfer_instructions:''],'fulfilment'=>['method'=>(string)$o->mrc_fulfilment_method,'status'=>(string)$o->mrc_fulfilment_status,'label'=>(string)$o->mrc_fulfilment_label,'tracking'=>(string)$o->mrc_fulfilment_tracking,'tracking_url'=>(string)$o->mrc_fulfilment_tracking_url],'items'=>is_array($items)?array_map(static fn($i)=>array_intersect_key($i,array_flip(['product_id','title','sku','variant_id','variant_options','price','quantity','product_type'])),$items):[],'totals'=>['subtotal'=>round((float)$o->mrc_subtotal_amount,2),'shipping'=>round((float)$o->mrc_shipping_amount,2),'discount'=>round((float)$o->mrc_discount_total,2),'tax'=>round((float)$o->mrc_tax_amount,2),'total'=>round((float)$o->mrc_total_amount,2),'currency'=>(string)$o->mrc_currency],'return_eligibility'=>$this->returnEligibility($o),'cancellation_eligibility'=>$this->commerce->getOrderCancellationEligibility($o),'cancellation_request'=>$cancellation?array_intersect_key($cancellation,array_flip(['request_id','status','reason','created_at'])):null,'links'=>['status'=>$this->publicUrl($this->commerce->getOrderStatusUrl($o)),'receipt'=>$this->publicUrl($this->commerce->getOrderReceiptUrl($o)),'payment'=>$retry?$this->publicUrl($this->commerce->getPaymentLinkUrl($o)):null]];return $this->extend($data,'order',['page'=>$o]);}
    private function returnEligibility(Page $order):array{$items=json_decode((string)$order->mrc_items,true);if((int)$order->mrc_payment_complete!==1)return['can_request'=>false,'message'=>'Returns become available after payment is completed.'];if(!is_array($items)||$items===[])return['can_request'=>false,'message'=>'This order has no returnable items.'];$status=(string)$order->mrc_fulfilment_status;if($status===MercatoFulfilmentStatus::RETURNED)return['can_request'=>false,'message'=>'This order has already been returned.'];$hasPhysical=false;foreach($items as$item)if((string)($item['product_type']??'physical')==='physical'){$hasPhysical=true;break;}$received=[MercatoFulfilmentStatus::FULFILLED,MercatoFulfilmentStatus::SHIPPED,MercatoFulfilmentStatus::COLLECTED,MercatoFulfilmentStatus::OUT_FOR_DELIVERY,MercatoFulfilmentStatus::DELIVERED];if($hasPhysical&&!in_array($status,$received,true))return['can_request'=>false,'message'=>'A return can be requested after the order has shipped or been collected.'];return['can_request'=>true,'message'=>'Select the items and quantities you want to return.'];}
    private function normalizeCartItems(mixed $items):array{if(!is_array($items))throw new MercatoHeadlessApiException('validation_failed','Cart items must be an array.',422,['items'=>'Use an array of product lines.']);if(count($items)>100)throw new MercatoHeadlessApiException('validation_failed','Cart has too many lines.',422,['items'=>'Use at most 100 lines.']);$out=[];foreach($items as$i=>$item){if(!is_array($item)||empty($item['product_id']))throw new MercatoHeadlessApiException('validation_failed','Cart items are invalid.',422,["items.$i.product_id"=>'A product is required.']);$quantity=(int)($item['quantity']??0);if($quantity<1||$quantity>999)throw new MercatoHeadlessApiException('validation_failed','Cart items are invalid.',422,["items.$i.quantity"=>'Use a quantity from 1 to 999.']);$product=$this->findProduct((int)$item['product_id']);if(!$product)throw new MercatoHeadlessApiException('validation_failed','Cart items are invalid.',422,["items.$i.product_id"=>'Product is unavailable.']);$variant=substr(trim((string)($item['variant_id']??'')),0,200);$key=(int)$product->id.'|'.$variant;if(isset($out[$key]))$out[$key]['quantity']=min(999,$out[$key]['quantity']+$quantity);else$out[$key]=['product_id'=>(int)$product->id,'variant_id'=>$variant,'quantity'=>$quantity];}return array_values($out);}
    private function serializeCart(array $record):array{$marketId=$this->marketId($record);$lines=[];$issues=[];foreach((array)($record['items']??[])as$item){$product=$this->findProduct((int)($item['product_id']??0));if(!$product){$issues[]=['code'=>'product_unavailable','product_id'=>(int)($item['product_id']??0),'message'=>'A product in this cart is no longer available.'];continue;}$quantity=max(1,(int)($item['quantity']??1));$variant=(string)($item['variant_id']??'');$purchase=$this->commerce->getProductPurchasability($product,$quantity,0.0,0,$variant!==''?$variant:null);$lineIssues=[];if(empty($purchase['ok']))$lineIssues[]=['code'=>'not_purchasable','message'=>(string)($purchase['first_error']??'This item is unavailable.')];try{$serialized=$this->serializeProduct($product,$marketId);}catch(WireException){$issues[]=['code'=>'market_price_unavailable','product_id'=>(int)$product->id,'message'=>'A product has no price in the selected market.'];continue;}$lines[]=['product'=>$serialized,'variant_id'=>$variant!==''?$variant:null,'quantity'=>$quantity,'validation_issues'=>$lineIssues];}$context=$this->commerce->marketService()->context($marketId);return['id'=>(string)$record['id'],'version'=>(int)$record['version'],'commerce_context'=>$context,'lines'=>$lines,'validation_issues'=>$issues,'expires_at'=>gmdate(DATE_ATOM,(int)$record['expires_at']),'updated_at'=>gmdate(DATE_ATOM,(int)$record['updated_at'])];}
    private function cartRecordKey(string $id):string{return'Mercato.api.cart.'.hash_hmac('sha256',$id,$this->secret());}
    private function storeCartRecord(array $record):void{$ttl=max(300,(int)$record['expires_at']-time());$this->wire('cache')->save($this->cartRecordKey((string)$record['id']),json_encode($record,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE),$ttl);}
    private function authorizedCart(string $id,string $token):array{if($id===''||$token==='')throw new MercatoHeadlessApiException('not_found','Resource not found.',404);$raw=$this->wire('cache')->get($this->cartRecordKey($id));$record=$raw?json_decode((string)$raw,true):null;if(!is_array($record)||!hash_equals((string)($record['id']??''),$id))throw new MercatoHeadlessApiException('not_found','Resource not found.',404);if((int)($record['expires_at']??0)<time())throw new MercatoHeadlessApiException('token_expired','Cart credential expired.',410);if(!hash_equals((string)($record['token_hash']??''),$this->tokenHash($token)))throw new MercatoHeadlessApiException('not_found','Resource not found.',404);return$record;}
    private function publicQuote(array $q):array{return array_intersect_key($q,array_flip(['items','item_count','market_id','commerce_context','currency','subtotal','shipping','discount','tax','total','discount_code','discount_valid','fulfilment_method','fulfilment_label','fulfilment_methods','requires_payment']));}
    private function requestedItems(mixed $items):array{if(!is_array($items)||$items===[])throw new MercatoHeadlessApiException('validation_failed','At least one item is required.',422,['items'=>'Add at least one product.']);$out=[];foreach($items as$i=>$item){if(!is_array($item)||empty($item['product_id'])||(float)($item['quantity']??0)<=0)throw new MercatoHeadlessApiException('validation_failed','Items are invalid.',422,["items.$i"=>'product_id and positive quantity are required.']);$product=$this->findProduct((int)$item['product_id']);if(!$product)throw new MercatoHeadlessApiException('validation_failed','Items are invalid.',422,["items.$i.product_id"=>'Product is unavailable.']);$out[]=['product_id'=>(int)$product->id,'id'=>(int)$product->id,'quantity'=>(float)$item['quantity'],'variant_id'=>(string)($item['variant_id']??'')];}return$out;}
    private function validateCheckoutInput(array $c,array $o):array{$e=[];foreach(['first_name','last_name']as$k)if(trim((string)($c[$k]??''))==='')$e["customer.$k"]='Required.';$email=(string)$this->wire('sanitizer')->email((string)($c['email']??''));if($email==='')$e['customer.email']='Valid email required.';if(trim((string)($o['payment_method']??''))==='')$e['options.payment_method']='Required.';if($this->commerce->getPolicyPages()->count()>0&&empty($o['policy_accepted']))$e['options.policy_accepted']='Store policies must be accepted.';return$e;}
    private function marketId(array $input):string{try{return(string)$this->commerce->marketService()->resolve((string)($input['market_id']??'default'))['id'];}catch(WireException $e){throw new MercatoHeadlessApiException('market_unavailable',$e->getMessage(),422,['market_id'=>'Choose an enabled store market.']);}}
    private function activateMarketLanguage(string $marketId):void{try{$market=$this->commerce->marketService()->resolve($marketId);$code=str_replace('_','-',strtolower((string)($market['language']??'')));$languages=$this->wire('languages');$user=$this->wire('user');if(!$languages||!$user||!method_exists($languages,'get'))return;$candidates=array_values(array_unique(array_filter([$code,explode('-',$code)[0]??''])));foreach($candidates as$candidate){$language=$languages->get('name='.$this->safe($candidate));if($language instanceof Page&&$language->id){$user->language=$language;return;}}}catch(\Throwable){}}
    private function paymentInstructions(Page $o,array $p,string $redirect):array{if(!empty($p['stripe_client_secret']))return['mode'=>'client_confirmation','provider'=>'stripe','client_secret'=>(string)$p['stripe_client_secret'],'confirmation'=>'native_sdk','return_url'=>$this->returnUrl($o)];if((string)$o->mrc_payment_method==='bank-transfer')return['mode'=>'offline','provider'=>'bank-transfer','instructions'=>(string)$this->commerce->bank_transfer_instructions];if($redirect!==''){if(!empty($this->commerce->production)&&strtolower((string)parse_url($redirect,PHP_URL_SCHEME))!=='https')throw new MercatoHeadlessApiException('invalid_payment_redirect','Payment provider returned a non-HTTPS redirect.',502);return['mode'=>'redirect','provider'=>(string)$o->mrc_payment_method,'url'=>$redirect,'return_url'=>$this->returnUrl($o)];}return['mode'=>'processing','provider'=>(string)$o->mrc_payment_method];}
    private function returnUrl(Page $o):string{return $this->publicUrl(rtrim($this->commerce->getHttpRoot(),'/').'/api/mercato/v1/checkouts/'.rawurlencode((string)$o->mrc_api_checkout_id));}
    private function paymentContext(array $p):array{return array_intersect_key($p,array_flip(['payment_attempt_id','payment_attempt_idempotency_key','stripe_payment_intent_id','stripe_client_secret','mollie_payment_id','payment_id']));}
    private function authorizedOrder(string $field,string $id,string $token,string $scope):Page{if($id===''||$token==='')throw new MercatoHeadlessApiException('not_found','Resource not found.',404);$o=$this->wire('pages')->get('template='.$this->safe((string)$this->commerce->order_template).', include=all, '.$field.'='.$this->safe($id));if(!$o||!$o->id)throw new MercatoHeadlessApiException('not_found','Resource not found.',404);$d=$this->details($o);if((int)($d['expires_at']??0)<time())throw new MercatoHeadlessApiException('token_expired','Resource credential expired.',410);if(!hash_equals((string)($d['token_hash']??''),$this->tokenHash($token))||!in_array($scope,(array)($d['scopes']??[]),true))throw new MercatoHeadlessApiException('not_found','Resource not found.',404);return$o;}
    private function token(array $h):string{$auth=(string)($h['authorization']??'');if(preg_match('/^Bearer\s+(.+)$/i',$auth,$m))return trim($m[1]);return trim((string)($h['x-mercato-token']??''));}
    private function requireIdempotency(array $h):string{$key=trim((string)($h['idempotency-key']??''));if(!preg_match('/^[A-Za-z0-9._:-]{8,128}$/',$key))throw new MercatoHeadlessApiException('idempotency_key_required','A valid Idempotency-Key header is required.',400,['Idempotency-Key'=>'Use 8-128 safe characters.']);return$key;}
    private function cached(string $key,string $hash):?array{$v=$this->wire('cache')->get($key);if(!$v)return null;$d=json_decode((string)$v,true);if(!is_array($d))return null;if(!hash_equals((string)$d['request_hash'],$hash))throw new MercatoHeadlessApiException('idempotency_conflict','Idempotency key was reused with different input.',409);$response=(array)$d['response'];$response['token']=$this->idempotentToken($key,$hash);return$response;}
    private function storeCached(string $key,string $hash,array $response,int $ttl):void{unset($response['token']);$this->wire('cache')->save($key,json_encode(['request_hash'=>$hash,'response'=>$response],JSON_UNESCAPED_SLASHES),max(300,$ttl));}
    private function mutationCached(string $key,string $hash):?array{$raw=$this->wire('cache')->get($key);if(!$raw)return null;$data=json_decode((string)$raw,true);if(!is_array($data))return null;if(!hash_equals((string)($data['request_hash']??''),$hash))throw new MercatoHeadlessApiException('idempotency_conflict','Idempotency key was reused with different input.',409);return(array)($data['response']??[]);}
    private function storeMutationCached(string $key,string $hash,array $response,int $ttl):void{$this->wire('cache')->save($key,json_encode(['request_hash'=>$hash,'response'=>$response],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE),max(300,$ttl));}
    private function idempotencyLock(string $key):mixed{$dir=rtrim((string)$this->wire('config')->paths->cache,'/').'/Mercato-headless-locks/';if(!is_dir($dir)&&!$this->wire('files')->mkdir($dir,true))throw new MercatoHeadlessApiException('idempotency_unavailable','Checkout locking is temporarily unavailable.',503);$handle=fopen($dir.hash('sha256',$key).'.lock','c');if($handle===false||!flock($handle,LOCK_EX)){if(is_resource($handle))fclose($handle);throw new MercatoHeadlessApiException('idempotency_unavailable','Checkout locking is temporarily unavailable.',503);}return$handle;}
    private function releaseIdempotencyLock(mixed $handle):void{if(is_resource($handle)){flock($handle,LOCK_UN);fclose($handle);}}
    private function idemKey(string $scope,string $key):string{return'Mercato.api.idem.'.hash_hmac('sha256',$scope.'|'.$key,$this->secret());}
    private function tokenHash(string $token):string{return hash_hmac('sha256',$token,$this->secret());}private function secret():string{return(string)($this->wire('config')->userAuthSalt?:__FILE__);}private function opaque(string $prefix,int $bytes=32):string{return$prefix.'_'.rtrim(strtr(base64_encode(random_bytes($bytes)),'+/','-_'),'=');}private function idempotentToken(string $key,string $hash):string{return'tok_'.rtrim(strtr(base64_encode(hash_hmac('sha256',$key.'|'.$hash,$this->secret(),true)),'+/','-_'),'=');}
    private function encryptContext(array $context):string{$iv=random_bytes(12);$tag='';$cipher=openssl_encrypt(json_encode($context,JSON_UNESCAPED_SLASHES),'aes-256-gcm',hash('sha256',$this->secret(),true),OPENSSL_RAW_DATA,$iv,$tag);if($cipher===false)throw new WireException('Could not protect API payment context.',500);return rtrim(strtr(base64_encode($iv.$tag.$cipher),'+/','-_'),'=');}
    private function decryptContext(string $encoded):array{if($encoded==='')return[];$raw=base64_decode(strtr($encoded,'-_','+/'),true);if($raw===false||strlen($raw)<29)throw new MercatoHeadlessApiException('invalid_checkout_state','Checkout payment context is unavailable.',409);$iv=substr($raw,0,12);$tag=substr($raw,12,16);$plain=openssl_decrypt(substr($raw,28),'aes-256-gcm',hash('sha256',$this->secret(),true),OPENSSL_RAW_DATA,$iv,$tag);$data=$plain!==false?json_decode($plain,true):null;if(!is_array($data))throw new MercatoHeadlessApiException('invalid_checkout_state','Checkout payment context is unavailable.',409);return$data;}
    private function canonical(array $v):string{$sort=function(&$x)use(&$sort){if(!is_array($x))return;foreach($x as&$y)$sort($y);if(!array_is_list($x))ksort($x);};$sort($v);return(string)json_encode($v,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);}
    private function details(Page $o):array{$d=json_decode((string)$o->mrc_api_details,true);return is_array($d)?$d:[];}private function safe(string $v):string{return(string)$this->wire('sanitizer')->selectorValue($v);}
    private function publicUrl(string $url):string{
        if($url==='')return'';$parts=parse_url($url);if(!is_array($parts))return$url;
        $configured=parse_url((string)$this->commerce->getHttpRoot(),PHP_URL_HOST);$source=strtolower((string)($parts['host']??''));
        if($source!==''&&$configured!==null&&!hash_equals(strtolower((string)$configured),$source)&&!str_ends_with($source,'.test'))return$url;
        $forwardedHost=trim(explode(',',(string)($_SERVER['HTTP_X_FORWARDED_HOST']??''))[0]);$host=$forwardedHost!==''?$forwardedHost:(string)($_SERVER['HTTP_HOST']??'');
        if(!preg_match('/^[A-Za-z0-9.-]+(?::\d+)?$/',$host))return$url;
        $forwardedProto=strtolower(trim(explode(',',(string)($_SERVER['HTTP_X_FORWARDED_PROTO']??''))[0]));$scheme=in_array($forwardedProto,['http','https'],true)?$forwardedProto:(!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off'?'https':'http');
        $path=(string)($parts['path']??'/');$query=isset($parts['query'])?'?'.$parts['query']:'';$fragment=isset($parts['fragment'])?'#'.$parts['fragment']:'';
        return $scheme.'://'.$host.$path.$query.$fragment;
    }
    private function findProduct(string|int $id):?Page{$p=$this->findPage((string)($this->commerce->product_template?:'mrc-product'),$id);return$p&&(!$p->hasField('mrc_product_status')||(string)$p->mrc_product_status==='active')?$p:null;}private function findPage(string $template,string|int $id):?Page{$selector='template='.$this->safe($template).', status<'.Page::statusHidden.', ';$selector.=ctype_digit((string)$id)?'id='.(int)$id:'name='.$this->safe((string)$id);$p=$this->wire('pages')->get($selector);return$p&&$p->id?$p:null;}
    private function pagination(int $p,int $l,int $t):array{return['page'=>$p,'limit'=>$l,'total'=>$t,'pages'=>(int)ceil($t/$l),'has_next'=>$p*$l<$t];}
    private function extend(array $resource,string $type,array $context=[]):array{$hooked=$this->commerce->headlessApiResource($resource,$type,$context);return is_array($hooked)?$hooked:$resource;}
}
