<?php
namespace ProcessWire;

final class MercatoAnalyticsService extends Wire {
    private const SESSION_CONSENT = 'mrc_analytics_consent';
    public function __construct(private Mercato $commerce) { parent::__construct(); }

    public function consent(): array { $stored=$this->wire('session')->get(self::SESSION_CONSENT);$default=(string)($this->commerce->analytics_default_consent??'denied')==='granted';return ['essential'=>true,'analytics'=>is_array($stored)?!empty($stored['analytics']):$default,'marketing'=>is_array($stored)?!empty($stored['marketing']):false,'updated_at'=>is_array($stored)?(string)($stored['updated_at']??''):'']; }
    public function setConsent(array $categories): array { $value=['essential'=>true,'analytics'=>!empty($categories['analytics']),'marketing'=>!empty($categories['marketing']),'updated_at'=>date(DATE_ATOM)];$this->wire('session')->set(self::SESSION_CONSENT,$value);$this->audit('consent_updated',['analytics'=>$value['analytics'],'marketing'=>$value['marketing']]);return $value; }

    public function track(string $name,array $payload=[],?Page $order=null,string $businessId=''): array {
        if(empty($this->commerce->analytics_enabled))return ['status'=>'disabled'];$payload['event_id']=$businessId!==''?$businessId:($payload['event_id']??hash('sha256',$name.'|'.microtime(true).'|'.random_int(1,PHP_INT_MAX)));$event=MercatoAnalyticsSchema::normalize($name,$payload,(string)($this->commerce->analytics_order_identifier??'invoice'));
        if($order&&$order->id){return $this->withOrderLock((int)$order->id,function()use($order,$event){$fresh=$this->wire('pages')->getById((int)$order->id,['cache'=>false])->first();$state=$this->orderState($fresh);if(isset($state['events'][$event['event_id']]))return ['status'=>'duplicate','event'=>$state['events'][$event['event_id']]['event']];$state['consent']=$this->consent();$state['events'][$event['event_id']]=['event'=>$event,'delivered'=>[],'created_at'=>date(DATE_ATOM)];$this->saveOrderState($fresh,$state);return $this->dispatchOrderEvent($fresh,$event['event_id']);});}
        if(empty($this->consent()['analytics']))return ['status'=>'consent_denied','event'=>$event];return $this->dispatchStandalone($event);
    }

    public function trackOrder(Page $order,string $name,array $extra=[],string $businessId=''): array { $payload=$this->orderPayload($order,$name,$extra);$businessId=$businessId?:$name.':'.(int)$order->id;return $this->track($name,$payload,$order,$businessId); }
    public function consumeOrderEvent(Page $order,string $name,string $adapter='data_layer'): array { $enabled=array_map('strval',(array)($this->commerce->analytics_adapters??['data_layer','first_party']));if(!in_array($adapter,$enabled,true))return [];return $this->withOrderLock((int)$order->id,function()use($order,$name,$adapter){$fresh=$this->wire('pages')->getById((int)$order->id,['cache'=>false])->first();$state=$this->orderState($fresh);foreach($state['events']??[] as $id=>$row){if(($row['event']['event']??'')!==$name||!empty($row['delivered'][$adapter]))continue;$consent=(array)($state['consent']??$this->consent());if(empty($consent['analytics'])&&empty($this->consent()['analytics']))return [];if(!empty($this->consent()['analytics'])&&empty($consent['analytics'])){$state['consent']['analytics']=true;$this->saveOrderState($fresh,$state);$this->dispatchOrderEvent($fresh,(string)$id);$state=$this->orderState($fresh);}$event=(array)$row['event'];$state['events'][$id]['delivered'][$adapter]=['at'=>date(DATE_ATOM),'status'=>'sent'];$this->saveOrderState($fresh,$state);$this->audit('analytics_dispatched',['adapter'=>$adapter,'event_name'=>$name,'event_id'=>$id,'order_id'=>(int)$fresh->id]);return $event;}return [];}); }

    public function orderPayload(Page $order,string $name,array $extra=[]): array { $items=json_decode((string)$order->mrc_items,true);$normalized=[];foreach(is_array($items)?$items:[] as $item){if(!is_array($item))continue;$normalized[]=['product_id'=>(string)($item['product_id']??$item['id']??''),'variant_id'=>(string)($item['variant_id']??''),'sku'=>(string)($item['sku']??''),'name'=>(string)($item['title']??''),'price'=>round((float)($item['price']??0),2),'quantity'=>max(1,(int)($item['quantity']??1))];}$total=$order->hasField('mrc_total_amount')?(float)$order->mrc_total_amount:$this->commerce->orderRepository()->getTotalAmount($order);return ['order_identifier'=>(string)($order->mrc_invoice_number?:$order->id),'currency'=>MercatoCurrency::normalizeCode((string)($order->mrc_currency?:$this->commerce->currency)),'value'=>round($name==='refund'?(float)($extra['refund_amount']??$extra['amount']??0):$total,2),'tax'=>round((float)($order->mrc_tax_amount??0),2),'shipping'=>round((float)($order->mrc_shipping_amount??0),2),'discount'=>round((float)($order->mrc_discount_total??0),2),'coupon'=>(string)($order->mrc_discount_code??''),'items'=>$normalized]+$extra; }
    public function adapters(): array { $adapters=['first_party'=>new MercatoFirstPartyAnalyticsAdapter()];$adapters['first_party']->setWire($this->wire());$hooked=$this->commerce->analyticsAdapters($adapters);return is_array($hooked)?$hooked:$adapters; }
    public function diagnostics(int $limit=20): array { $path=rtrim((string)$this->wire('config')->paths->logs,'/').'/mercato-analytics.txt';$rows=[];foreach(array_reverse(array_slice(is_readable($path)?(file($path,FILE_IGNORE_NEW_LINES|FILE_SKIP_EMPTY_LINES)?:[]):[],-max(1,min(100,$limit))))as$line){$json=strstr((string)$line,'{');$row=$json?json_decode($json,true):null;if(is_array($row))$rows[]=MercatoAnalyticsSchema::sanitize($row);}return ['enabled'=>!empty($this->commerce->analytics_enabled),'configured_adapters'=>(array)($this->commerce->analytics_adapters??[]),'registered_adapters'=>array_keys($this->adapters()),'consent'=>$this->consent(),'recent'=>$rows]; }

    private function dispatchOrderEvent(Page $order,string $eventId): array { $state=$this->orderState($order);$row=$state['events'][$eventId]??null;if(!is_array($row))return ['status'=>'missing'];$consent=(array)($state['consent']??[]);if(empty($consent['analytics']))return ['status'=>'pending_consent','event'=>$row['event']];$enabled=array_map('strval',(array)($this->commerce->analytics_adapters??['data_layer','first_party']));foreach($this->adapters()as$key=>$adapter){if(!in_array($key,$enabled,true)||!$adapter instanceof MercatoAnalyticsAdapterInterface||!empty($row['delivered'][$key]))continue;try{$result=$adapter->dispatch($row['event']);$state['events'][$eventId]['delivered'][$key]=['at'=>date(DATE_ATOM),'status'=>!empty($result['accepted'])?'sent':'failed'];}catch(\Throwable $e){$state['events'][$eventId]['delivered'][$key]=['at'=>date(DATE_ATOM),'status'=>'failed'];$this->audit('adapter_failed',['adapter'=>$key,'event_id'=>$eventId,'error_class'=>get_class($e)]);}}$this->saveOrderState($order,$state);return ['status'=>'processed','event'=>$row['event']]; }
    private function dispatchStandalone(array $event): array { $enabled=array_map('strval',(array)($this->commerce->analytics_adapters??['data_layer','first_party']));$results=[];foreach($this->adapters()as$key=>$adapter){if(!in_array($key,$enabled,true)||!$adapter instanceof MercatoAnalyticsAdapterInterface)continue;try{$results[$key]=$adapter->dispatch($event);}catch(\Throwable $e){$results[$key]=['accepted'=>false];$this->audit('adapter_failed',['adapter'=>$key,'event_id'=>$event['event_id'],'error_class'=>get_class($e)]);}}return ['status'=>'processed','event'=>$event,'adapters'=>$results]; }
    private function orderState(Page $order): array { $state=json_decode((string)($order->mrc_analytics_details??''),true);return is_array($state)?$state:['schema'=>MercatoAnalyticsSchema::VERSION,'consent'=>$this->consent(),'events'=>[]]; }
    private function saveOrderState(Page $order,array $state): void { if(!$order->hasField('mrc_analytics_details'))return;$saved=$this->wire('user');$super=$this->wire('users')->get('template=user, roles.name=superuser');if($super&&$super->id)$this->wire('users')->setCurrentUser($super);try{$order->of(false);$order->mrc_analytics_details=json_encode($state,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);$this->wire('pages')->save($order,['noHooks'=>true]);}finally{$this->wire('users')->setCurrentUser($saved);} }
    private function audit(string $event,array $data): void { $log=new MercatoEventLog('mercato-analytics');$log->setWire($this->wire());$log->record(['event'=>$event,'status'=>'recorded']+MercatoAnalyticsSchema::sanitize($data),$event); }
    private function withOrderLock(int $orderId,callable $callback): mixed { $directory=rtrim((string)$this->wire('config')->paths->cache,'/').'/MercatoAnalytics/';if(!is_dir($directory))$this->wire('files')->mkdir($directory,true);$handle=fopen($directory.'order-'.$orderId.'.lock','c');if(!$handle||!flock($handle,LOCK_EX))throw new WireException('Could not lock analytics event state.');try{return $callback();}finally{flock($handle,LOCK_UN);fclose($handle);} }
}
