<?php
namespace ProcessWire;

/** @var Mercato $commerce */
$commerce = $modules->get('Mercato');
if (($templateOverride = $commerce->getStorefrontTemplateOverridePath('mrc-account')) !== '') { include $templateOverride; return; }
require_once __DIR__ . '/mrc-storefront.php';
$accounts = $commerce->customerAccountService();
$ui = $commerce->getFrontendUiClasses(); $isVanilla = $commerce->getFrontendFramework() === 'vanilla';
$csrf = $session->CSRF ?? null; $csrfInput = ($csrf && method_exists($csrf, 'renderInput')) ? (string) $csrf->renderInput() : '';
$validCsrf = static fn(): bool => !$csrf || !method_exists($csrf, 'hasValidToken') || (bool) $csrf->hasValidToken();
$message = ''; $error = ''; $action = strtolower((string) ($input->get->text('action') ?: $input->post->text('mrc_account_action')));
$isCustomer = !$user->isGuest() && $user->hasRole('mercato-customer') && $accounts->isVerified($user);

try {
    if ($action === 'verify' && $input->get->int('user')) $message = $accounts->verify($input->get->int('user'), $input->get->text('token')) ? 'Email verified. You can sign in.' : 'This verification link is invalid or expired.';
    elseif ($action === 'claim' && $isCustomer) { $order = $pages->get($input->get->int('order')); $message = $order->id && $accounts->claimGuestOrder($user, $order, $input->get->text('token')) ? 'The guest order is now attached to your account.' : 'This claim link is invalid or expired.'; }
    elseif ($input->post->text('mrc_account_action') !== '') {
        if (!$validCsrf()) throw new WireException('Form session expired. Reload and try again.', 403);
        if ($action === 'register') $message = (string) $accounts->register($input->post->email('email'), (string) $input->post('password'), ['first_name' => $input->post->text('first_name'), 'last_name' => $input->post->text('last_name')])['message'];
        elseif ($action === 'login') { $result = $accounts->login($input->post->email('email'), (string) $input->post('password'), (string) ($_SERVER['REMOTE_ADDR'] ?? '')); if (empty($result['ok'])) throw new WireException((string) $result['message']); $session->redirect($page->url); }
        elseif ($action === 'logout') { $accounts->logout(); $session->redirect($page->url); }
        elseif ($action === 'request-reset') $message = (string) $accounts->requestPasswordReset($input->post->email('email'))['message'];
        elseif ($action === 'reset') { if (!$accounts->resetPassword($input->post->int('user'), $input->post->text('token'), (string) $input->post('password'))) throw new WireException('This reset link is invalid, expired, or the password is too short.'); $message = 'Password changed. Sign in again.'; }
        elseif ($action === 'profile' && !$user->isGuest()) {
            $address = ['label' => 'Primary', 'address' => $input->post->text('address'), 'city' => $input->post->text('city'), 'zip' => $input->post->text('zip'), 'country' => strtoupper($input->post->text('country'))];
            $accounts->updateProfile($user, ['first_name' => $input->post->text('first_name'), 'last_name' => $input->post->text('last_name'), 'phone' => $input->post->text('phone'), 'addresses' => [array_filter($address)], 'preferences' => ['commerce_email' => (bool) $input->post->int('commerce_email')]], $input->post->int('revision')); $message = 'Profile saved.';
        } elseif ($action === 'request-claim' && !$user->isGuest()) { $order = $commerce->orderRepository()->findByOrderReference($input->post->text('order_reference')); $result = $order ? $accounts->requestGuestOrderClaim($user, $order) : ['message' => MercatoAccountPolicy::GENERIC_AUTH_MESSAGE]; $message = (string) $result['message']; }
        elseif ($action === 'delete-account' && !$user->isGuest()) { $email = (string) $user->email; $commerce->privacyService()->deleteCustomerData($email, 'Customer self-service deletion request', (string) $commerce->privacy_policy_version); $accounts->logout(); $message = 'Account data was anonymized where legally and operationally permitted.'; }
    }
} catch (\Throwable $e) { $error = $e->getMessage(); }

$profile = $isCustomer && $accounts->isEnabled() ? $accounts->profile($user) : [];
$pageNum = max(1, $input->get->int('page')); $orders = $isCustomer && $accounts->isEnabled() ? $accounts->findOrders($user, $pageNum) : new PageArray();
$quotes = $isCustomer && $accounts->isEnabled() ? $commerce->quoteService()->findForCustomer($user, 100) : new PageArray();
$primary = (array) (($profile['addresses'][0] ?? [])); $seoHead = $commerce->seoService()->render($page, ['private' => true]);
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><?= $seoHead ?><?= mrc_storefront_assets($isVanilla) ?><?= $commerce->renderFrontendFrameworkAssets() ?></head><body class="<?= $ui['body'] ?>">
<?= mrc_storefront_header($commerce, $pages, $config, $sanitizer) ?><main class="<?= $ui['shell'] ?>"><section class="<?= $ui['panel'] ?>"><span class="<?= $ui['kicker'] ?>">Private account</span><h1>My account</h1>
<?php if ($message): ?><p class="<?= $ui['message'] ?>"><?= $sanitizer->entities($message) ?></p><?php endif; ?><?php if ($error): ?><p class="<?= $ui['error'] ?>"><?= $sanitizer->entities($error) ?></p><?php endif; ?>
<?php if (!$accounts->isEnabled()): ?><p>Customer accounts are disabled. Guest checkout and signed order links remain available.</p>
<?php elseif (!$isCustomer && !$user->isGuest()): ?><p>This signed-in staff/user session is not a verified customer account. Use a separate customer session to access storefront account data.</p>
<?php elseif ($user->isGuest()): ?>
<div class="<?= $ui['grid'] ?>"><form method="post" class="<?= $ui['form'] ?>"><?= $csrfInput ?><input type="hidden" name="mrc_account_action" value="login"><h2>Sign in</h2><label>Email<input class="<?= $ui['input'] ?>" type="email" name="email" required autocomplete="email"></label><label>Password<input class="<?= $ui['input'] ?>" type="password" name="password" required autocomplete="current-password"></label><button class="<?= $ui['button'] ?>">Sign in</button></form>
<form method="post" class="<?= $ui['form'] ?>"><?= $csrfInput ?><input type="hidden" name="mrc_account_action" value="register"><h2>Create account</h2><label>First name<input class="<?= $ui['input'] ?>" name="first_name" required></label><label>Last name<input class="<?= $ui['input'] ?>" name="last_name" required></label><label>Email<input class="<?= $ui['input'] ?>" type="email" name="email" required autocomplete="email"></label><label>Password (10+ characters)<input class="<?= $ui['input'] ?>" type="password" name="password" minlength="10" required autocomplete="new-password"></label><button class="<?= $ui['button'] ?>">Create account</button></form></div>
<form method="post" class="<?= $ui['form'] ?>"><?= $csrfInput ?><input type="hidden" name="mrc_account_action" value="request-reset"><h2>Reset password</h2><label>Email<input class="<?= $ui['input'] ?>" type="email" name="email" required></label><button class="<?= $ui['buttonSecondary'] ?>">Send reset link</button></form>
<?php if ($action === 'reset'): ?><form method="post" class="<?= $ui['form'] ?>"><?= $csrfInput ?><input type="hidden" name="mrc_account_action" value="reset"><input type="hidden" name="user" value="<?= $input->get->int('user') ?>"><input type="hidden" name="token" value="<?= $sanitizer->entities($input->get->text('token')) ?>"><label>New password<input class="<?= $ui['input'] ?>" type="password" name="password" minlength="10" required></label><button class="<?= $ui['button'] ?>">Set new password</button></form><?php endif; ?>
<?php else: ?>
<form method="post" class="<?= $ui['form'] ?>"><?= $csrfInput ?><input type="hidden" name="mrc_account_action" value="logout"><button class="<?= $ui['buttonSecondary'] ?>">Sign out</button></form>
<form method="post" class="<?= $ui['form'] ?>"><?= $csrfInput ?><input type="hidden" name="mrc_account_action" value="profile"><input type="hidden" name="revision" value="<?= (int) $profile['revision'] ?>"><h2>Profile and primary address</h2><div class="<?= $ui['grid'] ?>"><?php foreach (['first_name'=>'First name','last_name'=>'Last name','phone'=>'Phone','address'=>'Address','city'=>'City','zip'=>'Postal code','country'=>'Country'] as $name=>$label): $value = array_key_exists($name,$profile) ? $profile[$name] : ($primary[$name] ?? ''); ?><label><?= $label ?><input class="<?= $ui['input'] ?>" name="<?= $name ?>" value="<?= $sanitizer->entities((string) $value) ?>"></label><?php endforeach; ?></div><label><input type="checkbox" name="commerce_email" value="1" <?= !empty($profile['preferences']['commerce_email']) ? 'checked' : '' ?>> Receive optional commerce updates</label><button class="<?= $ui['button'] ?>">Save profile</button></form>
<h2>Order history</h2><?php if (!$orders->count()): ?><p>No orders are attached to this account.</p><?php else: ?><div class="mrc-table-wrap"><table class="mrc-table"><thead><tr><th>Order</th><th>Status</th><th>Fulfilment</th><th>Total</th><th>Links</th></tr></thead><tbody><?php foreach ($orders as $order): ?><tr><td><?= $sanitizer->entities((string) ($order->mrc_invoice_number ?: $order->title)) ?></td><td><?= $sanitizer->entities((string) $order->mrc_payment_status) ?></td><td><?= $sanitizer->entities((string) $order->mrc_fulfilment_status) ?></td><td><?= $sanitizer->entities($commerce->formatPrice($commerce->orderRepository()->getTotalAmount($order))) ?></td><td><a href="<?= $sanitizer->entities($commerce->getOrderStatusUrl($order)) ?>">Details & downloads</a> · <a href="<?= $sanitizer->entities($commerce->getOrderReceiptUrl($order)) ?>">Receipt</a></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?>
<p><?php if ($pageNum > 1): ?><a href="?page=<?= $pageNum - 1 ?>">Previous</a><?php endif; ?> <?php if ($orders->count() >= (int) $commerce->account_orders_per_page): ?><a href="?page=<?= $pageNum + 1 ?>">Next</a><?php endif; ?></p>
<h2>Quote records</h2><p><?= $quotes->count() ?> quote request(s) are attached to this account. <a href="<?= $config->urls->root ?>my-quotes/">Open quotes</a>.</p>
<?php if (!empty($commerce->account_claim_guest_orders)): ?><form method="post" class="<?= $ui['form'] ?>"><?= $csrfInput ?><input type="hidden" name="mrc_account_action" value="request-claim"><h2>Claim a guest order</h2><label>Invoice number<input class="<?= $ui['input'] ?>" name="order_reference" required></label><button class="<?= $ui['buttonSecondary'] ?>">Send claim confirmation</button></form><?php endif; ?>
<form method="post" class="<?= $ui['form'] ?>" onsubmit="return confirm('Review retention blockers and anonymize this account?')"><?= $csrfInput ?><input type="hidden" name="mrc_account_action" value="delete-account"><h2>Delete account data</h2><p>Financial and legally required order records are retained and anonymized under the configured privacy policy.</p><button class="<?= $ui['buttonSecondary'] ?>">Request account deletion</button></form>
<?php endif; ?></section></main><?= mrc_storefront_footer($commerce, $pages, $config, $sanitizer) ?></body></html>
