<?php
namespace ProcessWire;

trait ProcessMercatoOrderFulfilmentActions {

    protected function handleReservationCleanup(Mercato $commerce): array {
        if ((string) $this->wire('input')->post->text('mrc_cleanup_reservations') !== '1') {
            return [];
        }
        if (!$this->hasCommercePermission(self::PERMISSION_MANAGE_INVENTORY)) {
            return $this->permissionError(self::PERMISSION_MANAGE_INVENTORY, $this->_('Reservation cleanup was blocked.'));
        }

        if (!$this->validateCsrf()) {
            return [
                'summary' => $this->_('Reservation cleanup was blocked. Refresh the page and try again.'),
                'errors' => [$this->_('CSRF token validation failed.')],
            ];
        }

        $count = $commerce->orderRepository()->cleanupExpiredReservations();
        $summary = sprintf($this->_('Released %d expired reservation(s).'), $count);
        $this->wire('session')->message($summary);

        return [
            'summary' => $summary,
            'released' => $count,
            'errors' => [],
        ];
    }

    protected function handleDemoOrderCreation(Mercato $commerce): array {
        if ((string) $this->wire('input')->post->text('mrc_create_demo_order') !== '1') {
            return [];
        }
        if (!$this->hasCommercePermission(self::PERMISSION_LAUNCH_TOOLS)) {
            return $this->permissionError(self::PERMISSION_LAUNCH_TOOLS, $this->_('Demo order creation was blocked.'));
        }

        if (!$this->validateCsrf()) {
            return [
                'summary' => $this->_('Demo order creation was blocked. Refresh the page and try again.'),
                'errors' => [$this->_('CSRF token validation failed.')],
            ];
        }

        if (!empty($commerce->production)) {
            return [
                'summary' => $this->_('Demo order creation is disabled in production mode.'),
                'errors' => [$this->_('Switch to test mode before creating workflow fixtures.')],
            ];
        }

        $product = $this->wire('pages')->get('template=mrc-product, name=ceramics-gift-card, include=all');
        if (!$product || !$product->id) {
            return [
                'summary' => $this->_('Demo order creation failed.'),
                'errors' => [$this->_('Ceramics Gift Card product is missing. Run Mercato installer/repair first.')],
            ];
        }

        $items = $commerce->productList([
            ['id' => (int) $product->id, 'quantity' => 1],
        ])->toArray();
        $cart = $commerce->productList($items);
        $method = strtolower(trim((string) $this->wire('input')->post->text('demo_fulfilment_method')));
        if (!MercatoFulfilmentMethodType::isValid($method)) {
            $method = MercatoFulfilmentMethodType::CARRIER_DELIVERY;
        }
        $snapshot = $this->getDemoFulfilmentSnapshot($commerce, $cart, $method);
        $subtotal = (float) $product->mrc_price;
        $shipping = (float) $snapshot['amount'];
        $total = round($subtotal + $shipping, 2);
        $order = $commerce->orderRepository()->savePendingOrder([
            'first_name' => 'Demo',
            'last_name' => 'Customer',
            'email' => 'demo-order@example.test',
            'notes' => 'Generated by Mercato launch checklist for fulfilment testing. No live payment was processed.',
            'payment_method' => 'demo',
            'payment_status' => Mercato::PAYMENT_STATUS_PAID,
            'payment_complete' => 1,
            'paid_date' => date('Y-m-d H:i:s'),
            'payment_details' => json_encode(['demo' => true, 'source' => 'launch_checklist']),
            'mrc_receipt_details' => json_encode($commerce->buildReceiptDetailsSnapshot($cart, $shipping), JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE),
            'mrc_items' => json_encode($items, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE),
            'mrc_currency' => (string) $commerce->currency,
            'mrc_subtotal_amount' => $subtotal,
            'mrc_shipping_amount' => $shipping,
            'fulfilment_method' => $snapshot['type'],
            'mrc_fulfilment_label' => $snapshot['label'],
            'mrc_fulfilment_details' => json_encode($snapshot, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE),
            'mrc_discount_total' => 0,
            'mrc_total_amount' => $total,
        ]);

        $summary = sprintf($this->_('Created demo paid order %s for %s testing.'), (string) $order->mrc_invoice_number, (string) $snapshot['label']);
        $this->wire('session')->message($summary);
        return [
            'summary' => $summary,
            'order' => $order,
            'errors' => [],
        ];
    }

    protected function handleDemoStorefrontSetup(Mercato $commerce): array {
        if ((string) $this->wire('input')->post->text('mrc_enable_demo_fulfilment') !== '1') {
            return [];
        }
        if (!$this->hasCommercePermission(self::PERMISSION_LAUNCH_TOOLS)) {
            return $this->permissionError(self::PERMISSION_LAUNCH_TOOLS, $this->_('Demo checkout configuration was blocked.'));
        }

        if (!$this->validateCsrf()) {
            return [
                'summary' => $this->_('Demo checkout configuration was blocked. Refresh the page and try again.'),
                'errors' => [$this->_('CSRF token validation failed.')],
            ];
        }

        if (!empty($commerce->production)) {
            return [
                'summary' => $this->_('Demo checkout configuration is disabled in production mode.'),
                'errors' => [$this->_('Switch to test mode before enabling demo receiving methods.')],
            ];
        }

        $modules = $this->wire('modules');
        $config = array_merge(Mercato::getDefaultConfig(), (array) $modules->getConfig('Mercato'));
        $updates = [
            'enabled_fulfilment_methods' => [
                MercatoFulfilmentMethodType::CARRIER_DELIVERY,
                MercatoFulfilmentMethodType::STORE_PICKUP,
                MercatoFulfilmentMethodType::LOCAL_DELIVERY,
            ],
            'store_pickup_address' => trim((string) ($config['store_pickup_address'] ?? '')) !== ''
                ? (string) $config['store_pickup_address']
                : 'Demo Store, 1 High Street, London SW1A 1AA',
            'store_pickup_instructions' => trim((string) ($config['store_pickup_instructions'] ?? '')) !== ''
                ? (string) $config['store_pickup_instructions']
                : 'Bring your order confirmation to the collection desk.',
            'local_delivery_fee' => (float) ($config['local_delivery_fee'] ?? 0) > 0
                ? (float) $config['local_delivery_fee']
                : 4.50,
            'local_delivery_postcodes' => trim((string) ($config['local_delivery_postcodes'] ?? '')) !== ''
                ? (string) $config['local_delivery_postcodes']
                : 'SW1, EC1',
            'local_delivery_instructions' => trim((string) ($config['local_delivery_instructions'] ?? '')) !== ''
                ? (string) $config['local_delivery_instructions']
                : 'Local delivery is available in the configured postcode zone.',
            'enabled_payment_methods' => array_values(array_unique(array_merge(
                (array) ($config['enabled_payment_methods'] ?? []),
                ['demo']
            ))),
            'frontend_framework' => 'tailwind',
            'frontend_auto_assets' => true,
            'frontend_tailwind_cdn_url' => trim((string) ($config['frontend_tailwind_cdn_url'] ?? '')) !== ''
                ? (string) $config['frontend_tailwind_cdn_url']
                : (string) Mercato::getDefaultConfig()['frontend_tailwind_cdn_url'],
        ];

        $config = array_merge($config, $updates);
        if (!$modules->saveConfig('Mercato', $config)) {
            return [
                'summary' => $this->_('Demo checkout configuration could not be saved.'),
                'errors' => [$this->_('ProcessWire rejected the module configuration update.')],
            ];
        }
        foreach ($updates as $key => $value) {
            $commerce->set($key, $value);
        }

        $summary = $this->_('Enabled demo checkout with Delivery, Pickup, Local delivery, Demo Payment, and Tailwind storefront rendering.');
        $this->wire('session')->message($summary);
        return [
            'summary' => $summary,
            'errors' => [],
        ];
    }

    protected function handleDemoDiscountSetup(Mercato $commerce): array {
        if ((string) $this->wire('input')->post->text('mrc_create_demo_discount') !== '1') {
            return [];
        }
        if (!$this->hasCommercePermission(self::PERMISSION_MANAGE_DISCOUNTS)) {
            return $this->permissionError(self::PERMISSION_MANAGE_DISCOUNTS, $this->_('Demo discount setup was blocked.'));
        }

        if (!$this->validateCsrf()) {
            return [
                'summary' => $this->_('Demo discount setup was blocked. Refresh the page and try again.'),
                'errors' => [$this->_('CSRF token validation failed.')],
            ];
        }

        $result = $this->ensureDemoWelcomeDiscount($commerce);
        if (!empty($result['errors'])) {
            return $result;
        }

        $summary = sprintf(
            $this->_('Created demo coupon %s for checkout testing.'),
            (string) ($result['code'] ?? 'WELCOME10')
        );
        if (!empty($result['already_exists'])) {
            $summary = sprintf(
                $this->_('Demo coupon %s is already available for checkout testing.'),
                (string) ($result['code'] ?? 'WELCOME10')
            );
        }
        $this->wire('session')->message($summary);
        return $result + [
            'summary' => $summary,
            'errors' => [],
        ];
    }

    protected function ensureDemoWelcomeDiscount(Mercato $commerce): array {
        $templates = $this->wire('templates');
        $pages = $this->wire('pages');
        $discountTemplate = $templates->get('mrc-discount');
        if (!$discountTemplate) {
            return [
                'summary' => $this->_('Demo discount setup failed.'),
                'errors' => [$this->_('Discount template is missing. Run Mercato installer/repair first.')],
            ];
        }

        $parent = $pages->get('/discounts/');
        if (!$parent || !$parent->id) {
            $parentTemplate = $templates->get('basic-page') ?: $templates->get('home') ?: $discountTemplate;
            $parent = new Page();
            $parent->template = $parentTemplate;
            $parent->parent = $pages->get('/');
            $parent->name = 'discounts';
            $parent->of(false);
            $parent->title = 'Discounts';
            $parent->addStatus(Page::statusHidden);
            $pages->save($parent);
        }

        $existing = $commerce->discountService()->findByCode('WELCOME10');
        $alreadyExists = $existing && $existing->pageId > 0;
        $page = $alreadyExists ? $pages->get((int) $existing->pageId) : null;
        if (!$page || !$page->id) {
            $page = new Page();
            $page->template = $discountTemplate;
            $page->parent = $parent;
            $page->name = 'welcome10';
            $page->of(false);
            $page->title = 'Welcome 10%';
        } else {
            $page->of(false);
        }

        $page->mrc_discount_code = 'WELCOME10';
        $page->mrc_discount_active = 1;
        $page->mrc_discount_type = MercatoDiscountType::PERCENTAGE;
        $page->mrc_discount_percent = 10;
        $page->mrc_discount_amount = 0;
        if ($page->hasField('mrc_discount_usage_limit')) {
            $page->mrc_discount_usage_limit = 0;
        }
        if ($page->hasField('mrc_discount_customer_limit')) {
            $page->mrc_discount_customer_limit = 1;
        }
        if ($page->hasField('mrc_discount_notes')) {
            $page->mrc_discount_notes = 'Demo coupon for validating the discount checkout flow.';
        }
        $pages->save($page);

        return [
            'summary' => '',
            'page_id' => (int) $page->id,
            'code' => 'WELCOME10',
            'already_exists' => $alreadyExists,
            'errors' => [],
        ];
    }

    protected function handleManualOrderCreation(Mercato $commerce): array {
        if ((string) $this->wire('input')->post->text('mrc_create_manual_order') !== '1') {
            return [];
        }
        if (!$this->hasCommercePermission(self::PERMISSION_MANUAL_ORDERS)) {
            return $this->permissionError(self::PERMISSION_MANUAL_ORDERS, $this->_('Manual order creation was blocked.'));
        }

        if (!$this->validateCsrf()) {
            return [
                'summary' => $this->_('Manual order creation was blocked. Refresh the page and try again.'),
                'errors' => [$this->_('CSRF token validation failed.')],
            ];
        }

        $values = $this->getManualOrderFormValues($commerce);
        $action = (string) ($this->wire('input')->post->text('mrc_manual_order_action') ?: 'create');
        if ($action === 'apply_customer') {
            $values = $this->applyManualOrderCustomer($commerce, $values);
            return [
                'summary' => $this->_('Customer details loaded from previous orders.'),
                'errors' => [],
                'values' => $values,
            ];
        }

        $isPreview = $action === 'preview';
        $draft = $this->buildManualOrderDraft($commerce, $values, !$isPreview);
        if (!empty($draft['errors'])) {
            return [
                'summary' => $isPreview ? $this->_('Manual order preview could not be calculated.') : $this->_('Manual order could not be created.'),
                'errors' => (array) $draft['errors'],
                'values' => $values,
            ];
        }

        if ($isPreview) {
            return [
                'summary' => $this->_('Manual order preview calculated. Review the total before creating the unpaid order.'),
                'preview' => $draft,
                'errors' => [],
                'values' => $values,
            ];
        }

        try {
            $cart = $draft['cart'];
            $fulfilment = (array) $draft['fulfilment'];
            $discount = (array) $draft['discount'];
            $subtotal = (float) $draft['subtotal'];
            $shipping = (float) $draft['shipping'];
            $discountAmount = (float) $draft['discount_amount'];
            $total = (float) $draft['total'];
            $addresses = $commerce->buildAddressSnapshots($values, $fulfilment);

            $commerce->orderRepository()->assertStockAvailable($cart);
            $order = $commerce->orderRepository()->savePendingOrder([
                'first_name' => (string) $values['first_name'],
                'last_name' => (string) $values['last_name'],
                'email' => (string) $values['email'],
                'phone' => (string) $values['phone'],
                'address' => (string) $values['address'],
                'city' => (string) $values['city'],
                'zip' => (string) $values['zip'],
                'country' => (string) $values['country'],
                'mrc_billing_address' => json_encode($addresses['billing'], JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE),
                'mrc_shipping_address' => json_encode($addresses['shipping'], JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE),
                'notes' => (string) $values['notes'],
                'payment_method' => (string) $values['payment_method'],
                'payment_status' => Mercato::PAYMENT_STATUS_PENDING,
                'payment_complete' => 0,
                'payment_details' => json_encode(['source' => 'manual_order'], JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE),
                'mrc_receipt_details' => json_encode($commerce->buildReceiptDetailsSnapshot($cart, $shipping), JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE),
                'mrc_items' => json_encode($cart->toArray(), JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE),
                'mrc_currency' => (string) $commerce->currency,
                'mrc_subtotal_amount' => $subtotal,
                'mrc_shipping_amount' => $shipping,
                'mrc_discount_code' => (string) ($discount['code'] ?? ''),
                'mrc_discount_total' => $discountAmount,
                'mrc_discount_details' => json_encode($discount, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE),
                'mrc_total_amount' => $total,
                'fulfilment_method' => (string) ($fulfilment['type'] ?? $values['fulfilment_method']),
                'mrc_fulfilment_label' => (string) ($fulfilment['label'] ?? ''),
                'mrc_fulfilment_details' => json_encode($fulfilment, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE),
            ]);
            $commerce->orderRepository()->reserveStock($order, $commerce->getReservationTtlMinutes());
            if (!empty($discount['valid'])) {
                $commerce->discountService()->recordAuditEvent('attached_to_order', $discount, [
                    'source' => 'manual_order',
                    'email' => (string) $values['email'],
                    'order_page_id' => (int) $order->id,
                    'invoice' => (string) $order->mrc_invoice_number,
                ]);
            }

            $summary = sprintf($this->_('Created manual order %s. Send the payment link to the customer.'), (string) ($order->mrc_invoice_number ?: $order->title));
            $paymentLinkEmail = [];
            if (!empty($values['email_payment_link'])) {
                $service = new MercatoPaymentLinkService($commerce);
                $service->setWire($this->wire());
                $paymentLinkEmail = $service->send($order);
                if (($paymentLinkEmail['status'] ?? '') === 'sent') {
                    $summary = sprintf($this->_('Created manual order %s and sent the payment link.'), (string) ($order->mrc_invoice_number ?: $order->title));
                }
            }
            $this->wire('session')->message($summary);
            return [
                'summary' => $summary,
                'order' => $order,
                'payment_link' => $commerce->getPaymentLinkUrl($order),
                'payment_link_email' => $paymentLinkEmail,
                'errors' => [],
                'values' => $values,
            ];
        } catch (\Throwable $e) {
            return [
                'summary' => $this->_('Manual order could not be created.'),
                'errors' => [$e->getMessage()],
                'values' => $values,
            ];
        }
    }

    protected function buildManualOrderDraft(Mercato $commerce, array $values, bool $auditDiscount): array {
        $errors = [];
        $lineItemMap = [];
        $customItems = [];

        foreach ((array) ($values['items'] ?? []) as $index => $line) {
            $productId = (int) ($line['product_id'] ?? 0);
            $quantity = (int) ($line['quantity'] ?? 0);
            if ($productId <= 0 && $quantity <= 0) {
                continue;
            }
            $product = $this->wire('pages')->get($productId);
            if (!$product || !$product->id || $product->template->name !== 'mrc-product') {
                $errors[] = sprintf($this->_('Line %d: select a valid product.'), $index + 1);
                continue;
            }
            if ($quantity < 1) {
                $errors[] = sprintf($this->_('Line %d: quantity must be at least 1.'), $index + 1);
                continue;
            }
            $key = (int) $product->id;
            if (!isset($lineItemMap[$key])) {
                $lineItemMap[$key] = ['id' => $key, 'quantity' => 0];
            }
            $lineItemMap[$key]['quantity'] += $quantity;
        }

        if (trim((string) ($values['custom_title'] ?? '')) !== '') {
            $customQuantity = (int) ($values['custom_quantity'] ?? 0);
            $customPrice = (float) ($values['custom_price'] ?? 0);
            if ($customQuantity < 1) {
                $errors[] = $this->_('Custom line quantity must be at least 1.');
            }
            if ($customPrice < 0) {
                $errors[] = $this->_('Custom line price cannot be negative.');
            }
            if ($customQuantity > 0 && $customPrice >= 0) {
                $customItems[] = [
                    'id' => 'custom-' . substr(sha1((string) ($values['custom_title'] ?? '') . '|' . microtime(true)), 0, 12),
                    'product_id' => 0,
                    'title' => (string) $values['custom_title'],
                    'price' => $customPrice,
                    'quantity' => $customQuantity,
                    'tax_rate' => max(0, (float) ($values['custom_tax_rate'] ?? $commerce->getDefaultTaxRate())),
                    'shipping_price' => 0.0,
                    'template' => 'mrc-custom-line',
                    'uid' => 'custom-line',
                    'sku' => 'CUSTOM',
                    'stock_policy' => 'service',
                    'stock' => null,
                ];
            }
        }

        $lineItems = array_merge(array_values($lineItemMap), $customItems);
        if (!$lineItems) {
            $errors[] = $this->_('Add at least one product line.');
        }
        if (trim((string) $values['email']) === '' || !filter_var((string) $values['email'], FILTER_VALIDATE_EMAIL)) {
            $errors[] = $this->_('Enter a valid customer email.');
        }
        if (trim((string) $values['first_name']) === '' || trim((string) $values['last_name']) === '') {
            $errors[] = $this->_('Enter the customer first and last name.');
        }
        if (!in_array((string) $values['payment_method'], $commerce->getEnabledPaymentMethods(), true)) {
            $errors[] = $this->_('Select an enabled payment method.');
        }
        if (!in_array((string) $values['fulfilment_method'], $commerce->getEnabledFulfilmentMethods(), true)) {
            $errors[] = $this->_('Select an enabled fulfilment method.');
        }
        if ($errors) {
            return ['errors' => $errors];
        }

        try {
            $cart = $commerce->productList($lineItems);
            $customer = [
                'first_name' => (string) $values['first_name'],
                'last_name' => (string) $values['last_name'],
                'email' => (string) $values['email'],
                'phone' => (string) $values['phone'],
                'address' => (string) $values['address'],
                'city' => (string) $values['city'],
                'zip' => (string) $values['zip'],
                'country' => (string) $values['country'],
            ];
            $fulfilment = $commerce->fulfilmentService()->resolveSelection((string) $values['fulfilment_method'], $cart, $customer);
            $subtotal = $cart->getSubtotal();
            $shipping = round((float) ($fulfilment['amount'] ?? 0), 2);
            $discount = ['valid' => false, 'code' => '', 'amount' => 0.0, 'title' => '', 'type' => ''];
            if (trim((string) ($values['discount_code'] ?? '')) !== '') {
                $discount = $commerce->discountService()->resolveCartDiscount(
                    (string) $values['discount_code'],
                    $cart,
                    (string) $values['email'],
                    $auditDiscount,
                    ['source' => 'manual_order', 'email' => (string) $values['email']]
                );
                if (empty($discount['valid'])) {
                    return ['errors' => [(string) ($discount['message'] ?? $this->_('Discount code could not be applied.'))]];
                }
            }
            $discountAmount = round((float) ($discount['amount'] ?? 0), 2);
            $total = round(max(0, $subtotal + $shipping - $discountAmount), 2);
            $commerce->orderRepository()->assertStockAvailable($cart);

            return [
                'errors' => [],
                'cart' => $cart,
                'items' => $cart->toArray(),
                'fulfilment' => $fulfilment,
                'discount' => $discount,
                'subtotal' => $subtotal,
                'shipping' => $shipping,
                'discount_amount' => $discountAmount,
                'total' => $total,
            ];
        } catch (\Throwable $e) {
            return ['errors' => [$e->getMessage()]];
        }
    }

    protected function getManualOrderFormValues(Mercato $commerce): array {
        $input = $this->wire('input');
        $enabledPayments = $commerce->getEnabledPaymentMethods();
        $sourceOrderId = (int) $this->wire('sanitizer')->int($input->get('source_order'));
        $items = [];
        for ($i = 0; $i < 5; $i++) {
            $items[] = [
                'product_id' => (int) $this->wire('sanitizer')->int($input->post('product_id_' . $i)),
                'quantity' => max(0, (int) $this->wire('sanitizer')->int($input->post('quantity_' . $i))),
            ];
        }
        $values = [
            'items' => $items,
            'first_name' => (string) $input->post->text('first_name'),
            'last_name' => (string) $input->post->text('last_name'),
            'email' => (string) $input->post->email('email'),
            'phone' => (string) $input->post->text('phone'),
            'address' => (string) $input->post->text('address'),
            'city' => (string) $input->post->text('city'),
            'zip' => strtoupper((string) $input->post->text('zip')),
            'country' => strtoupper((string) ($input->post->text('country') ?: 'GB')),
            'notes' => (string) $input->post->textarea('notes'),
            'custom_title' => (string) $input->post->text('custom_title'),
            'custom_price' => max(0, (float) $input->post('custom_price')),
            'custom_quantity' => max(0, (int) $this->wire('sanitizer')->int($input->post('custom_quantity'))),
            'custom_tax_rate' => trim((string) $input->post->text('custom_tax_rate')) !== ''
                ? max(0, (float) $input->post('custom_tax_rate'))
                : $commerce->getDefaultTaxRate(),
            'discount_code' => strtoupper((string) $input->post->text('discount_code')),
            'email_payment_link' => (int) $input->post('email_payment_link') === 1,
            'product_search' => trim((string) ($input->post->text('product_search') ?: $input->get->text('product_q'))),
            'customer_search' => trim((string) $input->post->text('customer_search')),
            'customer_key' => trim((string) ($input->post->text('customer_key') ?: $input->get->text('customer_key'))),
            'source_order_id' => $sourceOrderId,
            'payment_method' => (string) ($input->post->text('payment_method') ?: ($enabledPayments[0] ?? 'stripe-card')),
            'fulfilment_method' => (string) ($input->post->text('fulfilment_method') ?: $commerce->getDefaultFulfilmentMethod()),
        ];

        if ((string) $input->post->text('mrc_create_manual_order') === '' && $sourceOrderId > 0) {
            $values = $this->applyManualOrderSourceOrder($commerce, $values, $sourceOrderId);
        }

        return $values;
    }

    protected function applyManualOrderCustomer(Mercato $commerce, array $values): array {
        $key = trim((string) ($values['customer_key'] ?? ''));
        if ($key === '') {
            return $values;
        }

        foreach ($this->getCustomersFromOrders($commerce) as $customer) {
            if ((string) ($customer['key'] ?? '') !== $key) {
                continue;
            }
            foreach (['first_name', 'last_name', 'email', 'phone', 'address', 'city', 'zip', 'country'] as $field) {
                if (array_key_exists($field, $customer)) {
                    $values[$field] = (string) $customer[$field];
                }
            }
            return $values;
        }

        return $values;
    }

    protected function applyManualOrderSourceOrder(Mercato $commerce, array $values, int $sourceOrderId): array {
        $order = $this->wire('pages')->get($sourceOrderId);
        if (!$order || !$order->id || $order->template->name !== $commerce->order_template) {
            return $values;
        }

        foreach (['first_name', 'last_name', 'email', 'phone', 'address', 'city', 'zip', 'country'] as $field) {
            $orderField = 'mrc_' . $field;
            if ($order->hasField($orderField)) {
                $values[$field] = (string) $order->get($orderField);
            }
        }

        if ((string) ($values['customer_key'] ?? '') === '') {
            $email = strtolower(trim((string) $order->mrc_email));
            $values['customer_key'] = $email !== '' ? $email : 'order-' . (int) $order->id;
        }

        $items = json_decode((string) $order->mrc_items, true);
        if (is_array($items)) {
            $lines = [];
            foreach ($items as $item) {
                $productId = (int) ($item['product_id'] ?? $item['id'] ?? 0);
                if ($productId <= 0) {
                    continue;
                }
                $lines[] = [
                    'product_id' => $productId,
                    'quantity' => max(1, (int) ($item['quantity'] ?? 1)),
                ];
                if (count($lines) >= 5) {
                    break;
                }
            }
            if ($lines) {
                while (count($lines) < 5) {
                    $lines[] = ['product_id' => 0, 'quantity' => 0];
                }
                $values['items'] = $lines;
            }
        }

        if ($order->hasField('mrc_fulfilment_method') && trim((string) $order->mrc_fulfilment_method) !== '') {
            $method = trim((string) $order->mrc_fulfilment_method);
            if (MercatoFulfilmentMethodType::isValid($method)) {
                $values['fulfilment_method'] = $method;
            }
        }

        $values['source_order_id'] = (int) $order->id;
        $values['source_order_label'] = (string) ($order->mrc_invoice_number ?: $order->title);
        return $values;
    }

    protected function getDemoFulfilmentSnapshot(Mercato $commerce, MercatoProductList $cart, string $method): array {
        if ($method === MercatoFulfilmentMethodType::STORE_PICKUP) {
            $details = trim(implode("\n", array_filter([
                trim((string) ($commerce->store_pickup_address ?? '')),
                trim((string) ($commerce->store_pickup_instructions ?? '')),
            ]))) ?: $this->_('Demo pickup location: store collection desk.');
            return [
                'type' => $method,
                'label' => trim((string) ($commerce->store_pickup_label ?? '')) ?: $this->_('Store pickup'),
                'amount' => 0.0,
                'details' => $details,
                'available' => true,
            ];
        }
        if ($method === MercatoFulfilmentMethodType::LOCAL_DELIVERY) {
            return [
                'type' => $method,
                'label' => trim((string) ($commerce->local_delivery_label ?? '')) ?: $this->_('Local delivery'),
                'amount' => round(max(0, (float) ($commerce->local_delivery_fee ?? 0)), 2),
                'details' => trim((string) ($commerce->local_delivery_instructions ?? '')) ?: $this->_('Demo local delivery route.'),
                'available' => true,
            ];
        }
        return [
            'type' => MercatoFulfilmentMethodType::CARRIER_DELIVERY,
            'label' => trim((string) ($commerce->carrier_delivery_label ?? '')) ?: $this->_('Delivery'),
            'amount' => $cart->getShipping(),
            'details' => $this->_('Demo carrier delivery fixture.'),
            'available' => true,
        ];
    }

    protected function handleStockAdjustment(Mercato $commerce): array {
        if ((string) $this->wire('input')->post->text('mrc_adjust_stock') !== '1') {
            return [];
        }
        if (!$this->hasCommercePermission(self::PERMISSION_MANAGE_INVENTORY)) {
            return $this->permissionError(self::PERMISSION_MANAGE_INVENTORY, $this->_('Stock adjustment was blocked.'));
        }

        if (!$this->validateCsrf()) {
            return [
                'summary' => $this->_('Stock adjustment was blocked. Refresh the page and try again.'),
                'errors' => [$this->_('CSRF token validation failed.')],
            ];
        }

        $productId = (int) $this->wire('sanitizer')->int($this->wire('input')->post('product_id'));
        $delta = (int) $this->wire('sanitizer')->int($this->wire('input')->post('stock_delta'));
        $note = trim((string) $this->wire('input')->post->text('stock_note'));
        $product = $this->wire('pages')->get($productId);

        if (!$product || !$product->id || $product->template->name !== 'mrc-product') {
            return [
                'summary' => $this->_('Stock adjustment failed.'),
                'errors' => [$this->_('Product not found.')],
            ];
        }

        $result = $commerce->orderRepository()->adjustProductStock($product, $delta, $note);
        if (!empty($result['errors'])) {
            return [
                'summary' => $this->_('Stock adjustment failed.'),
                'errors' => $result['errors'],
            ];
        }

        $summary = sprintf($this->_('Adjusted stock for "%s" by %+d.'), (string) $product->title, $delta);
        $this->recordProductEvent('product_stock_adjusted', $product, [
            'delta' => $delta,
            'note' => $note,
            'before' => $result['before'] ?? null,
            'after' => $result['after'] ?? null,
        ]);
        $this->wire('session')->message($summary);

        return [
            'summary' => $summary,
            'errors' => [],
        ];
    }

    protected function handleFulfilmentUpdate(Mercato $commerce): array {
        if ((string) $this->wire('input')->post->text('mrc_update_fulfilment') !== '1') {
            return [];
        }
        if (!$this->hasCommercePermission(self::PERMISSION_FULFIL_ORDERS)) {
            return $this->permissionError(self::PERMISSION_FULFIL_ORDERS, $this->_('Fulfilment update was blocked.'));
        }

        if (!$this->validateCsrf()) {
            return [
                'summary' => $this->_('Fulfilment update was blocked. Refresh the page and try again.'),
                'errors' => [$this->_('CSRF token validation failed.')],
            ];
        }

        $orderId = (int) $this->wire('sanitizer')->int($this->wire('input')->post('order_id'));
        $status = strtolower(trim((string) $this->wire('input')->post->text('fulfilment_status')));
        $tracking = trim((string) $this->wire('input')->post->text('fulfilment_tracking'));
        $trackingUrl = trim((string) $this->wire('input')->post('fulfilment_tracking_url'));
        $notes = trim((string) $this->wire('input')->post->textarea('fulfilment_notes'));
        $courier = trim((string) $this->wire('input')->post->text('fulfilment_courier'));
        $proof = trim((string) $this->wire('input')->post->text('fulfilment_proof'));
        $carrierReference = trim((string) $this->wire('input')->post->text('fulfilment_carrier_reference'));
        $labelUrl = trim((string) $this->wire('input')->post('fulfilment_label_url'));
        $order = $this->wire('pages')->get($orderId);

        if (!$order || !$order->id || $order->template->name !== $commerce->order_template) {
            return [
                'summary' => $this->_('Fulfilment update failed.'),
                'errors' => [$this->_('Order not found.')],
            ];
        }

        if (!MercatoFulfilmentStatus::isValid($status)) {
            return [
                'summary' => $this->_('Fulfilment update failed.'),
                'errors' => [$this->_('Invalid fulfilment status.')],
            ];
        }

        $method = $this->getOrderFulfilmentMethod($order);
        if (!in_array($status, $this->getFulfilmentStatusesForMethod($method), true)) {
            return [
                'summary' => $this->_('Fulfilment update failed.'),
                'errors' => [$this->_('This status is not available for the selected fulfilment method.')],
            ];
        }
        if (!$this->fulfilmentMethodSupportsTracking($method)) {
            $tracking = '';
            $trackingUrl = '';
            $labelUrl = '';
        }

        if ($trackingUrl !== '') {
            $trackingUrl = (string) $this->wire('sanitizer')->url($trackingUrl, ['allowRelative' => false]);
            if ($trackingUrl === '') {
                return [
                    'summary' => $this->_('Fulfilment update failed.'),
                    'errors' => [$this->_('Tracking URL must be a valid absolute URL.')],
                ];
            }
        }
        if ($labelUrl !== '') {
            $labelUrl = (string) $this->wire('sanitizer')->url($labelUrl, ['allowRelative' => false]);
            if ($labelUrl === '') {
                return [
                    'summary' => $this->_('Fulfilment update failed.'),
                    'errors' => [$this->_('Label URL must be a valid absolute URL.')],
                ];
            }
        }

        if ($method === MercatoFulfilmentMethodType::LOCAL_DELIVERY) {
            $notes = $this->appendFulfilmentNoteDetail($notes, $this->_('Courier / driver'), $courier);
            $notes = $this->appendFulfilmentNoteDetail($notes, $this->_('Proof of delivery'), $proof);
        } elseif ($method === MercatoFulfilmentMethodType::CARRIER_DELIVERY) {
            $notes = $this->appendFulfilmentNoteDetail($notes, $this->_('Carrier reference'), $carrierReference);
            $notes = $this->appendFulfilmentNoteDetail($notes, $this->_('Label URL'), $labelUrl);
        }

        if (!$order->hasField('mrc_fulfilment_status')) {
            return [
                'summary' => $this->_('Fulfilment update failed.'),
                'errors' => [$this->_('Fulfilment fields are missing. Run Mercato installer/repair from module settings.')],
            ];
        }

        $previousStatus = strtolower(trim((string) $order->mrc_fulfilment_status)) ?: MercatoFulfilmentStatus::UNFULFILLED;
        $previousTracking = $order->hasField('mrc_fulfilment_tracking') ? (string) $order->mrc_fulfilment_tracking : '';
        $previousOrderStatus = $commerce->getDerivedOrderStatus($order);
        $order->of(false);
        $order->mrc_fulfilment_status = $status;
        if ($order->hasField('mrc_fulfilment_tracking')) {
            $order->mrc_fulfilment_tracking = $tracking;
        }
        if ($order->hasField('mrc_fulfilment_tracking_url')) {
            $order->mrc_fulfilment_tracking_url = $trackingUrl;
        }
        if ($order->hasField('mrc_fulfilment_notes')) {
            $order->mrc_fulfilment_notes = $notes;
        }
        if ($order->hasField('mrc_fulfilled_date') && in_array($status, [MercatoFulfilmentStatus::FULFILLED, MercatoFulfilmentStatus::SHIPPED, MercatoFulfilmentStatus::COLLECTED, MercatoFulfilmentStatus::DELIVERED], true)) {
            $order->mrc_fulfilled_date = (string) $order->mrc_fulfilled_date ?: date('Y-m-d H:i:s');
        }
        $this->wire('pages')->save($order);
        $this->recordFulfilmentEvent($order, $previousStatus, $status, $previousTracking, $tracking, $trackingUrl, $notes);
        $commerce->fulfilmentUpdated($order, [
            'source' => 'fulfilmentUpdate',
            'method' => $method,
            'from' => $previousStatus,
            'to' => $status,
            'previous_tracking' => $previousTracking,
            'tracking' => $tracking,
            'tracking_url' => $trackingUrl,
            'notes' => $notes,
        ]);
        $commerce->emitOrderStatusChanged($order, $previousOrderStatus, [
            'source' => 'fulfilmentUpdate',
            'fulfilment_status_from' => $previousStatus,
            'fulfilment_status_to' => $status,
        ]);

        $summary = sprintf($this->_('Updated fulfilment for %s.'), (string) ($order->mrc_invoice_number ?: $order->title));
        $this->wire('session')->message($summary);

        return [
            'summary' => $summary,
            'errors' => [],
        ];
    }

    protected function appendFulfilmentNoteDetail(string $notes, string $label, string $value): string {
        if ($value === '') {
            return $notes;
        }

        return trim($notes . "\n" . $label . ': ' . $value);
    }

    protected function recordFulfilmentEvent(Page $order, string $from, string $to, string $previousTracking, string $tracking, string $trackingUrl, string $notes): void {
        $log = new MercatoFulfilmentEventLog();
        $log->setWire($this->wire());
        $log->updated($order, $from, $to, $previousTracking, $tracking, $trackingUrl, $notes, (string) ($this->wire('user')->name ?? ''));
    }

}
